### ISSUE TITLE
Improve help command

### ISSUE THREAD

**Issue by weeco** [nestjs/nest-cli#102]
Currently the help command doesn't return a list of all available commands.

I am not sure if this is by design or a bug with the windows powershell, hence I attach this screenshot:

![](https://i.imgur.com/Z7E8WG4.png)

**Comment by ThomRick** [comment]
Never tested with windows powershell in fact so thanks for your feedbacks @weeco :-)
I'll check that to improve display on windows powershell.
You can use the docker image if you want a full cli experience 'till this will be fixed ;-)

**Comment by ThomRick** [comment]
Same as #103
