### ISSUE TITLE
Manage javascript language

### ISSUE THREAD

**Issue by ThomRick** [nestjs/nest-cli#104]
AS a user I WANT TO use javascript as main language TO manage my Nest project

**Comment by 1valdis** [comment]
I see this marked as Done but I don't see anything in documentation that says how to generate a project in pure JS. So, how do I do that?

**Comment by lahvey** [comment]
From the starter, but stopped here.

**Comment by ThomRick** [comment]
Hey guys ! 
With the CLI `new` command you can pass `-l js` option to generate project in pure JavaScript but I don't recommend this 
```shell
$ nest new project-name -l js
```

**Comment by stormwatch** [comment]
@1valdis It is documented in [cli usage](https://docs.nestjs.com/cli/usages) but not in the output of `nest new --help`. I tried first by passing `-l JavaScript` which throws a cryptic ENOENT.
