### ISSUE TITLE
> PartialType class should be imported from @nestjs/swagger.

### ISSUE THREAD

**Issue by shamim-42** [nestjs/nest-cli#1046]
> PartialType class should be imported from @nestjs/swagger.

In case of GraphQL applications, `PartialType` **must** be imported from the `@nestjs/graphql`.

_Originally posted by @kamilmysliwiec in https://github.com/nestjs/nest-cli/issues/1045#issuecomment-780372402_

**Comment by shamim-42** [comment]
If I don't import it from `@nestjs/swagger` it is showing the below error and app can't be started anyway.

`Error: Unable to find fields for GraphQL type CreateUserInput. Is your class annotated with an appropriate decorator?`

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by shamim-42** [comment]
Okay Kamil, Thank you!
