### ISSUE TITLE
Use better CLI framework 

### ISSUE THREAD

**Issue by ThomRick** [nestjs/nest-cli#106]
Caporaljs is no longer maintained... see to use Commander or EmberCLI as AngularCLI do

**Comment by weeco** [comment]
Agreed, I am facing issues again and again and to be honest I got tired reporting them here. Really a pitty I can not use the Nest CLI, becaues it would definetely help to improve productivity.

I'll give it a shot again once you switched to a different CLI framework.

**Comment by weeco** [comment]
@ThomRick that was absolutely not meant to be an allegation. I just wanted to emphasize that there is another good reason to change the CLI framework and that there are still issues to be resolved.

I am aware that you are doing this just in your free time and I think we all highly appreciate your efforts!
