### ISSUE TITLE
Add ability to choose default branch when generating a new app. (main/master)

### ISSUE THREAD

**Issue by BatuhanW** [nestjs/nest-cli#1060]
## I'm submitting a...

[x] Feature request

## Current behavior

Currently, nest-cli creates a new application with the default `master` branch. I think it would be nice to ask the user about the preferred default branch. Just like it asks npm/yarn. I'd like to implement it if it's something that you'll consider.

## Expected behavior

CLI will ask the user for the preferred default branch.

## What is the motivation / use case for changing the behavior?

Since GitHub switched the default branch to main, it would be nice to support that.

**Comment by jmcdo29** [comment]
The Nest CLI calls `git init` under the hood. If you have your git config set up to use `main` it will use main. If you have it set up use `master` it will use `master`. 

You can set this config using `git config --global init.defaultBranch main`, and [find more information on it here](https://github.blog/2020-07-27-highlights-from-git-2-28/#introducing-init-defaultbranch)
