### ISSUE TITLE
Exec a service using nestjs/cli

### ISSUE THREAD

**Issue by felinto-dev** [nestjs/nest-cli#1105]
## Is your feature request related to a problem? Please describe.
Hi!

I would like to suggest that it is possible to run a NestJS service through the command line.

## Describe the solution you'd like
I had this idea when using a utility called "Scrapy", available for Python. This is software to crawl pages and allows you to test a function (in NestJS we use service) in isolation.
https://docs.scrapy.org/en/latest/topics/debug.html#parse-command
```
scrapy parse --spider=myspider -c parse_item -d 2 <item_url>
```

I would like to see something like that at NestJS:
```
nest service exec moduleName serviceName -d { param1: 'a', param2: 'b' }
```

## Teachability, Documentation, Adoption, Migration Strategy
Users will be able to use this functionality when they need to access an application resource without necessarily using any means of transport, such as HTTP. Something local.

This would also make room for complex applications using shell scripts and architectures with NodeJS.
Otherwise, is useful for fast debug too.

**Comment by jmcdo29** [comment]
The best thing you could do in this case is make use of something like [nest-commander](https://github.com/jmcdo29/nestjs-commander) (disclaimer: I'm the author of it) which is pretty much what Kamil has said in [this issue](https://github.com/nestjs/nest/issues/4716). It seems to be what you're looking for, but it will require some setup code around your service. You can see an example [of this library here](https://github.com/jmcdo29/ogma/tree/main/packages/cli) (another package of mine)

**Comment by felinto-dev** [comment]
Thank you for helping the NestJS community @jmcdo29 

Very appreciate!
