### ISSUE TITLE
Error nest-cli generate new and nest info

### ISSUE THREAD

**Issue by menme95** [nestjs/nest-cli#114]
I was going to migrate my nest project, I've installed nest-cli and when I generate the project with json mange package, it failed.
When I opened the documents, everything were numbers in all de docs:
![image](https://user-images.githubusercontent.com/22968155/39583311-187cdbe8-4ef0-11e8-9469-432b23762e3c.png)

Then I did nest info, and I got it.

![image](https://user-images.githubusercontent.com/22968155/39583237-f1999d36-4eef-11e8-8339-ad7f4f29d0d4.png)

How can I fix it?

**Comment by ThomRick** [comment]
Hey @menme95 ! 
You just have to upgrade to node >= 8.9.0
