### ISSUE TITLE
Add either documentation or feature for watchAssets server reload for non-ts files

### ISSUE THREAD

**Issue by rbutera** [nestjs/nest-cli#1140]
## I'm submitting a...
[x] Feature request
[x] Documentation issue or request

## Current behavior
As outlined in #1136, it is not possible to configure nestjs to reload the server when a non-ts file changes.

There is no documentation or resource out there (that I can find) that demonstrates how to achieve this using webpack and a custom file loader.

The behaviour as it is currently is misleading. It is not clear from the docs that `watchAssets` is strictly for copying to `dist` (and this is unusual behaviour for most file-watching integrations of development servers) and it should definitely be documented better.

## Expected behavior

Either:

1. **documentation update**: documentation should be written that at a *bare minimum* a) clarifies that `watchAssets` is strictly for copying to `dist`, or *ideally* b) directs developers using NestJS how to achieve this functionality, perhaps as a recipe in the docs. *OR...*
2. **functionality addition**: the ability to optionally restart the server will be added to `nest-cli` for specified assets, but disabled by default. (in my opinion, this is a generally more preferred option)

For example:

```json
{
  "compilerOptions": {
    "assets": [
       { "include": "**/*.txt", "watchAssets": true, "reload": true },
       { "include": "**/*.png", "watchAssets": true, "reload": false },
    ], 
  }
}
```

By including the property `reload` and setting it to true on a member of the `assets` array with `watchAssets === true`, then any change to a file that matches the blob will result in a server reload.
 
By default, `reload` should be `false`, therefore existing projects and configurations would work as-is.

## Minimal reproduction of the problem with instructions
https://github.com/rbutera/nest-oso-repro

## What is the motivation / use case for changing the behavior?

Changing the behaviour would massively improve the developer experience for any NestJS project that integrates with a library / service that uses non-ts files for configuration.

For example, the authorization library `oso` uses `.polar` files for authorization rule definitions. It is an awesome library with a Nestjs integration which makes implementing authorization into NestJS applications very simple. Unfortunately, the user must manually restart the server on every update to the definition files.

**Comment by rbutera** [comment]
I did some digging in this repo to see how the proposed solution might be implemented.

First, I determined that the option to reload should be added to the interfaces `AssetEntry` and `ActionOnFile` in `lib/configuration/configuration.ts`:

```typescript
export interface AssetEntry {
  glob: string;
  include?: string;
  flat?: boolean;
  exclude?: string;
  outDir?: string;
  watchAssets?: boolean;
  reload: boolean;
}

export interface ActionOnFile {
  action: 'change' | 'unlink';
  item: AssetEntry;
  path: string;
  sourceRoot: string;
  watchAssetsMode: boolean;
  reload: boolean;
}
```

Then I determined that `lib/compiler/assets-manager.ts` is responsible for handling assets.

First of all, we could add a boolean property to the class that tracks whether or not we are in the initial asset loading phase:

```typescript
  private initialLoadPhase = true; // set to false once initial load has concluded, as we don't want to restart the server when files are initially loaded
```

The `filesToCopy` array in the `copyAssets` method needs to be updated to include the `reload` property in the `AssetEntry` if it is set in configuration, otherwise set it to `false`:

```typescript
const filesToCopy = assets.map<AssetEntry>((item) => {
        if (typeof item === 'string') {
          return {
            glob: join(sourceRoot, item),
            outDir,
          };
        }
        return {
          outDir: item.outDir || outDir,
          glob: join(sourceRoot, item.include!),
          exclude: item.exclude ? join(sourceRoot, item.exclude) : undefined,
          flat: item.flat, // deprecated field
          watchAssets: item.watchAssets,
          reload: item.reload ?? false,
        };
      });
``` 

Also, if the asset definition is just a glob (string), then we need to manually set reload to false:

```typescript
        if (typeof item === 'string') {
          return {
            glob: join(sourceRoot, item),
            outDir,
            reload: false,
          };
        }
```

Then, when creating the array of `watchers`, the value of `reload` needs to be extracted and included in the `option`:

```typescript
        const option: ActionOnFile = {
          action: 'change',
          item,
          path: '', // why is this always an empty string?
          sourceRoot,
          reload: item.reload,
          watchAssetsMode: isWatchEnabled,
        };
```

Once all the watchers have been added, we set the value of `initialLoadPhase` to false. 

```typescript
      // all file watchers added, now schedule the end of initial load phase
      setTimeout(() => {
        this.initialLoadPhase = false;
      }, getValueOrDefault<number>(configuration, 'compilerOptions.loadTimeout', appName, 'path', undefined, 30000));
```

It should be noted that we add an optional property to `CompilerOptions` that specifies the length in time of the initial load phase.

```typescript
interface CompilerOptions {
  tsConfigPath?: string;
  webpack?: boolean;
  webpackConfigPath?: string;
  plugins?: string[];
  assets?: string[];
  deleteOutDir?: boolean;
  loadTimeout?: number;
}
```

Above, I suggest a default of 30 seconds, but maybe we could extend that number if build times are expected to be longer than that?

Next, in `actionOnFile` we determine if we need to reload on change:

```typescript
    const shouldReloadOnChange = reload && isWatchEnabled && !this.initialLoadPhase;
```

The final step, which I can't quite figure out yet, is actually triggering the reload after copying the file to the output dir.

```typescript
  private actionOnFile(option: ActionOnFile) {
    const { action, item, path, sourceRoot, watchAssetsMode, reload } = option;
    const isWatchEnabled = watchAssetsMode || item.watchAssets;
    const shouldReloadOnChange = reload && isWatchEnabled;

    // Allow to do action for the first time before check watchMode
    if (!isWatchEnabled && this.watchAssetsKeyValue[path]) {
      return;
    }

    // Set path value to true for watching the first time
    this.watchAssetsKeyValue[path] = true;

    const dest = copyPathResolve(
      path,
      item.outDir!,
      sourceRoot.split(sep).length,
    );

    // Copy to output dir if file is changed or added
    if (action === 'change') {
      shell.mkdir('-p', dirname(dest));
      shell.cp(path, dest);
    } else if (action === 'unlink') {
      // Remove from output dir if file is deleted
      shell.rm(dest);
    }

    // TODO: trigger reload if new file added after initial load phase
    if(shouldReloadOnChange) {
      this.closeWatchers();
      // TODO: how to reload server here?????
    }
  }
}
```

any guidance as to next steps for implementing this?

Will submit a PR and update documentation if we can get this done.

I'm sick of alt+tab, ctrl+C, up arrow, enter, wait for compilation to finish. It feels like I'm back in 2008 🤣️

**Comment by rbutera** [comment]
I have created a draft PR for review here 
https://github.com/nestjs/nest-cli/pull/1142

help appreciated

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest-cli/pull/1142
