### ISSUE TITLE
Generating fails in Windows due to a space in global node_modules path

### ISSUE THREAD

**Issue by funkizer** [nestjs/nest-cli#123]
@nestjs/cli@5.1.2
Node: 8.11.1 (tried also 8.10.x)
NPM: 6.0.1 (tried also 5.5.1)
Windows 10 x64

`nest new my-app` fails because the path to schematics isn't enclosed in quotes:

```
'C:\Users\User' is not recognized as an internal or external command,
operable program or batch file.
🙀  Failed to execute command: 
C:\Users\User Name\AppData\Roaming\npm\node_modules\@nestjs\cli\node_modules\.bin\schematics @nestjs/schematics:application --name=my-app --description=description --version=1.0.0 --aut
hor= --dry-run=false
```

I was able to run the command and generate an app manually by quoting the path:

```
"C:\Users\User Name\AppData\Roaming\npm\node_modules\@nestjs\cli\node_modules\.bin\schematics" @nestjs/schematics:application --name=my-app --description=description --version=1.0.0 --author= --dry-run=false
```

Haven't tried other CLI commands yet, but assuming I'll face the same problem again.

**Comment by ThomRick** [comment]
Hey @funkizer 

Thanks for feedbacks.
Yeah you'll got the same issue with other commands.

I'm on it ! Hope to release soon the bug fix !
