### ISSUE TITLE
[Feature Request] Please add an option for generating a test file only

### ISSUE THREAD

**Issue by jezsung** [nestjs/nest-cli#1238]
Sometimes, I prefer to delete the generated test files for fast development and later add tests for some of the cases. It would be great if I can do something like `nest g co example --only-spec`.

**Comment by jmcdo29** [comment]
If we were to implement this, how in depth would the file generation go? I a provider has, say 15 dependencies (and I really hope it doesn't), should the spec generation take care of a simple mock up for each of them? Should it just add the dependencies to the `providers` array? Or should it generate a test file that doesn't actually pass and have none of the dependencies? 

It usually isn't too troublesome to set up a test file, and you could always create a snippet as well to help do it if this is something that's a common occurrence. I don't know of many people that delete the initial test files only to want to add them back later via CLI.

**Comment by jezsung** [comment]
@jmcdo29 I wanted it to generate a basic initial test file just like what it is already doing. I prefer to delete unused test files cuz it causes me to click them accidentally and it reduces my productivity. Is there a VSCode extension for generating snippets for Nest.js?

**Comment by jmcdo29** [comment]
Definitely a common plugin from what I can tell. The first three seem pretty promising for what you're looking for. Personally I think this is more than what the CLI should be responsible for.

![image](https://user-images.githubusercontent.com/28268680/125013193-3c4a2700-e020-11eb-82fb-cf3d6c072e3e.png)

**Comment by jezsung** [comment]
@jmcdo29 Looks good! Thanks for your suggestion
