### ISSUE TITLE
How to change `defaultOutDir` value ?

### ISSUE THREAD

**Issue by Kronhyx** [nestjs/nest-cli#1243]
https://github.com/nestjs/nest-cli/blob/6379b32fb527730f54003df1ca1671bbeb259d4c/lib/configuration/defaults.ts#L20

**Comment by micalevisk** [comment]
https://github.com/nestjs/nest-cli/blob/499ac3f715568667f59692d51caa4e20aaa79551/actions/start.action.ts#L48

thus just set the `outDir` in your tsconfig

![image](https://user-images.githubusercontent.com/13461315/126045850-5f261d00-ef11-4ef1-ad98-8fe366225c3f.png)
https://www.typescriptlang.org/tsconfig#outDir
