### ISSUE TITLE
Folder generation

### ISSUE THREAD

**Issue by Grimscythe1983** [nestjs/nest-cli#125]
It would comply with Angular's CLI if Nest CLI would create folders only when specifically told so. Running `nest g service foo` makes a folder called `foo`. The correct way (I believe) is calling `nest g service foo/foo` to make a `foo` service in `foo` folder.

It just provides more control.

**Comment by asi-np** [comment]
If this has been implemented, how is it used?  There are no flags in the documentation and the issue persists when generating services according to the documented method.

**Comment by koboldt** [comment]
Use option --flat (see https://docs.nestjs.com/cli/usages)

**Comment by MightyCryptowall** [comment]
> 
> 
> Use option --flat (see https://docs.nestjs.com/cli/usages)



> 
> 
> Use option --flat (see https://docs.nestjs.com/cli/usages)

This works for me, Thank @koboldt
