### ISSUE TITLE
You have to manually update your Jest configuration (for e2e tests) by updating the `moduleNameMapper` configuration. This **may** change in the future if we decide to merge this PR https://github.com/nestjs/schematics/pull/532

### ISSUE THREAD

**Issue by SergiiVlasiuk** [nestjs/nest-cli#1259]
You have to manually update your Jest configuration (for e2e tests) by updating the `moduleNameMapper` configuration. This **may** change in the future if we decide to merge this PR https://github.com/nestjs/schematics/pull/532

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for further questions. We are using GitHub to track bugs, feature requests, and potential improvements.

_Originally posted by @kamilmysliwiec in https://github.com/nestjs/nest-cli/issues/1257#issuecomment-888982057_

Can you please add more details how to fix the configuration!?

**Comment by kamilmysliwiec** [comment]
![image](https://user-images.githubusercontent.com/23244943/127506851-09b820b0-bf45-4b78-b9c1-f90497f7b779.png)
