### ISSUE TITLE
Cannot be used as a build tool...

### ISSUE THREAD

**Issue by wendellmva** [nestjs/nest-cli#126]
when using angular/cli I can do => ng new test --skip-install perfect for automated builds. I would like to see the same for nest/cli.

I am using shelljs to automatically generate a new nest project but it  breaks the process. Even when you provide all the options => nest new test "This is the description" "0.0.0" "wendellmva" 

it still prompts for the package manager, so I wanted to suggest two more parameters --pm=yarn|npm and also --skip-install to skip the install.

I this a good Idea? Do you accept pr's?

**Comment by ThomRick** [comment]
Hey @wendellmva 

Everything that you noticed seem great !
In fact we were focused on the generate part for the Nest v5 release.

The build tools are currently in development so it would be great to get you involved to the project ! ;-)

Don't hesitate to PR that is the best contribution to Nest :-)
Don't forget to sign your commits with GPG for that or I could not merge them (I protected the persistant branches)

I just would like you create issues when you want to work on something and PR to solve them. Just for organisation ;-)

Thanks

**Comment by wendellmva** [comment]
ok, no problem I will get back to with a working pr!
