### ISSUE TITLE
Asset Copy : Check Asset copy success

### ISSUE THREAD

**Issue by Amirault** [nestjs/nest-cli#1270]
<pre><code>
[ X ] Bug report
</code></pre>

## Current behavior

A problem occurs with the asset copy in our project sometimes the copy work sometimes not... 

## Expected behavior : 

Asset copy success or a compile time error

## Minimal reproduction of the problem with instructions

Having a folder with a lot of assets inside and try to read it at runtime.

## What is the motivation / use case for changing the behavior?

We only find out the problem at the runtime when reading the concerned directory (with the error `Error: ENOENT: no such file or directory, scandir `).

After looking on the nest code base it's possible that the watcher close to early but we are not sure about that.

We are wondering if it's possible to have a safe check that the file copied successfully  in order to have 
a compile time Error ? 

(maybe after the copy https://github.com/nestjs/nest-cli/blob/dbdb33541c734924290ce13178b1264cd3f79670/actions/build.action.ts#L105)

Thank you in advance for your answer !

**Comment by Amirault** [comment]
@kamilmysliwiec @ThomRick ?

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

**Comment by Amirault** [comment]
@kamilmysliwiec what's your point about closing this one ?

It's hard to reproduce while it's random;

I'm wandering a compile check in order to now when it's success and when it's not

**Comment by squalsoft** [comment]
I have the same issue. Random copying in dist on Ubuntu but on my mac everything is ok.

**Comment by alumni** [comment]
We also have a similar issue due to the 500s timeout. It happens even with small files (<10kB).
