### ISSUE TITLE
nest-cli can`t build assest file in dist

### ISSUE THREAD

**Issue by CloudWoR** [nestjs/nest-cli#1272]
## Environment

```
webpack 5.28.0 compiled successfully in 4476 ms
Using Unsupported mongoose version, highest supported is 5.10.18 (Current version: 5.12.3)
[Nest] 12292   - 2021/08/08 上午11:27:02   [NestFactory] Starting Nest application...
[Nest] 12292   - 2021/08/08 上午11:27:02   [ExceptionHandler] ENOENT: no such file or directory, open 'D:\CloudWoR\HUIXIANG\demo\server\dist\apps\server\config.yaml' +39ms
Error: ENOENT: no such file or directory, open 'D:\CloudWoR\HUIXIANG\demo\server\dist\apps\server\config.yaml'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at InstanceWrapper.exports.default [as metatype] (D:\CloudWoR\HUIXIANG\demo\server\dist\apps\server\main.js:635:27)
    at Injector.instantiateClass (D:\CloudWoR\HUIXIANG\demo\server\node_modules\@nestjs\core\injector\injector.js:289:55)
    at callback (D:\CloudWoR\HUIXIANG\demo\server\node_modules\@nestjs\core\injector\injector.js:42:41)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Injector.resolveConstructorParams (D:\CloudWoR\HUIXIANG\demo\server\node_modules\@nestjs\core\injector\injector.js:114:24)
    at async Injector.loadInstance (D:\CloudWoR\HUIXIANG\demo\server\node_modules\@nestjs\core\injector\injector.js:46:9)
    at async Injector.loadProvider (D:\CloudWoR\HUIXIANG\demo\server\node_modules\@nestjs\core\injector\injector.js:68:9)
    at async Promise.all (index 4)
    at async InstanceLoader.createInstancesOfProviders (D:\CloudWoR\HUIXIANG\demo\server\node_modules\@nestjs\core\injector\instance-loader.js:43:9)
    at async D:\CloudWoR\HUIXIANG\demo\server\node_modules\@nestjs\core\injector\instance-loader.js:28:13
    at async Promise.all (index 6)
    at async InstanceLoader.createInstances (D:\CloudWoR\HUIXIANG\demo\server\node_modules\@nestjs\core\injector\instance-loader.js:27:9)
    at async InstanceLoader.createInstancesOfDependencies (D:\CloudWoR\HUIXIANG\demo\server\node_modules\@nestjs\core\injector\instance-loader.js:17:9)
    at async D:\CloudWoR\HUIXIANG\demo\server\node_modules\@nestjs\core\nest-factory.js:90:17
```
why configure to yaml file can not build in dist 📂?my config file create in library，like this

base dir: 
```
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       2021-08-08     10:50                apps
d-----       2021-08-08     11:25                dist
d-----       2021-08-08     10:57                libs
d-----       2021-08-08      9:59                node_modules
-a----       2021-06-08     17:11           1451 .eslintrc.js
-a----       2021-06-08     17:11            408 .gitignore
-a----       2021-06-08     17:11             54 .prettierrc
-a----       2021-08-07     10:04             44 .test.env
-a----       2021-08-08     11:27           1809 nest-cli.json
-a----       2021-08-08     11:09           3352 package.json
-a----       2021-08-07     10:18             23 process.env
-a----       2021-06-08     17:11           3672 README.md
-a----       2021-06-08     17:11            101 tsconfig.build.json
-a----       2021-08-08     11:09            883 tsconfig.json
-a----       2021-06-08     17:11            444 tslint.json
-a----       2021-08-08      9:59         311391 yarn.lock
```
libs dir
```
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       2021-08-08     11:22                configure
d-----       2021-06-08     17:11                local-db
d-----       2021-06-08     17:11                pacsdb
d-----       2021-06-08     19:14                worklistdb
```
nest-cli.json file
```
{
  "collection": "@nestjs/schematics",
  "sourceRoot": "apps/server/src",
  "monorepo": true,
  "root": "apps/server",
  "compilerOptions": {
    "webpack": true
  },
  "projects": {
    "server": {
      "type": "application",
      "root": "apps/server",
      "entryFile": "main",
      "sourceRoot": "apps/server/src",
      "compilerOptions": {
        "tsConfigPath": "apps/server/tsconfig.app.json"
      }
    },
    "admin": {
      "type": "application",
      "root": "apps/admin",
      "entryFile": "main",
      "sourceRoot": "apps/admin/src",
      "compilerOptions": {
        "tsConfigPath": "apps/admin/tsconfig.app.json"
      }
    },
   ...
    "configure": {
      "type": "library",
      "root": "libs/configure",
      "entryFile": "index",
      "sourceRoot": "libs/configure/src",
      "compilerOptions": {
        "tsConfigPath": "libs/configure/tsconfig.lib.json",
        "assets": [
          {
            "include": "../configure/*.yaml",
            "outDir": "./dist/apps/server"
          }
        ],
        "watchAssets": true
      }
    }
  }
}
```
run nets start -dev server，can`t build assets file in dist.

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

**Comment by CloudWoR** [comment]
wait a minute.

**Comment by CloudWoR** [comment]
https://github.com/CloudWoR/nestAssest.git

> 请提供[最小的复制存储库](http://minimum-reproduction.wtf)。

https://github.com/CloudWoR/nestAssest.git

**Comment by jmcdo29** [comment]
That's not a minimum reproduction.. That has database dependencies and all sorts of unnecessary code for a _minimum reproduction_. Please, provide a **minimum** reproduction so we can diagnose this problem more easily.

If you need more information on what a minimum reproduction is, please click on the link in my first comment.

**Comment by CloudWoR** [comment]
> That's not a minimum reproduction.. That has database dependencies and all sorts of unnecessary code for a _minimum reproduction_. Please, provide a **minimum** reproduction so we can diagnose this problem more easily.
> 
> If you need more information on what a minimum reproduction is, please click on the link in my first comment.
i delete orhter files and packge.json,
https://github.com/CloudWoR/nestAssest.git

**Comment by CloudWoR** [comment]
> > That's not a minimum reproduction.. That has database dependencies and all sorts of unnecessary code for a _minimum reproduction_. Please, provide a **minimum** reproduction so we can diagnose this problem more easily.
> > If you need more information on what a minimum reproduction is, please click on the link in my first comment.
> > i delete orhter files and packge.json,
> > https://github.com/CloudWoR/nestAssest.git in minimum branch

dose it meet the standard by minimum reproduction?  thanks

**Comment by jmcdo29** [comment]
I can't reproduce your problem using your `minimum` branch. 

Screenshot of the terminal

![image](https://user-images.githubusercontent.com/28268680/128656507-89f4f747-2335-45a5-a26a-171bf89d013a.png)

Screenshot of the directory inside of VSCode

![image](https://user-images.githubusercontent.com/28268680/128656541-92861b75-843c-426b-8ec6-76585ebe660d.png)

Looks like it's working as expected.

**Comment by CloudWoR** [comment]
libs/configure/configure have a yaml file: configInLibrary.yaml want build this file in dist.

**Comment by jmcdo29** [comment]
That's not what your minimum reproduction is doing, and there's no info in the README about it, like the link above states there should be, so how are we supposed to know  what should and shouldn't happen? You mentioned in the original issue that `start:dev server` doesn't work, I ran the command and it does. To me, seems like a problem on your end.

**If this is not the case please, _for the last time_, provide a [minimum reproduction repository](http://minimum-reproduction.wtf)**

**Comment by CloudWoR** [comment]
sorry, Delay your time, i`m push a new minimun, please help me.

**Comment by CloudWoR** [comment]
https://github.com/CloudWoR/nestAssest.git

**Comment by CloudWoR** [comment]
https://github.com/CloudWoR/nestAssest.git

**Comment by jmcdo29** [comment]
Your "minimum" reproduction now requires Mongo running to properly run... 

Anyways, the problem here is that you're expecting the assets of a different project (the `configure` project) to be moved when you build the `server` project which requires `configure`. I'm not sure if I'm aware of _any_ monorepo manager that would move assets of a different project on build. You might have luck using [`nx`](https://nx.dev) as they have a `dependsOn` that can be configured, and the projects _might_ properly then move assets per project, but this is not a feature of the Nest monorepo mode. You tell Nest to build project `server` and it will move the assets required to build `server`. That's just how it is
