### ISSUE TITLE
Dependabot security update

### ISSUE THREAD

**Issue by ilteoood** [nestjs/nest-cli#1368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The latest possible version that can be installed is 3.0.0 because of the following conflicting dependencies:

@nestjs/cli@8.1.2 requires ansi-regex@^3.0.0 via a transitive dependency on strip-ansi@4.0.0
eslint@6.8.0 requires ansi-regex@^4.1.0 via strip-ansi@5.2.0
eslint@6.8.0 requires ansi-regex@^4.1.0 via strip-ansi@5.2.0
The earliest fixed version is 5.0.1.

### Minimum reproduction code

https://github.com/ilteoood/sesamo-backend

### Steps to reproduce

Install dependabot on a nest project

### Expected behavior

Security alert disappear

### Package version

8.1.2

### NestJS version

8.0.11

### Node.js version

14.17.6

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
> Install dependabot on a nest project

We use both dependabot and renovate. Likely the package you mentioned is already upgraded, it just waits for triggering a new release of the package.
