### ISSUE TITLE
Installing/validating dependencies using CLI

### ISSUE THREAD

**Issue by nickerlan** [nestjs/nest-cli#1397]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Over and over again I'm facing the same issue.
I create new NestJS project with cli, then I go to documentation to install features I need.
And then something goes wrong. I'm struggling to understand why previous NestJS projects worked as expected, and this new one fails.
After I go here and realise that even going by recommended steps in documentation I've installed unsupported versions of something.

e.g. `yarn add graphql` gives me v.16, which I find out to be yet unsupported. I've downgraded it, it made difference, but still graphql nest-cil plugin doesn't work, probably because some other deps. And I have nowhere to check on it.

### Describe the solution you'd like

It would be nice to have cli-based installation of latest-supported key dependencies or at least linter to show which versions should be downgraded to what numbers.

If there already some other solution for that, please add it to documentation.

### What is the motivation / use case for changing the behavior?

I think that steps described in NestJS docs should always lead to expected results.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
