### ISSUE TITLE
TypeScript "importsNotUsedAsValues" compiler option doesn't take effect while using path alias or baseUrl

### ISSUE THREAD

**Issue by RageYL** [nestjs/nest-cli#1406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```
import type { MyType } from 'mymodule';
```

generates

```
const mymodule_1 = require('...')
```

This problem was already reported in this closed issue: https://github.com/nestjs/nest-cli/issues/783.

### Minimum reproduction code

```typescript
import { TypeA } from 'src/type-a'
import type { TypeB } from 'src/type-b'
import { TypeC } from './type-c'
import type { TypeD } from './type-d'
```

```sh
npm run build generates:
```

```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const type_a_1 = require("./type-a");
const type_b_1 = require("./type-b");
```

### Steps to reproduce

https://github.com/RageYL/nest-cli-type-imports-bug

### Expected behavior

No code should be emitted for type only imports.

### Package version

8.1.2

### NestJS version

8.1.2

### Node.js version

14.17.6

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

From a quick google, we can skip the existing logic in https://github.com/nestjs/nest-cli/blob/master/lib/compiler/hooks/tsconfig-paths.hook.ts#L18 with the following edit:

````
-          tsBinary.isImportDeclaration(node) ||
+          (tsBinary.isImportDeclaration(node) && !node.importClause?.isTypeOnly) ||
```

**Comment by jmcdo29** [comment]
Can you make a git repo with the steps to reproduce, so we can just clone, install, and verify the issue?

**Comment by RageYL** [comment]
Created a repo from scratch using @nestjs/cli and edited the main file: https://github.com/RageYL/nest-cli-type-imports-bug

**Comment by liaoyinglong** [comment]
has anything news?

**Comment by jmcdo29** [comment]
This slipped my radar for a bit, sorry about that. The reproduction does indeed reproduce and shows tsc working as expected, and the proposed code change does fix up `nest build` so that it acts like `tsc` in this case. I'll get a PR made for fixing this done today

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest-cli/pull/1449
