### ISSUE TITLE
Unsupported engine @nestjs/cli 8.1.4 

### ISSUE THREAD

**Issue by jimmydls** [nestjs/nest-cli#1409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

➜  Codes npm i -g @nestjs/cli
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/core@12.2.10',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     node: '^12.14.1 || >=14.0.0',
npm WARN EBADENGINE     npm: '^6.11.0 || ^7.5.6',
npm WARN EBADENGINE     yarn: '>= 1.13.0'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v16.11.1', npm: '8.0.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/schematics@12.2.10',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     node: '^12.14.1 || >=14.0.0',
npm WARN EBADENGINE     npm: '^6.11.0 || ^7.5.6',
npm WARN EBADENGINE     yarn: '>= 1.13.0'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v16.11.1', npm: '8.0.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/schematics-cli@12.2.10',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     node: '^12.14.1 || >=14.0.0',
npm WARN EBADENGINE     npm: '^6.11.0 || ^7.5.6',
npm WARN EBADENGINE     yarn: '>= 1.13.0'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v16.11.1', npm: '8.0.0' }
npm WARN EBADENGINE }

changed 253 packages, and audited 254 packages in 15s

38 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

➜  Codes nest -v
8.1.4

### Minimum reproduction code

N/A

### Expected behavior

Install without issue with NPM V8.
Angular had released version 13, @nestjs/cli should upgrade accordingly and introduce new version.

### Package version

8.1.4

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
This is a duplicate issue. We've already acknowledge that upgrading should fix this and that it just needs to be done. We're determining if this will cause a breaking change or not so we can upgrade accordingly. This **warning** only happens on initialization, and it doesn't change any functionality of the CLI.
