### ISSUE TITLE
Different outdir for one application does not work in nest monorepo

### ISSUE THREAD

**Issue by SunilManthenaG01** [nestjs/nest-cli#1412]
### Current behavior

I want to have a custom outdir of one of the applications in monorepo. 
The current behavior is it created the dist at both application level and root level as well.

Ideally, it should only create the dist at the application level based on the tsconfig app json.

### Minimum reproduction code

https://github.com/SunilManthenaG01/nest-monorepo-dist

### Steps to reproduce

1. npm i
2. nest start my-app

### Expected behavior

the dist folder should be created based on the tsconfig.app.json file and it should be in root.

### Package version

8.1.1

### NestJS version

8.1.1

### Node.js version

14.16.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Monorepo mode enforces certain things including directories structure. If you want to keep using it, you must align to the recommended configuration. Otherwise, things may break unexpectedly.
