### ISSUE TITLE
`generate --help` ignores custom collections

### ISSUE THREAD

**Issue by micalevisk** [nestjs/nest-cli#1433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

`nest generate --help` always outputs this:

![image](https://user-images.githubusercontent.com/13461315/144144110-3a919d63-51e9-4928-9e57-dcdf5a7da6cc.png)

(a list of available schematics) even when the schematics from `@nestjs/schematics` aren't available. For instance, using a custom collection

```
$  cat nest-cli.json 
{
  "collection": "../my-collection-that-doesnt-extends-nestjs-schematics",
  "sourceRoot": "src"
}
```

then we can't run, for instance, `nest generate application`

![image](https://user-images.githubusercontent.com/13461315/144144330-d045b36d-d943-412b-9d57-7e484b08feab.png)

---

basically this is due to the following:

https://github.com/nestjs/nest-cli/blob/35df7f8ad339a07364ae6ac0ef720ff90a16c383/commands/generate.command.ts#L77-L83

https://github.com/nestjs/nest-cli/blob/35df7f8ad339a07364ae6ac0ef720ff90a16c383/commands/generate.command.ts#L100

https://github.com/nestjs/nest-cli/blob/35df7f8ad339a07364ae6ac0ef720ff90a16c383/lib/schematics/nest.collection.ts#L124-L128

which doesn't take in count the `collection` option from `nest-cli.json` config file

### Expected behavior

`nest generate --help` should list the schematics available in the loaded collection

But I see three problems here:

- can we fetch all schematics available of a collection programmatically?
- the config file must be parsed every time someone uses `--help`, to retrieve the collection name. Which I think will degraded DX (without thinking of caching things around)
- I don't think we can load the value of `--collection` option on `GenerateCommand#buildDescription` method

So, looks like listing the right set of schematics is not possible.

Then what we could do is indicate that the table lists schematics from the collection `@nestjs/schematics`, not just "Available schematics". This should avoid misusages of NestJS's CLI. Maybe _"Schematics available on @nestjs/schematics collection"_ will be enough?

### Package version

8.1.5

### NestJS version

8.2.3

**Comment by kamilmysliwiec** [comment]
> Then what we could do is indicate that the table lists schematics from the collection @nestjs/schematics, not just "Available schematics". This should avoid misusages of NestJS's CLI. Maybe "Schematics available on @nestjs/schematics collection" will be enough?

Sounds good! Would you like to create a PR for this issue?
