### ISSUE TITLE
Remove colors from dependency.

### ISSUE THREAD

**Issue by emfomy** [nestjs/nest-cli#1486]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The author of `colors` (imported from `@nestjs/cli/cli-table3/colors`) is destroying the package (https://snyk.io/blog/open-source-npm-packages-colors-faker/)

It will be nice to remove `colors` from the dependency tree to avoid vulnerability.

### Describe the solution you'd like

Remove `colors` from the dependency tree.

### What is the motivation / use case for changing the behavior?

Remove `colors` from the dependency tree to avoid vulnerability.

**Comment by jmcdo29** [comment]
You'll notice nest doesn't have a direct dependency in colors, it's cli-table3 that died. They've already patched their package by pinning an old dependency and are in the talks of removing it altogether in favor of chalk. There's nothing for us to do at the moment, unless we were to rewrite cli-table3 ourselves or replace that dependency.
