### ISSUE TITLE
shutdown hooks stuck waiting for dispose call

### ISSUE THREAD

**Issue by ssilve1989** [nestjs/nest-cli#1487]
## Bug Report
When the process receives a SIGINT, the application gets stuck waiting for the `httpAdapter.close()` in the `dispose()` call in the shutdown lifecycles. It never reaches the shutdown hooks.

## Current behavior

When enabling shutdown hooks and having an http server receiving requests from a polling source, like Prometheus, this behavior can be seen when sending a SIGINT into the process. The terminal prompt may be returned, but the process is still alive and providing output to the current terminal context.

## Input Code

https://github.com/ssilve1989/nest-sigint-no-exit

## Expected behavior

The http server should exit properly. I am not sure if this is a bug in Nest or Express, but it only seems to happen when the process is in the midst of receiving requests.

## Environment

<pre><code>
Nest version: 8.0.8 and 7.16.18

 
For Tooling issues:
- Node version: 14.17.3 
- Platform:  Mac and Linux

Others:

</code></pre>

**Comment by ssilve1989** [comment]
@micalevisk I don't use `nest start` in my current project, we are using the Bazel build system. So I don't think its specifically related to the Nest CLI tool.

**Comment by micalevisk** [comment]
@ssilve1989 so, to run the project, you're using `node` directly? I didn't understand why it worked with `node dist/main.js` but didn't with `nest start` tbh

**Comment by ssilve1989** [comment]
@micalevisk 
>  so, to run the project, you're using node directly? 

that's right

> I didn't understand why it worked with node dist/main.js but didn't with nest start tbh

i'll try to find some time to try it that way as well with the reproduction repo I provided

**Comment by tolgap** [comment]
FYI, this should've been fixed with the introduction of the `forceCloseConnections` option: https://github.com/nestjs/nest/pull/10345

If you create your app using
```ts
const app = NestFactory.create({ forceCloseConnections: true });
app.enableShutdownHooks();
```
Nest will keep track of `Connection: Keep-Alive` HTTP requests and dispose them correctly.
