### ISSUE TITLE
Fresh install of NestJS global CLI and scaffolding a new yarn project fails

### ISSUE THREAD

**Issue by lirantal** [nestjs/nest-cli#1499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The global nest CLI is installed without an issue, using:
```
yarn global add @nestjs/cli
```

Then scaffolding a project using the following command:
```
nest new demo123
```

displays the files to be created in that `demo123/` folder, I then continued to choose `yarn` as the package manager, and after some time it failed with the following:

```
? Which package manager would you ❤️  to use? yarn
▹▹▹▹▸ Installation in progress... ☕
Failed to execute command: yarn install --silent
✖ Installation in progress... ☕
🙀  Packages installation failed, see above

                          Thanks for installing Nest 🙏
                 Please consider donating to our open collective
                        to help us maintain this package.


               🍷  Donate: https://opencollective.com/nest
```

### Minimum reproduction code

n/a

### Steps to reproduce

1. `yarn global add @nestjs/cli`
2. `nest new demo123`

### Expected behavior

Project is scaffolded successfully and all dependencies installed properly.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.2.0

### Packages versions

I ran `nest info` and getting the following:

```
 _   _             _      ___  _____  _____  _     _____
| \ | |           | |    |_  |/  ___|/  __ \| |   |_   _|
|  \| |  ___  ___ | |_     | |\ `--. | /  \/| |     | |
| . ` | / _ \/ __|| __|    | | `--. \| |    | |     | |
| |\  ||  __/\__ \| |_ /\__/ //\__/ /| \__/\| |_____| |_
\_| \_/ \___||___/ \__|\____/ \____/  \____/\_____/\___/


[System Information]
OS Version     : macOS Catalina
NodeJS Version : v14.15.1
NPM Version    : 8.1.1

[Nest CLI]
Nest CLI Version : 8.2.0

[Nest Platform Information]
😼  cannot read your project package.json file, are you inside your project directory?
```

However I am running it in the folder which has a `package.json` file in it

### Node.js version

14.15.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Perhaps we should update the "Packages installation failed, see above" error message to something more informative, like "Packages installation failed, see above. In case you don't see any errors, consider manually running yarn/npm i to see more details on why the previous command errored out."

**Comment by lirantal** [comment]
@micalevisk thank you for the kind words 🤗

@kamilmysliwiec indeed, although I was left wondering whether the scaffolding CLI does only a yarn install at that point, or did it break while also doing other things? creating dirs, symlinks, updating files, etc. Definitely more verbose logging on such a fatal failure is needed.

Regardless of the above, the current experience for any user trying out NestJS with a Node.js version that isn't compliant with that `@typescript-eslint/eslint-plugin` version requirements of the Node.js runtime is going to run into a really frustrating experience, which I'd say is less than ideal as a first user onboarding session. Perhaps it's possible to update the NestJS CLI/project to more "relaxed" version ranges?

**Comment by kamilmysliwiec** [comment]
>  Perhaps it's possible to update the NestJS CLI/project to more "relaxed" version ranges?

I'd suggest reporting this issue in the ESLint repository. Perhaps they can just make the requirement a bit more relaxed (when it comes to the required Node.js version).

**Comment by lirantal** [comment]
I did. Let's wait and see how that goes.

**Comment by lirantal** [comment]
As Brad points out [here](https://github.com/typescript-eslint/typescript-eslint/issues/4465#issuecomment-1018030920) that specific module is following versioning semantics from the upstream ESLint project.

One thing that we can do with the CLI here is to indeed apply the `--ignore-engines` when the CLI performs the installation behind the scenes. To avoid cases where this is actually running for Node.js versions that are entirely out of scope like say Node.js versions lower than v12, we can detect that before everything even starts. WDYT?

**Comment by kamilmysliwiec** [comment]
There are currently no plans to ignore internal packages engine requirements.

I'll keep this open so we won't forget about updating the error message.
