### ISSUE TITLE
Unable to do nest update

### ISSUE THREAD

**Issue by philosofonusus** [nestjs/nest-cli#1514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Failed to execute command: npm update @nestjs/common @nestjs/config @nestjs/core @nestjs/jwt @nestjs/mongoose @nestjs/passport @nestjs/platform-fastify @nestjs/serve-static
node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "undefined".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

### Minimum reproduction code

{   "name": "tentai",   "version": "0.0.1",   "description": "",   "author": "TENTACLE",   "private": true,   "license": "UNLICENSED",   "scripts": {     "prebuild": "rimraf dist",     "build": "nest build",     "build:client": "npm run build --prefix client",     "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",     "start": "nest start",     "start:dev": "nest start --watch",     "start:debug": "nest start --debug --watch",     "start:prod": "node dist/main",     "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",     "test": "jest",     "test:watch": "jest --watch",     "test:cov": "jest --coverage",     "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",     "test:e2e": "jest --config ./test/jest-e2e.json"   },   "dependencies": {     "@nestjs/common": "^7.6.18",     "@nestjs/config": "^0.6.3",     "@nestjs/core": "^7.6.18",     "@nestjs/jwt": "^7.2.0",     "@nestjs/mongoose": "^7.2.4",     "@nestjs/passport": "^7.1.6",     "@nestjs/platform-fastify": "^7.6.18",     "@nestjs/serve-static": "^2.2.2",     "@types/bcrypt": "^3.0.0",     "bcrypt": "^5.0.1",     "cache-manager": "^3.6.0",     "cache-manager-redis-store": "^2.0.0",     "class-transformer": "^0.4.0",     "class-validator": "^0.13.1",     "fastify-compress": "^3.6.1",     "fastify-csrf": "^3.1.0",     "fastify-helmet": "^5.3.1",     "fastify-https-redirect": "^1.0.3",     "fastify-multipart": "^4.0.3",     "fastify-static": "^4.5.0",     "mongoose": "^5.13.13",     "node-fetch": "^2.6.6",     "passport": "^0.4.1",     "passport-jwt": "^4.0.0",     "passport-local": "^1.0.0",     "reflect-metadata": "^0.1.13",     "rimraf": "^3.0.2",     "rxjs": "^6.6.6",     "spdy": "^4.0.2",     "tinify": "^1.6.0-beta.2",     "xmlbuilder": "^15.1.1"   },   "devDependencies": {     "@nestjs/cli": "^7.5.6",     "@nestjs/schematics": "^7.2.7",     "@nestjs/testing": "^7.6.13",     "@types/cache-manager": "^3.4.0",     "@types/express": "^4.17.11",     "@types/jest": "^26.0.20",     "@types/node": "^14.14.31",     "@types/passport-jwt": "^3.0.5",     "@types/supertest": "^2.0.10",     "@typescript-eslint/eslint-plugin": "^4.15.2",     "@typescript-eslint/parser": "^4.15.2",     "eslint": "^7.20.0",     "eslint-config-prettier": "^8.1.0",     "eslint-plugin-prettier": "^3.3.1",     "jest": "^26.6.3",     "prettier": "^2.2.1",     "supertest": "^6.1.3",     "ts-jest": "^26.5.2",     "ts-loader": "^8.0.17",     "ts-node": "^9.1.1",     "tsconfig-paths": "^3.9.0",     "typescript": "^4.1.5"   },   "jest": {     "moduleFileExtensions": [       "js",       "json",       "ts"     ],     "rootDir": "src",     "testRegex": ".*\\.spec\\.ts$",     "transform": {       "^.+\\.(t|j)s$": "ts-jest"     },     "collectCoverageFrom": [       "**/*.(t|j)s"     ],     "coverageDirectory": "../coverage",     "testEnvironment": "node"   } }

### Steps to reproduce

nest u
```
Failed to execute command: npm update @nestjs/common @nestjs/config @nestjs/core @nestjs/jwt @nestjs/mongoose @nestjs/passport @nestjs/platform-fastify @nestjs/serve-static
node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "undefined".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

### Expected behavior

Completed installation

### Package version

7.6.0

### NestJS version

7.6.18

### Node.js version

v15.14.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
can you run

```
npm update @nestjs/common @nestjs/config @nestjs/core @nestjs/jwt @nestjs/mongoose @nestjs/passport @nestjs/platform-fastify @nestjs/serve-static
```

manually?

**Comment by philosofonusus** [comment]
npm update @nestjs/common @nestjs/config @nestjs/core @nestjs/jwt @nestjs/mongoose @nestjs/passport @nestjs/platform-fastify @nestjs/serve-static
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @nestjs/serve-static@2.2.2
npm ERR! Found: @nestjs/common@7.6.18
npm ERR! node_modules/@nestjs/common
npm ERR!   @nestjs/common@"^7.6.18" from the root project
npm ERR!   peer @nestjs/common@"^6.10.0 || ^7.0.0" from @nestjs/config@0.6.3
npm ERR!   node_modules/@nestjs/config
npm ERR!     @nestjs/config@"^0.6.3" from the root project
npm ERR!   8 more (@nestjs/core, @nestjs/jwt, @nestjs/mongoose, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @nestjs/common@"^6.0.0 || ^7.0.0 || ^8.0.0" from @nestjs/serve-static@2.2.2
npm ERR! node_modules/@nestjs/serve-static
npm ERR!   @nestjs/serve-static@"^2.2.2" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @nestjs/common@8.2.6
npm ERR! node_modules/@nestjs/common
npm ERR!   peer @nestjs/common@"^6.0.0 || ^7.0.0 || ^8.0.0" from @nestjs/serve-static@2.2.2
npm ERR!   node_modules/@nestjs/serve-static
npm ERR!     @nestjs/serve-static@"^2.2.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/tentacle/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tentacle/.npm/_logs/2022-01-31T15_24_41_433Z-debug.log
```

> can you run
> 
> ```
> npm update @nestjs/common @nestjs/config @nestjs/core @nestjs/jwt @nestjs/mongoose @nestjs/passport @nestjs/platform-fastify @nestjs/serve-static
> ```
> 
> manually?

**Comment by philosofonusus** [comment]
that is what happens

**Comment by micalevisk** [comment]
oh, right. This happens due to version mismatch.

looks like `nest update` try to fetch the latest version of `@nestjs/*`

If you do have a good reason to stay with nestjs v7, try this:

```
npm update @nestjs/common@7 @nestjs/config @nestjs/core@7 @nestjs/jwt @nestjs/mongoose @nestjs/passport @nestjs/platform-fastify@7 @nestjs/serve-static
```

btw avoid using `nest update`. You could use https://www.npmjs.com/package/npm-check-updates instead.

**Comment by philosofonusus** [comment]
> oh, right. This happens due to version mismatch.
> 
> looks like `nest update` try to fetch the latest version of `@nestjs/*`
> 
> If you do have a good reason to stay with nestjs v7, try this:
> 
> ```
> npm update @nestjs/common@7 @nestjs/config @nestjs/core@7 @nestjs/jwt @nestjs/mongoose @nestjs/passport @nestjs/platform-fastify@7 @nestjs/serve-static
> ```
> 
> btw avoid using `nest update`. You could use https://www.npmjs.com/package/npm-check-updates instead.

I want to try newest version of nestjs due to performance tweaks

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
