### ISSUE TITLE
nest build folder

### ISSUE THREAD

**Issue by Karman40** [nestjs/nest-cli#1515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Why does the same code drop the web application into / dist / src once and / or another time?

I can’t figure out what’s causing this and it works differently for each project.

For me, the latter solution would be better. I use the latest version of everything.

### Minimum reproduction code

https://github.com

### Expected behavior

It would be nice if you didn't generate it back in a folder, because it's hard to write automation to it.

### Package version

8.2.0

### NestJS version

8.2.6

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
This is standard Typescript behavior. Typescript tries to make the `dist` (or whatever output directory you have) mirror the current setup of the included typescript files that are found during compilation. If you end up with `dist/src` that usually means you are including a `ts` file, or importing a file that lives outside the `src` directory.
