### ISSUE TITLE
After Migrating from Standard to Monorepo, Bull Processors Do not exist in the Dist/app/XXX/

### ISSUE THREAD

**Issue by Mellywins** [nestjs/nest-cli#1517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm migrating from a Standard app to a monorepo. Starting to chip at my old app and turning it into microservice. But before starting any of that, my old app which should be running as a small app within the monorepo right now, is having issues with `nest start`.
It builds with no errors, but when running, Bull's Queue processors are not being compiled to the dist/apps/
This is the following exception:
``` 
[Nest] 14241  - 02/04/2022, 2:52:42 PM   ERROR [ExceptionHandler] File /home/oussema/Workplace/bull-monorepo-test/dist/apps/bull-monorepo-test/processor/test.processor.js does not exist
```

### Minimum reproduction code

https://github.com/Mellywins/NestJS-monorepo-bull

### Steps to reproduce

1. the standard repo shows that the package works, you can test it with
* `npm i`
* `npm run start`
2. Checkout to monorepo and redo the same

### Expected behavior

Processor.ts should be compiled to js and exist within the dist folder to work properly

### Package version

8.2

### NestJS version

8.0.0

### Node.js version

14.18.3

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
