### ISSUE TITLE
Add --flat generation option to nest-cli.json

### ISSUE THREAD

**Issue by SmallhillCZ** [nestjs/nest-cli#1518]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I have to put `--flat`  to all of my generate commands when I am using flat structure.

### Describe the solution you'd like

I would like to have `flat` key in `generateOptions` in `nest-cli.json` the same way `spec` works.

### What is the motivation / use case for changing the behavior?

I am lazy to put `--flat`  to all of my generate commands.

**Comment by micalevisk** [comment]
would you like to make a PR for this?
