### ISSUE TITLE
nest start --watch not reloading after changes (nest start --watch not working)

### ISSUE THREAD

**Issue by Alex44lel** [nestjs/nest-cli#1533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have a nest.js installation. When I run "npm run start:dev" (which runs start --watch) everything works fine and the green logs appear.

![GNq3Y](https://user-images.githubusercontent.com/66825022/154343971-681b4f1c-c6cc-4c6a-9d73-8bfaf19ef4d7.png)

The thing is that when I update something in the code, nest does not update anymore and it gets stuck in the following image:

![UHdcC](https://user-images.githubusercontent.com/66825022/154344009-b4736145-58fc-4cae-8d61-bd28bc102443.png)

I am sure this is not an issue with my code as I am having the same problem in all my nest.js repositories. I had also deleted node_modules and reinstalled them and it did not work.

I have also tried to reinstall the nest CLI globally. I am also sharing the same repository with another developer and he does not have this issue

My node version is 16.14.0 and npm 8.3.1

```
{
  "name": "unigow-backend",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "env-cmd -f .env.production rimraf dist",
    "build": "env-cmd -f .env.production nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "env-cmd -f .env.development nest start --watch",
    "start:debug": "env-cmd -f .env.development nest start --debug --watch",
    "start:prod": "env-cmd -f .env.production node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^8.3.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/mapped-types": "^1.0.1",
    "@nestjs/mongoose": "^8.0.1",
    "@nestjs/platform-express": "^8.0.0",
    "@types/dotenv": "^8.2.0",
    "@types/luxon": "^2.0.9",
    "@types/mongoose": "^5.11.97",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "dateformat": "^5.0.1",
    "dotenv": "^10.0.0",
    "env-cmd": "^10.1.0",
    "luxon": "^1.28.0",
    "moment": "^2.29.1",
    "moment-range": "^4.0.2",
    "mongoose": "^5.13.9",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rrule": "^2.6.8",
    "rxjs": "^7.2.0",
    "sib-api-v3-sdk": "^8.2.1",
    "stripe": "^8.183.0",
    "twilio": "^3.69.0",
    "uuid": "^8.3.2"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "^26.0.24",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^4.28.2",
    "@typescript-eslint/parser": "^4.28.2",
    "eslint": "^7.30.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^3.4.0",
    "jest": "27.0.6",
    "prettier": "^2.3.2",
    "supertest": "^6.1.3",
    "ts-jest": "^27.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "^3.10.1",
    "typescript": "^4.3.5"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}
```

Here is my ts config:

```
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true
  }
}
```
Here is my tsconfig.build:
```
{
  "extends": "./tsconfig.json",
  "exclude": ["node_modules", "test", "dist", "**/*spec.ts"]
}
```

Thank you very much for the help
I have been stuck here for many days :(

### Minimum reproduction code

https://github.com/Alex44lel/nestTest

### Expected behavior

I expect that npm run start:dev reloads when i make changes on my code

### Package version

^8.0.0

### NestJS version

8.3.1

### Node.js version

16.14.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

Everything was working fine. Honestly, I have no idea what i did in order to break the cli

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.

If you believe this truly is a bug then please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

**Comment by Alex44lel** [comment]
Hi,

Thanks for the quick response, I will go into Discord.

The bug is happening in all my nest.js projects. ¿Do you want me to share a test repository (basically the one you obtain after running "nest new project-name")?

**Comment by jmcdo29** [comment]
That would be the idea. Something that we're able to verify reproduces the issue

**Comment by Alex44lel** [comment]
I have upload the repository. I do not know if it will help much as it is just the boiler repository

**Comment by micalevisk** [comment]
yep. Didn't manage to reproduce this in my Linux + Vim editor.

**Comment by Alex44lel** [comment]
Thanks for trying. So far the only new thing I have find out is that the error may be related to typescript as when I run tsx -watch it gets stuck in the same point

**Comment by Alex44lel** [comment]
Also, when installing the nest cli i am getting this warnings

![image](https://user-images.githubusercontent.com/66825022/154425944-2729ce68-0d89-4612-b5ab-8eee17d5d5aa.png)

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
