### ISSUE TITLE
Live Reload not working with Nestjs Workspaces in Docker

### ISSUE THREAD

**Issue by all2pie** [nestjs/nest-cli#1535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using Nestjs workspaces the Live reload do not work in docker

### Minimum reproduction code

(https://github.com/all2pie/nestjs-workspaces-live-reload-issue/tree/bad

### Steps to reproduce

Master branch works fine 
Bad branch has the issue

Use this command to test: 

`docker-compose -f test.yml up --build`

### Expected behavior

The server should reload whenever the code changes

### Package version

8.2.1

### NestJS version

^8.0.0

### Node.js version

16.13.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by all2pie** [comment]
If this isn't the issue of the cli then please support here: 

[Stackoverflow Issue](https://stackoverflow.com/questions/70446187/nestjs-live-reload-not-working-with-docker?noredirect=1#comment124527759_70446187)

I have also asked on discord but got no response.

**Comment by jmcdo29** [comment]
Your "bad" branch is auto-reloading as expected. Am I missing something?

**Comment by jmcdo29** [comment]
I don't have a windows machine for development. Running on Linux. Does the auto-compile and restart work without docker? Trying to figure out where the issue may be here

**Comment by jmcdo29** [comment]
Seems like a problem with docker-compose ,not with Nest's CLI.

**Comment by all2pie** [comment]
Also tried with simple docker, getting the same issue.

Pushed the docker commands in the bad branch README

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
