### ISSUE TITLE
Missing parts of `name` when creating new project `a.b.c.d`

### ISSUE THREAD

**Issue by DevDengChao** [nestjs/nest-cli#1540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The `name` field in `package.json` is missing `.d` if you create a new project named `a.b.c.d`.

### Minimum reproduction code

None, as it dosen't require a NestJS instance to reproduce.

### Steps to reproduce

1. open a new terminal with cmd.exe
2. type `nest new a.b.c.d`
3. select a package manager, eg: `yarn`
4. open `a.b.c.d/package.json` with any editor
5. you'll find that the `name` field is set to `a.b.c`

### Expected behavior

You should see `a.b.c.d` instead of `a.b.c` in step 5 above.

### Package version

8.2.1

### NestJS version

8.3.1

### Node.js version

16.13.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

![reproduce](https://user-images.githubusercontent.com/16363180/155158777-951149e2-5cf5-4ac9-b57a-4ec03c2236e5.gif)

**Comment by micalevisk** [comment]
that's a bug on this `resolvePackageName`:

https://github.com/nestjs/schematics/blob/7ebccbbe169aa0c1c259b096cd11f4c4578ef578/src/lib/application/application.factory.ts#L54-L60

Should be easy to fix. Can you open a PR at https://github.com/nestjs/schematics? (would be even better if you write tests for it)

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/schematics/pull/956
