### ISSUE TITLE
Provide CLI command for renaming the library

### ISSUE THREAD

**Issue by ph55** [nestjs/nest-cli#1543]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

After renaming library - manual search and replace required.
Need to go through `tsconfig.json`, `package.json`, `nest-cli.json`, `tsconfig.lib.json` files and replace old name for new.
Also all applications should be searched for library import and replaced with new one.

### Describe the solution you'd like

CLI command for renaming the library would be nice.
Command should rename all library references including the imports.

### What is the motivation / use case for changing the behavior?

Renaming library should be easy task and should require as less manual work as possible.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
