### ISSUE TITLE
Path for nested library is incorrect

### ISSUE THREAD

**Issue by ph55** [nestjs/nest-cli#1544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When creating library inside existing folder for code organization - folders would have unexpected structure.

### Minimum reproduction code

https://github.com/nestjs/nest-cli

### Steps to reproduce

```
❯ nest g lib chat-channels/whatsapp
? What prefix would you like to use for the library (default: @app)? 
CREATE libs/chat-channels/whatsapp/tsconfig.lib.json (236 bytes)
CREATE libs/chat-channels/whatsapp/src/index.ts (99 bytes)
CREATE libs/chat-channels/whatsapp/src/chat-channels/whatsapp.module.ts (268 bytes)
CREATE libs/chat-channels/whatsapp/src/chat-channels/whatsapp.service.spec.ts (566 bytes)
CREATE libs/chat-channels/whatsapp/src/chat-channels/whatsapp.service.ts (105 bytes)
UPDATE nest-cli.json (2848 bytes)
UPDATE package.json (2486 bytes)
UPDATE tsconfig.json (1132 bytes)
```

Notice how `chat-channels` folder is duplicated.

### Expected behavior

```
❯ nest g lib chat-channels/whatsapp
? What prefix would you like to use for the library (default: @app)? 
CREATE libs/chat-channels/whatsapp/tsconfig.lib.json (236 bytes)
CREATE libs/chat-channels/whatsapp/src/index.ts (99 bytes)
CREATE libs/chat-channels/whatsapp/src/whatsapp.module.ts (268 bytes)
CREATE libs/chat-channels/whatsapp/src/whatsapp.service.spec.ts (566 bytes)
CREATE libs/chat-channels/whatsapp/src/whatsapp.service.ts (105 bytes)
UPDATE nest-cli.json (2848 bytes)
UPDATE package.json (2486 bytes)
UPDATE tsconfig.json (1132 bytes)
```

### Package version

8.2.1

### NestJS version

8.3.1

### Node.js version

16.14.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

BTW. Why "Minimum reproduction code" field is required for CLI project when opening the bug.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by stanimirovv** [comment]
@kamilmysliwiec if the issue is up for grabs I am interested in giving it a go.

**Comment by kamilmysliwiec** [comment]
@stanimirovv contributions are more than welcome!

**Comment by stanimirovv** [comment]
I am wrapping up https://github.com/nestjs/schematics/pull/967 Then I will start looking deeper into this.

**Comment by stanimirovv** [comment]
@kamilmysliwiec  @micalevisk 

I did a bit of digging :
``` 
nest g lib chat-channels/whatsapp
```

Parses to the following schematicOptions:
```
[
  SchematicOption { name: 'name', value: 'a12/b' },
  SchematicOption { name: 'dry-run', value: true },
  SchematicOption { name: 'language', value: 'ts' },
  SchematicOption { name: 'sourceRoot', value: 'src' },
  SchematicOption { name: 'spec', value: true }
]
```

both for lib and controller name is passed, path is not -> most likely we should add some logic to the **library schematic**
Maybe adjusting this function makes sense: https://github.com/nestjs/schematics/blob/master/src/lib/library/library.factory.ts#L59

We can add logic to the GenerateAction if only name was passed to figure out if it is a single file or path, but:
* This issue has been noticed only for libraries and isn't present for other schematics -> most likely it is intended to be handled on the schematics side ? 
* Changing a singel schematic will have less side effects /risk

Does it make sense to make the fix in the schematic ?

**Comment by kamilmysliwiec** [comment]
Just wanted to add my 2 cents to this issue: technically, libraries in NestJS monorepo mode are designed to follow a "flat structure" meaning, they shouldn't be nested. That means, passing `chat-channels/whatsapp` as the name parameter is just a wrong usage of the schematic. As for passing paths, we shouldn't allow doing so as it may lead to unexpected side effects.
