### ISSUE TITLE
TypeError: Cannot read property 'paths' of undefined

### ISSUE THREAD

**Issue by billwing** [nestjs/nest-cli#1571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I save the tsconfig.json and thrown error:
![image](https://user-images.githubusercontent.com/3411815/158573709-c2d0a9ae-459a-4900-81c1-e3fd93376048.png)

### Minimum reproduction code

https://github.com/zhangyuang/ssr/tree/dev/example/nestjs-vue3-ssr

### Expected behavior

Without error.

### Package version

8.4.1

### NestJS version

8.4.1

### Node.js version

14.18.3

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by billwing** [comment]
> @billwing can you actually tell me what type of changes you are making to the TS config file ?
> 
> After spending some time playing arround with it I found that adding new lines (for some reason) breaks it, but changing values of existing options or adding inline comments does not.
> 
> What edits are you doing when it breaks ? I wonder if it is just the new lines or there is something else.
> 
> Context: When the error exists when this is called: https://github.com/nestjs/nest-cli/blob/master/lib/compiler/watch-compiler.ts#L68 The value of the options is undefined which causes the code to break here:
> 
> https://github.com/nestjs/nest-cli/blob/cdb6c247ae27a9bd79289724f2d2681621d4f1bc/lib/compiler/hooks/tsconfig-paths.hook.ts#L11
> 
> I added some code on an experimental branch to try and fix this:
> 
> ```
> if(options === undefined) {
>         const tsLoader = new TypeScriptBinaryLoader();
>         const tsConfigProvider = new TsConfigProvider(tsLoader);
>         const temp= tsConfigProvider.getByConfigFilename(configFilename);
>       options = temp.options;
>     }
>       const tsconfigPathsPlugin = tsconfigPathsBeforeHookFactory(options);
> ```
> 
> Although the function call doesn't fail the typescript compiler fails further down the line, the point being the fix should most likely be in another place.

I reproduce the issue without changes with TS config file and save.
The author of `ssr` had pull requests: https://github.com/nestjs/nest-cli/pull/1572.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest-cli/pull/1572
