### ISSUE TITLE
CLI command "nest new <name>" fails with schema validation error

### ISSUE THREAD

**Issue by russaa** [nestjs/nest-cli#1573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Creating a new `nest` project fails with schema validation error.

This error seems similar to #1448 except that there should not be any possible clash between the CLI's dependency versions and the project's dependency versions (for schemas etc), since the project is about to be created by the CLI.

I checked the versions for `@nestjs/cli` and this error does not occur for version `v8.1.4`, but starting with version `v8.1.5` up to version `v8.2.3` the schema validation error occurs
```
>nest new my-new-project
?  We will scaffold your app in a few seconds..

Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID
    at Object.code (C:\Users\___\App\nvm\v12.16.3\node_modules\@nestjs\cli\node_modules\ajv\dist\vocabularies\core\id.js:6:15)
    at keywordCode (C:\Users\___\App\nvm\v12.16.3\node_modules\@nestjs\cli\node_modules\ajv\dist\compile\validate\index.js:454:13)
    at C:\Users\___\App\nvm\v12.16.3\node_modules\@nestjs\cli\node_modules\ajv\dist\compile\validate\index.js:222:17
    at CodeGen.code (C:\Users\___\App\nvm\v12.16.3\node_modules\@nestjs\cli\node_modules\ajv\dist\compile\codegen\index.js:439:13)
    at CodeGen.block (C:\Users\___\App\nvm\v12.16.3\node_modules\@nestjs\cli\node_modules\ajv\dist\compile\codegen\index.js:568:18)
    at iterateKeywords (C:\Users\___\App\nvm\v12.16.3\node_modules\@nestjs\cli\node_modules\ajv\dist\compile\validate\index.js:219:9)
    at groupKeywords (C:\Users\___\App\nvm\v12.16.3\node_modules\@nestjs\cli\node_modules\ajv\dist\compile\validate\index.js:208:13)
    at C:\Users\___\App\nvm\v12.16.3\node_modules\@nestjs\cli\node_modules\ajv\dist\compile\validate\index.js:192:13
    at CodeGen.code (C:\Users\___\App\nvm\v12.16.3\node_modules\@nestjs\cli\node_modules\ajv\dist\compile\codegen\index.js:439:13)
    at CodeGen.block (C:\Users\___\App\nvm\v12.16.3\node_modules\@nestjs\cli\node_modules\ajv\dist\compile\codegen\index.js:568:18)

Failed to execute command: node @nestjs/schematics:application --name=my-new-project --directory=undefined --no-dry-run --no-skip-git --no-strict --package-manager=undefined --language="ts" --collection="@nestjs/schematics"
```

### Minimum reproduction code

N/A

### Steps to reproduce

1. install @nestjs/cli@8.1.5 (or higher)  
    ```
    npm -g i @nestjs/cli@8.1.5 
    ```
2. create new nest project
    ```
    nest new my-new-project
    ```

### Expected behavior

the command `nest new my-new-project` should create a new `nest` project at `./my-new-project`

### Package version

8.1.5

### NestJS version

N/A

### Node.js version

12.16.3

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
I can't seem to replicate this in docker, node 12.22.9

<details>

<summary>Docker run of nest new</summary>

```sh
❯ docker run -it node:12 sh
# node -v
v12.22.9
# npm i -g @nestjs/cli
/usr/local/bin/nest -> /usr/local/lib/node_modules/@nestjs/cli/bin/nest.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/@nestjs/cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ @nestjs/cli@8.2.3
added 250 packages from 244 contributors in 19.755s
# nest new node-12-test -p npm
⚡  We will scaffold your app in a few seconds..

CREATE node-12-test/.eslintrc.js (631 bytes)
CREATE node-12-test/.prettierrc (51 bytes)
CREATE node-12-test/README.md (3339 bytes)
CREATE node-12-test/nest-cli.json (64 bytes)
CREATE node-12-test/package.json (2001 bytes)
CREATE node-12-test/tsconfig.build.json (97 bytes)
CREATE node-12-test/tsconfig.json (546 bytes)
CREATE node-12-test/src/app.controller.spec.ts (617 bytes)
CREATE node-12-test/src/app.controller.ts (274 bytes)
CREATE node-12-test/src/app.module.ts (249 bytes)
CREATE node-12-test/src/app.service.ts (142 bytes)
CREATE node-12-test/src/main.ts (208 bytes)
CREATE node-12-test/test/app.e2e-spec.ts (630 bytes)
CREATE node-12-test/test/jest-e2e.json (183 bytes)

✔ Installation in progress... ☕

🚀  Successfully created project node-12-test
👉  Get started with the following commands:

$ cd node-12-test
$ npm run start


                          Thanks for installing Nest 🙏
                 Please consider donating to our open collective
                        to help us maintain this package.


               🍷  Donate: https://opencollective.com/nest

```

</details>

I wonder if this is windows specific

**Comment by stanimirovv** [comment]
I also can't replicate this on Linux, node 14. 

Cloud you please try to install nest and nest-cli locally in a project, without the -g flag ?

**Comment by russaa** [comment]
... locally works:  
created a new  project/package.json & installing `@nestjs/cli@8.2.3` and `@nestjs/core@8.4.1`

and then using the locally installed nest CLI creates the project without problems, i.e. running
```
node_modules\.bin\nest new my-new-project
```

**Comment by russaa** [comment]
... I think the "cause" for the problem with `npm install -g ...`  may be the missing `core` package:

after globally installing `@nestjs/cli` **and** `@nestjs/core`, the command `nest new <name>` does work as expected, on Windows too

So the "problem" may only be the documentation, e.g.  
[[@nestjs/cli](https://docs.nestjs.com/first-steps)](https://docs.nestjs.com/first-steps#setup)  
only mentions that `@nestjs/cli` needs to be installed (i.e. no mentioning of `@nestjs/core`)

**Comment by micalevisk** [comment]
there's no reason for `@nestjs/cli` depends on `@nestjs/core`

**Comment by micalevisk** [comment]
@russaa please try this:

1. `npm uninstall -g @nestjs/core @nestjs/cli`
2. `npm i -g @nestjs/cli@latest`
3. `nest new my-project`

**Comment by russaa** [comment]
yes, sorry, I did not check thoroughly enough:

actually, now it just works with only the latest `@nestjs/cli` (v8.2.3) installed!

no idea what did change and why it did not work before
(may one of those "Windows only" wonders that happen now and again)

I guess this ticket can be closed -- sorry for the needless work and many thanks for the lightning fast help

**Comment by micalevisk** [comment]
@russaa you can close this btw :)
