### ISSUE TITLE
Better message differentiation on successfully started cli

### ISSUE THREAD

**Issue by rbalet** [nestjs/nest-cli#1576]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

UI enhancement

### Describe the solution you'd like

Changing the last `Nest application successfully started` message with an other color or an icon at the end.

### Teachability, documentation, adoption, migration strategy

![image](https://user-images.githubusercontent.com/44493964/159139175-a2b459ee-1756-44ed-8ba0-113e4c93c512.png)

This is the way angular does   
![image](https://user-images.githubusercontent.com/44493964/159139207-0ef95f5d-2aae-4472-a844-65b64b9006f6.png)

### What is the motivation / use case for changing the behavior?

Working on multiple screen, if we see another color the eye would be attracted faster and we wouldn't need to read it to understand that our project is ready.

**Comment by micalevisk** [comment]
btw this messages comes from here

https://github.com/nestjs/nest/blob/0dc4f919f153a64863daf2f490b9c0bb80849bb6/packages/core/constants.ts#L3

**Comment by jmcdo29** [comment]
As Micael mentioned this isn't directly related to the CLI, it's actually a line in the `@nestjs/core` package. And you're welcome to add any logs you'd like to after the `await app.listen(3000)` to provide any extra context or visuals if you'd like

**Comment by micalevisk** [comment]
@rbalet you could do something like this:

```ts
import { Logger } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';

async function bootstrap() {
  const logger = new Logger('NestApplication');
  const app = await NestFactory.create(AppModule, { logger });
  await app.listen(process.env.PORT || 3000);
  logger.verbose(`Server running on ${await app.getUrl()}`);
}
bootstrap();
```

![image](https://user-images.githubusercontent.com/13461315/159140153-28d237cd-578e-498c-8c35-4d75cb3a1a25.png)

**Comment by rbalet** [comment]
Thx a lot @micalevisk  & @jmcdo29 .

Si I'm closing the issue for the the cli, sorry.

Don't you think it would make sense to add the line you just added into the core package then?

I can create a pull request while just adding a :zap: at the end of the phrase.

Even if adding on which local host it does serve is even better.

**Comment by jmcdo29** [comment]
[There was a PR in the schematic](https://github.com/nestjs/schematics/pull/287) but we decidedd not to move forward with it

**Comment by rbalet** [comment]
@jmcdo29 okay I see, the logic here.

Could the :zap: be accepted then ?

It doesn't add any lint & doesn't make the main.ts more complex..?

**Comment by jmcdo29** [comment]
I honestly don't see this being added. Would it require an extra library, or just a "strange" character string? What about environments that don't support emojis? 

If you want to add this to your server(s), great, but I don't see this being updated in the main code
