### ISSUE TITLE
Prototype Pollution in minimist | upstream @angular-devkit/schematics-cli v13.3.1

### ISSUE THREAD

**Issue by emfomy** [nestjs/nest-cli#1594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Running `yarn audit` in my project results in

```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Prototype Pollution in minimist                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimist                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.2.6                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @nestjs/cli                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @nestjs/cli > @angular-devkit/schematics-cli > minimist      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1067285                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
1 vulnerabilities found
Severity: 1 High
```

### Minimum reproduction code

see above

### Steps to reproduce

- yarn add @nestjs/cli
- yarn audit (8.2.4)

### Expected behavior

Change dependency of `@angular-devkit/schematics-cli` to `^13.3.1`

`@angular-devkit/schematics-cli` v13.3.1 has bumped `minimist` to v1.2.6. Please update the dependency to this version.

Reference: https://github.com/angular/angular-cli/releases/tag/13.3.1

### Package version

8.2.4

### NestJS version

no

### Node.js version

v16.13.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
duplicate #1583 and #1579

Please do something searching next time.
