### ISSUE TITLE
[FEATURE] - CLI not following the nestjs example architecture

### ISSUE THREAD

**Issue by MonsieurMan** [nestjs/nest-cli#16]
I began a new project using the nestjs/typescript-starter-project and I can't use the CLI. 
I think the default base repo should be changed to the official one. And that the CLI should be updated to follow it's folder structure.    

Is there any reason for it not being that way?

**Comment by ThomRick** [comment]
Hey @MonsieurMan !

The "official" project structure was created after the CLI tool... but this is not a good explanation regarding your issue.
I think the new and generate commands have to follow the official recent project structure like you mentioned in your issue description.

Currently you can use the template of your choice with the new command and no specifications are written to help people to make their own template.

Moreover I think the update command should be able to pull the most recent template and adapt the project structure regarding the project structure specifications.

I'll add these on the project development plan.

**Comment by MonsieurMan** [comment]
@ThomRick Thank you for the answer.  
Regarding the development, I'm currently in a work and study formation that doesn't fit my level, so I basically have two spare days each week where I could contribute. Also, we're beginning adopting nest for a project that could lead to a startup creation and maybe in my company too, so I could get some friends/colleagues involved in the development.

**Comment by ThomRick** [comment]
Feel free to make some pull requests ! 
That is the open source is for ;-)
