### ISSUE TITLE
the latest nestjs/cli depends on a mimimist (v1.2.5) package, which contains a vulnerability of critical severity

### ISSUE THREAD

**Issue by organic-data** [nestjs/nest-cli#1600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The latest nestjs/cli depends on @mimimist (v1.2.5) package, which contains a vulnerability of [critical severity](https://github.com/advisories/GHSA-xvch-5gv4-984h).
The related package is @angular-devkit/schematics-cli (v13.3.0) where a fixed version has been already released.

### Minimum reproduction code

https://github.com/organic-data/typescript-starter

### Steps to reproduce

1. npm i

### Expected behavior

Update the dependencies to a fixed version @angular-devkit/schematics-cli (v13.3.1).

### Package version

8.2.4

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
There's already a PR to fix this: https://github.com/nestjs/nest-cli/pull/1591
