### ISSUE TITLE
New application with collection already containing a .gitignore fails

### ISSUE THREAD

**Issue by maxgaurav** [nestjs/nest-cli#1628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When setting up a new application using a collection that already contains a **.gitignore** file. The git init process would fail.

![image](https://user-images.githubusercontent.com/10531584/165780732-4e60d738-8fb4-4f38-91f6-214503583c59.png)

### Minimum reproduction code

https://gist.github.com/maxgaurav/c6260d956d5fb7d124f565959406e957

### Steps to reproduce

```bash

npm install -g @nestjs/cli
npm install -g @maxgaurav/nestjs-template-schematics

nest new sample-content
```

### Expected behavior

When a .**gitignore** file already exists it should not try to overwrite with default git content. This actions leads to 

### Package version

8.2.5

### Node.js version

v16.14.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

It looks like the action where **.gitignore** is being initialized is not considering the fact a **.gitignore** file can already be there

**Comment by jmcdo29** [comment]
If you're using `nest new` in a directory that already is using `git` you can use the `--skip-git` flag to tell Nest not to worry about the git setup

**Comment by maxgaurav** [comment]
## Findings

The main call to init git passes but when the next which is to create gitignore file fails.

```typescript
    if (!isDryRunEnabled) {
      if (!shouldSkipGit) {
        await initializeGitRepository(projectDirectory); // passes and setups all necessary git init actions
        await createGitIgnoreFile(projectDirectory); // fails as it assumes no .gitignore file would exists
      }

      printCollective();
    }
 ```

Referencing file: https://github.com/nestjs/nest-cli/blob/94b0c037134a59f7bf3fcc1fd2e7b8f14020141f/actions/new.action.ts#L207

The **createGitIgnoreFile**  function does not consider the fact the files copied through schematics may already contain a .gitignore file. I think this is written this way as the default application strucuture in @nestjs/schmatics does not include the .gitignore file. In my collection overide of the schematics I have provided my own gitignore and its causing failure in completion of command.

```typescript
/**
 * Write a file `.gitignore` in the root of the newly created project.
 * `.gitignore` available in `@nestjs/schematics` cannot be published to
 * NPM (needs to be investigated).
 *
 * @param dir Relative path to the project.
 * @param content (optional) Content written in the `.gitignore`.
 *
 * @return Resolves when succeeds, or rejects with any error from `fn.writeFile`.
 */
const createGitIgnoreFile = (dir: string, content?: string) => {
  const fileContent = content || defaultGitIgnore;
  const filePath = join(process.cwd(), dir, '.gitignore');
  return promisify(fs.writeFile)(filePath, fileContent);
};
```

**Comment by maxgaurav** [comment]
Just FYI: I was looking into the implementation it looks like there is some attempt but never completed, as there is an option of passing custom content but the main caller never does such a thing along with the fact there is a possibility that the file may already exist after copying the structure from schematics provided.

Would it be okay that I provide a pull request for this?

**Comment by jmcdo29** [comment]
If it's non-breaking and easy to maintain, I'd say go for it :)

**Comment by maxgaurav** [comment]
Ok. Will do

**Comment by maxgaurav** [comment]
@jmcdo29 
I have linked the issue with the pull request.

**Comment by kamilmysliwiec** [comment]
Tracking this here https://github.com/nestjs/nest-cli/pull/1630
