### ISSUE TITLE
New project places typescript in dependencies not devDependencies?

### ISSUE THREAD

**Issue by dls314** [nestjs/nest-cli#168]
I noticed that nest-cli new project places typescript in dependencies not devDependencies. Is this a subtle requirement or could typescript be moved to devDependencies in (most) cases?

**Comment by dls314** [comment]
Thanks, I'll check that repo.

**Comment by dls314** [comment]
This is slightly OT, but how/how often does nest-cli pick up a new version of nest-typescript-starter? I see some issues fixed in master over there, but it looks like nest-cli is using update/version-5 (based on content, I don't know how it's being done)

**Comment by ThomRick** [comment]
Yeah Nest-CLI new generate a project based on nest-typescript-starter files but it is not cloning that branch repository.
Nest-CLI use the @nestjs/schematics module to generate project and elements.
If you want to apply your modifications you must go to that project and PR. (don't forget to submit an issue first to attach PR and track the project evolution)
After that we have to update @nestjs/schematics dependency in Nest-CLI ;-)
