### ISSUE TITLE
Allow custom suffix when generating unit tests

### ISSUE THREAD

**Issue by garritfra** [nestjs/nest-cli#1683]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

We've settled with `.test.ts` as a unit-test suffix for all of our projects. While Nest is able to interpret these files, it can only produce `.spec.ts` files when generating a resource, which breaks our convention. It would be nice to be able to specify a custom suffix as a cli option.

### Describe the solution you'd like

There should be a cli flag and config option to specify the suffix to be used, with the default being `spec`.

```sh
nest g res foo --spec-suffix=test
```

`nest-cli.json`:
```json
{
	"generateOptions": {
		"spec": true,
		"specSuffix": "test"
	}
}
```

(flag and option naming TBD.)

### What is the motivation / use case for changing the behavior?

Implementing this feature makes it easier to adopt company conventions.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by garritfra** [comment]
@kamilmysliwiec I'll see what I can do.👍

**Comment by kamilmysliwiec** [comment]
Thanks @garritfra, let's track this here https://github.com/nestjs/schematics/pull/1077!

**Comment by hrkeni** [comment]
@kamilmysliwiec Does this need to be reopened? I don't believe the feature has been implemented and didn't make it into the cli as part of https://github.com/nestjs/schematics/pull/1077 

@garritfra Am I seeing that correctly?

**Comment by garritfra** [comment]
@hrkeni yes, that's correct. I don't have the time to work on it anymore, but it should be a simple change.

**Comment by hrkeni** [comment]
I would be happy to work on this.

**Comment by hrkeni** [comment]
@kamilmysliwiec Please reopen this issue and review PRs or let me know if I should open another issue here. Thank you.

**Comment by hrkeni** [comment]
@micalevisk Apologies for the spam. Can you take a look at the comments above and advise?
