### ISSUE TITLE
remove `update` command in nestjs v9

### ISSUE THREAD

**Issue by micalevisk** [nestjs/nest-cli#1696]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

taking this https://github.com/nestjs/nest-cli/issues/1204#issuecomment-887326762

> We might need to remove the `update` command entirely soon as it isn't even close to a real "updating/upgrading" feature. I'd recommend using npx ncu -u instead (for updating deps).

I guess we can do that in v9 :smile: 

### Describe the solution you'd like

either

- drop the command `update` from `@nestjs/cli` and update the migration guide to clarify why,
- or display a deprecating warning message when `nest update` is being used, to finally remove it in v10 

### Teachability, documentation, adoption, migration strategy

it depends on which path above we will follow

### What is the motivation / use case for changing the behavior?

people often complains about `nest update` not working as they expected it should, and I don't think the CLI need that feature because there are other tools for such task

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this?
