### ISSUE TITLE
[FEATURE] - Automatically add missing nestconfig.json

### ISSUE THREAD

**Issue by MonsieurMan** [nestjs/nest-cli#17]
I think that we could simply ask the user if the project's using ts or es, create the config file and go on.

**Comment by ThomRick** [comment]
Hey @MonsieurMan !
You're right ! 
Currently the new command just takes some arguments to create the project.
I'm working on a prompt that will take user inputs about the project configuration before create the project files (like npm init)

**Comment by weeco** [comment]
Has this feature been removed? I get an exception trying to generate a new module in a project which has no nestcli.json

**Comment by ThomRick** [comment]
We are developing a default configuration in case their is no nest config file in the project.
