### ISSUE TITLE
NPM Install is failing with package not found for es-lint@8.4.4

### ISSUE THREAD

**Issue by sicco-moonbeam** [nestjs/nest-cli#1705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Running `npm i -g @nestjs/cli`, I get the following error:

```
npm i -g @nestjs/cli@8.2.7
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types/eslint/-/eslint-8.4.4.tgz - Not found
npm ERR! 404
npm ERR! 404  '@types/eslint@https://registry.npmjs.org/@types/eslint/-/eslint-8.4.4.tgz' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

### Minimum reproduction code

https://github.com/nestjs/nest-cli

### Steps to reproduce

Run the command `npm i -g @nestjs/cli`

### Expected behavior

NestJS/CLI installs globally

### Package version

8.2.8

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Looks like there was an error publishing `@types/eslint`. Follow [this thread](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/61032) for more details

**Comment by Segaja** [comment]
Am I missing something? I'm trying to install `@nestjs/cli` version 8.2.8, which has in its [`package.json`](https://github.com/nestjs/nest-cli/blob/8.2.8/package.json#L86=) version 8.18.0 of eslint as dependency. Why will it then during install try to load eslint 8.4.4 ?

**Comment by jmcdo29** [comment]
It's not that it's trying to install `eslint@8.4.4` it's that somewhere in the dependency tree something is request `@types/eslint@8.4.4` (presumably by `@types/eslint@^8.x.y`) which gets this missing package error.

**Comment by Segaja** [comment]
Hm okay. still sounds add as this seems to be an old version. Why would it vanish from NPM? anyway. i guess we have to wait for eslint to fix this? What a set back... This kind of kills my first dive into nestjs...

**Comment by jmcdo29** [comment]
This issue just came up today, within the last hour or so. It's a major issue that is effecting multiple packages, not just `@nestjs/cli`. Unfortunately, not much to do right now other than wait for `@types/8.4.5`. You could go without the CLI for now, I think we have a docs PR in the works of how to get started without it, but it's really unfortunate timing honestly

**Comment by Segaja** [comment]
I will wait, but thanks ;)

**Comment by jmcdo29** [comment]
This has now been resolved. There was an incident with npm that did not allow for the publishing of new packages. Just tested in a clean docker environment and had no issues.
