### ISSUE TITLE
Node.js v10.13.0 not available to use cli v9

### ISSUE THREAD

**Issue by diyews** [nestjs/nest-cli#1716]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Versions

8 -> 9

### Describe the regression

From the [doc site](https://docs.nestjs.com/first-steps#prerequisites) it said 

> Please make sure that [Node.js](https://nodejs.org/) (>= 10.13.0, except for v13) is installed on your operating system.

@nestjs/core v9 works in v10.13.0, see [link](https://github.com/nestjs/docs.nestjs.com/pull/2252)(v8, I tried v9 also)

With @nestjs/cli v9 I got
![image](https://user-images.githubusercontent.com/35769340/178095713-6c1bcda7-d6a7-4101-9b97-d63254e97847.png)

### Minimum reproduction code

```ts

```

### Expected behavior

Update docs or make it works in v10.13.0, prefer the first one :)

**Comment by micalevisk** [comment]
![image](https://user-images.githubusercontent.com/13461315/178106027-0410780b-e93f-4dba-bc9e-91de9ef9941d.png)

```bash
$ npm view yargs-parser engines.node
>=12
```

So I guess the solution to this would be either indicate that Nest CLI only supports node >= 12 or downgrade all the dependencies of it :/

---

I notice that the latest version `@angular-devkit/*` packages supports node14 or above

```bash
$ npm view @angular-devkit/core engines.node
^14.15.0 || >=16.10.0
```

note that v13 only supports node12

**Comment by micalevisk** [comment]
also, please don't use node10 anymore. There's no reason to :smile: (to me we could drop the support for node10 entirely tbh)

![image](https://user-images.githubusercontent.com/13461315/178109273-24939af8-0da6-4270-a412-f03b7698e228.png)

**Comment by micalevisk** [comment]
https://docs.nestjs.com/migration-guide#nodejs

I just notice that Kamil choose to drop the support for node10 lol I'll update the docs
