### ISSUE TITLE
When installing the V9 version, the installation fails using nest g resource test, and the script that automatically generates test cases needs to be closed to install the dependencies normally.

### ISSUE THREAD

**Issue by webCoder-hm** [nestjs/nest-cli#1720]
### Did you read the migration guide?

- [ ] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Versions

8.0.0 -> 9.0.1

### Describe the regression

When installing the V9 version, the installation fails using nest g resource test, and the script that automatically generates test cases needs to be closed to install the dependencies normally.

### Minimum reproduction code

```ts

```

### Expected behavior

When installing the V9 version, the installation fails using nest g resource test, and the script that automatically generates test cases needs to be closed to install the dependencies normally.

**Comment by micalevisk** [comment]
could you please share with the steps to reproduce your issue? I didn't follow

**Comment by jmcdo29** [comment]
Just tested this in a docker container, is this the error you're getting?
```
npm i
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @jest/console@^28.1.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-07-13T14_16_18_752Z-debug-0.log
```
<details>

<summary>Full output</summary>

```
# npm i -g @nestjs/cli

added 249 packages, and audited 250 packages in 9s

39 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice
npm notice New minor version of npm available! 8.12.1 -> 8.13.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.13.2
npm notice Run npm install -g npm@8.13.2 to update!
npm notice
# nest new resource-test -p npm
⚡  We will scaffold your app in a few seconds..

CREATE resource-test/.eslintrc.js (665 bytes)
CREATE resource-test/.prettierrc (51 bytes)
CREATE resource-test/README.md (3340 bytes)
CREATE resource-test/nest-cli.json (118 bytes)
CREATE resource-test/package.json (1998 bytes)
CREATE resource-test/tsconfig.build.json (97 bytes)
CREATE resource-test/tsconfig.json (546 bytes)
CREATE resource-test/src/app.controller.spec.ts (617 bytes)
CREATE resource-test/src/app.controller.ts (274 bytes)
CREATE resource-test/src/app.module.ts (249 bytes)
CREATE resource-test/src/app.service.ts (142 bytes)
CREATE resource-test/src/main.ts (208 bytes)
CREATE resource-test/test/app.e2e-spec.ts (630 bytes)
CREATE resource-test/test/jest-e2e.json (183 bytes)

▹▹▹▹▸ Installation in progress... ☕
Failed to execute command: npm install --silent
✖ Installation in progress... ☕
🙀  Packages installation failed!
In case you don't see any errors above, consider manually running the failed command npm install to see more details on why it errored out.

                                                                                 Thanks for installing Nest 🙏
                                                                        Please consider donating to our open collective
                                                                               to help us maintain this package.


                                                                      🍷  Donate: https://opencollective.com/nest

# cd resource-test
# npm i
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @jest/console@^28.1.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-07-13T14_16_18_752Z-debug-0.log
```

</details>

**Comment by webCoder-hm** [comment]
1. Uninstall nestcli
2. Install the latest @nestjs/cli
3. Execute nest g resource user
4. Error

> could you please share with the steps to reproduce your issue? I didn't follow
> 
> Also, [why Reproductions are Required](https://antfu.me/posts/why-reproductions-are-required).

1. Uninstall nestcli
2. Install the latest @nestjs/cli
3. Execute nest g resource user
4. Error

**Comment by jmcdo29** [comment]
> 
    Uninstall nestcli
    Install the latest @nestjs/cli
    Execute nest g resource user
    Error

So is this in an existing project that this is happening, not a new one?

**Comment by webCoder-hm** [comment]
> > 
> 
> ```
> Uninstall nestcli
> Install the latest @nestjs/cli
> Execute nest g resource user
> Error
> ```
> 
> So is this in an existing project that this is happening, not a new one?

Old project, I only upgraded "@nestjs/core", it seems to be the same

**Comment by micalevisk** [comment]
you should update every `@nestjs/*` package.

`npx @nestjs/cli@latest new` & `npm i` went fine here.

**Comment by jmcdo29** [comment]
This is the error I just got when trying to run `nest g resource test` on an old help project upgraded to v9

```
nest g resource test
? What transport layer do you use? REST API
? Would you like to generate CRUD entry points? Yes
CREATE src/test/test.controller.spec.ts (556 bytes)
CREATE src/test/test.controller.ts (883 bytes)
CREATE src/test/test.module.ts (240 bytes)
CREATE src/test/test.service.spec.ts (446 bytes)
CREATE src/test/test.service.ts (607 bytes)
CREATE src/test/dto/create-test.dto.ts (30 bytes)
CREATE src/test/dto/update-test.dto.ts (169 bytes)
CREATE src/test/entities/test.entity.ts (21 bytes)
UPDATE package.json (2028 bytes)
UPDATE src/app.module.ts (308 bytes)
⠼ Installing packages (npm)...npm ERR! Cannot read properties of null (reading 'matches')

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jay/.npm/_logs/2022-07-13T14_30_37_718Z-debug-0.log
✖ Package install failed, see above.
The Schematic workflow failed. See above.

Failed to execute command: node @nestjs/schematics:resource --name=test --no-dry-run --no-skip-import --language="ts" --source-root="src" --spec
```

Let me see if I can make a more solid reproduction with better steps all the way through

**Comment by micalevisk** [comment]
@webCoder-hm please share us the output of the `npx nest info` command

**Comment by webCoder-hm** [comment]
> npx nest info


[System Information]
OS Version     : macOS Monterey
NodeJS Version : v16.13.2
PNPM Version    : 7.1.5 

[Nest CLI]
Nest CLI Version : 9.0.0

**Comment by webCoder-hm** [comment]
> 

yes that's it

**Comment by micalevisk** [comment]
looks like there is some version mismatch as that didn't happen in a fresh new app (running `npx nest g resource test`)

**Comment by webCoder-hm** [comment]
> 看起来有一些版本不匹配，因为在新的新应用程序中没有发生这种情况（`npx nest g resource test`按预期运行）

you need to run
Error：Cannot find module '@nestjs/mapped-types' or its corresponding type declarations.

1 import { PartialType } from '@nestjs/mapped-types';

Found 1 error(s).

**Comment by webCoder-hm** [comment]
> looks like there is some version mismatch as that didn't happen in a fresh new app (running `npx nest g resource test` worked as expected)

我就是新安装的cli，
执行 nest g resource test 所报错的
nest g resource test
? What transport layer do you use? REST API
? Would you like to generate CRUD entry points? Yes
CREATE src/test/test.controller.spec.ts (556 bytes)
CREATE src/test/test.controller.ts (883 bytes)
CREATE src/test/test.module.ts (240 bytes)
CREATE src/test/test.service.spec.ts (446 bytes)
CREATE src/test/test.service.ts (607 bytes)
CREATE src/test/dto/create-test.dto.ts (30 bytes)
CREATE src/test/dto/update-test.dto.ts (169 bytes)
CREATE src/test/entities/test.entity.ts (21 bytes)
UPDATE package.json (2028 bytes)
UPDATE src/app.module.ts (308 bytes)
⠼ Installing packages (npm)...npm ERR! Cannot read properties of null (reading 'matches')

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jay/.npm/_logs/2022-07-13T14_30_37_718Z-debug-0.log
✖ Package install failed, see above.
The Schematic workflow failed. See above.

Failed to execute command: node @nestjs/schematics:resource --name=test --no-dry-run --no-skip-import --language="ts" --source-root="src" --spec

**Comment by jmcdo29** [comment]
Not sure what's going on for you, but I couldn't replicate this in docker
```sh
docker run it node:latest sh
npx @nestjs/cli@8 new resource-upgrade-test -p npm --yes
cd resource-upgrade-test
npx nest g res test-v8
npm install @nestjs/common@^9 @nestjs/core@^9 @nestjs/platform-express@^9 @nestjs/cli@^9 @nestjs/schematics@^9 @nestjs/testing@^9
npx nest g res test-v9
```

**Comment by webCoder-hm** [comment]
> > 看起来有一些版本不匹配，因为在新的新应用程序中没有发生这种情况（`npx nest g resource test`按预期运行）
> 
> 你需要运行 错误：找不到模块'@nestjs/mapped-types'或其对应的类型声明。
> 
> 1 从“@nestjs/mapped-types”导入 { PartialType }；
> 
> 发现 1 个错误。

I am the newly installed cli,
The error reported by executing nest g resource test
nest g resource test
? What transport layer do you use? REST API
? Would you like to generate CRUD entry points? Yes
CREATE src/test/test.controller.spec.ts (556 bytes)
CREATE src/test/test.controller.ts (883 bytes)
CREATE src/test/test.module.ts (240 bytes)
CREATE src/test/test.service.spec.ts (446 bytes)
CREATE src/test/test.service.ts (607 bytes)
CREATE src/test/dto/create-test.dto.ts (30 bytes)
CREATE src/test/dto/update-test.dto.ts (169 bytes)
CREATE src/test/entities/test.entity.ts (21 bytes)
UPDATE package.json (2028 bytes)
UPDATE src/app.module.ts (308 bytes)
⠼ Installing packages (npm)...npm ERR! Cannot read properties of null (reading 'matches')

npm ERR! A complete log of this run can be found in:
npm ERR! /home/jay/.npm/_logs/2022-07-13T14_30_37_718Z-debug-0.log
✖ Package install failed, see above.
The Schematic workflow failed. See above.

Failed to execute command: node @nestjs/schematics:resource --name=test --no-dry-run --no-skip-import --language="ts" --source-root="src" --spec

**Comment by webCoder-hm** [comment]
> I notice that in v9 the new app has the hard dependency `@nestjs/mapped-types`
> 
> @webCoder-hm install `@nestjs/mapped-types` and see if it works

pnpm i @nestjs/mapped-types

Error:
error TS2300: Duplicate identifier 'UserModule'.

4 import { UserModule } from './user/user.module';

error TS2300: Duplicate identifier 'UserModule'.

5 import { UserModule } from './user/user.module';

**Comment by webCoder-hm** [comment]
> 🤔 looks like an issue with your environment or setup.
> 
> I won't look at this anymore unless you share some minimum reproduction repository, sorry.
> 
> # [Why Reproductions are Required](https://antfu.me/posts/why-reproductions-are-required)

"dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/mapped-types": "*",
    "@nestjs/platform-express": "^9.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "28.1.4",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "28.1.2",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "28.0.5",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.0.0",
    "typescript": "^4.3.5"
  },

are these ok？

**Comment by webCoder-hm** [comment]
> I copy paste your deps in a nest v8 app, removed the lock file, ran `npm install` & `npx nest g resource test` & `npm run start:dev`. Everything went fine here.

I need to sleep, I will reproduce it tomorrow (this is mandatory in the V9 version), what parameters do I need to provide?

**Comment by micalevisk** [comment]
just share some full project and the steps that to reproduce your issue.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
