### ISSUE TITLE
Components must be generated from project root

### ISSUE THREAD

**Issue by ps2goat** [nestjs/nest-cli#173]
When using the Angular CLI tool, it's common for me to navigate into module directories, which may be 2-5 folders deep.  I can then run the generate command and components will be generated relative to the path I am in.

Example:
I'm in `/src/area1/section1/`.  `ng g c test` results in a component created in `/src/area1/section1/test` 

With nest, I have to stay at the root of the project and pass in the full path from project root (less the `/src` folder).

Example, using the above use case, but with a service:
I'm in `./`, `nest g s area1/section1/test` is how I create a new service at the level I need it.

This is a minor nuisance, but noticeable to me.

**Comment by ianmh** [comment]
Angular has a `--flat` flag used to indicate if a directory should be created. This would be nice.

**Comment by kamilmysliwiec** [comment]
It should be fixed in the latest release. Please, let me know if you face any issue.
