### ISSUE TITLE
Generation error - Unknown argument skipImport. Did you mean skip-import?

### ISSUE THREAD

**Issue by qWici** [nestjs/nest-cli#1733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I've got the same error that in this [issue](https://github.com/nestjs/nest-cli/issues/1693). I found this solution and update my package to 9.0.0. But I still got same error if I call cli from root of project. If I change directory to `src` it works fine.

My project struct:
```shell
- root
- - src
- - - modules
- - package.json
- - etc
```

```shell
$ pwd
/project/
$ nest g mo modules/mymodule
error
$ nest g mo src/modules/mymodule
error

$ cd src/
$ nest g mo modules/mymodule
It works!
```

```shell
/project/node_modules/@angular-devkit/schematics-cli/bin/schematics.js:338
            throw new Error(`Unknown argument ${key}. Did you mean ${(0, yargs_parser_1.decamelize)(key)}?`);
                  ^

Error: Unknown argument skipImport. Did you mean skip-import?
    at parseArgs (/project/node_modules/@angular-devkit/schematics-cli/bin/schematics.js:338:19)
    at main (/project/node_modules/@angular-devkit/schematics-cli/bin/schematics.js:122:49)
    at Object.<anonymous> (/project/node_modules/@angular-devkit/schematics-cli/bin/schematics.js:367:5)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

### Minimum reproduction code

nest g mo modules/mymodule

### Expected behavior

It generate module

### Package version

9.0.0

### NestJS version

8.0.0

### Node.js version

16.16.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
you're problably using the old version. v9 works fine here.

![image](https://user-images.githubusercontent.com/13461315/179419402-dcc6c717-aeba-4806-be67-00b8839e842f.png)

please share the output of `npx nest info`

**Comment by qWici** [comment]
> you're problably using the old version. v9.0.0 works as expected here.
> 
> ![image](https://user-images.githubusercontent.com/13461315/179419402-dcc6c717-aeba-4806-be67-00b8839e842f.png)
> 
> please share the output of `npx nest info` (note that now you won't use the global `@nestjs/cli` but the local one due to `npx`)

Yeah, you are right. And I'm a little bit confused. Why `nest -v` show me `9.0.0` version?

```shell
 ~/dev/web/project npx nest info

[System Information]
OS Version     : macOS Monterey
NodeJS Version : v16.16.0
YARN Version    : 1.22.19 

[Nest CLI]
Nest CLI Version : 8.2.7 

[Nest Platform Information]
platform-express version : 8.4.7
event-emitter version    : 1.3.0
schematics version       : 8.0.11
passport version         : 8.2.2
typeorm version          : 8.1.4
testing version          : 8.4.7
common version           : 8.4.7
config version           : 2.1.0
core version             : 8.4.7
jwt version              : 8.0.1
cli version              : 8.2.7

 ~/dev/web/project nest -v
9.0.0

```

**Comment by micalevisk** [comment]
it's how NPM works. When you install `@nestjs/cli` globally, you'll have the `nest` command available. I don't recommend this. I prefer always using the `@nestjs/cli` used in the project instead.

If I don't have any project, I can call `npx @nestjs/cli new` to start a new one.

Anyway, there's nothing to fix here. Just upgrade your local `@nestjs/cli` to 8.2.8.

**Comment by qWici** [comment]
Got it. Thanks!
