### ISSUE TITLE
Is there any plan to add a build argument to support build with dependencies and minified?

### ISSUE THREAD

**Issue by bthulu** [nestjs/nest-cli#1739]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

we are using nestjs for factory device controls.
we have many customers, none of them allows server pc connect to internet, so npm i will not work.
we need to deploy to the server pc without internet, and we also want to protect our code by minify all js files.
so if can build with dependencies and minify, we can package to a zip file, and deploy it by copy.

### Describe the solution you'd like

run the following, get a dist folder with dependencies and all src js files minified as one main.js file.
`npm run build --withDependencies --minify`
dist foler structure like bellow:
```
dist
--main.js
--node_modules
----@nestjs
----rxjs
```

### What is the motivation / use case for changing the behavior?

deploy under no internet environment, deploy to many customer's internal network.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
