### ISSUE TITLE
Need to set bodyParser:false to override it

### ISSUE THREAD

**Issue by sshevlyagin** [nestjs/nest-cli#1740]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

You need to disable bodyParser to customize it.

For example [main.ts](https://github.com/sshevlyagin/nest-test/blob/main/src/main.ts)
```
const app = await NestFactory.create(AppModule, {bodyParser: false});
```
[app.module.ts](https://github.com/sshevlyagin/nest-test/blob/main/src/app.module.ts)

```
    consumer
      .apply(json({ limit: '5mb' }))
      .forRoutes({ path: '/upload', method: RequestMethod.POST });
    consumer
      .apply(json({ limit: '10kb' }))
      .exclude({ path: '/upload', method: RequestMethod.ALL })
      .forRoutes('*');
```

### Minimum reproduction code

https://github.com/sshevlyagin/nest-test

### Steps to reproduce

1. Clone repo and run test.js observe how the function succeeds
2. Remove `bodyParser:false` from `main.ts`
3. Observe how now you get a 413

### Expected behavior

Don't need to turn bodyParser off to override it

### Package version

8.2.8

### NestJS version

8.4.7

### Node.js version

16.15.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by sshevlyagin** [comment]
My biggest paint point is that this was undocumented and took a while to figure out. Would love a note about it in the [middleware section](https://docs.nestjs.com/middleware)

**Comment by micalevisk** [comment]
PRs are more than welcomed :smile_cat:

**Comment by sshevlyagin** [comment]
> PRs are more than welcomed 😸

Happy to do it, just want to hear if this is by design first or not.

**Comment by micalevisk** [comment]
oh, right. I believe it was intentional because the default `json()` middleware is registered before all the others. But let's wait for Kamil.

**Comment by kamilmysliwiec** [comment]
This is the expected behavior.
