### ISSUE TITLE
Yarn berry (pnp) not working with NestJS

### ISSUE THREAD

**Issue by leomelki** [nestjs/nest-cli#1741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

After installing the dependencies of a new project (created using `nest new`, with nest cli v9.0.0) using yarn berry (pnp), the project isn't able to be built.
It produces this error :
![image](https://user-images.githubusercontent.com/4275184/183519149-3f8b46d6-a9ba-48af-8f96-0a57b4a5fbc1.png)

It may be because some used dependencies are not explicitly specified.

### Minimum reproduction code

https://github.com/leomelki/NestJS-yarnberry-bug

### Steps to reproduce

nest new test --skip-install
cd test
yarn set version berry
touch yarn.lock
yarn install
yarn build

### Expected behavior

After yarn build is executed, it should fail because some dependencies are not specified

### Package version

9.0.0

### NestJS version

9.0.0

### Node.js version

16.16.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

**Comment by micalevisk** [comment]
can you run `yarn why body-parser`

**Comment by jmcdo29** [comment]
<details>

<summary>This worked for me inside of a fresh docker container</summary>

```
❯ docker run -it node:latest sh
# nest new test --skip-install^C
# npm i -g @nestjs/cli

added 249 packages, and audited 250 packages in 16s

39 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice
npm notice New minor version of npm available! 8.12.1 -> 8.16.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.16.0
npm notice Run npm install -g npm@8.16.0 to update!
npm notice
# nest new test --skip-install
⚡  We will scaffold your app in a few seconds..

CREATE test/.eslintrc.js (665 bytes)
CREATE test/.prettierrc (51 bytes)
CREATE test/README.md (3340 bytes)
CREATE test/nest-cli.json (118 bytes)
CREATE test/package.json (1989 bytes)
CREATE test/tsconfig.build.json (97 bytes)
CREATE test/tsconfig.json (546 bytes)
CREATE test/src/app.controller.spec.ts (617 bytes)
CREATE test/src/app.controller.ts (274 bytes)
CREATE test/src/app.module.ts (249 bytes)
CREATE test/src/app.service.ts (142 bytes)
CREATE test/src/main.ts (208 bytes)
CREATE test/test/app.e2e-spec.ts (630 bytes)
CREATE test/test/jest-e2e.json (183 bytes)


                                                                                 Thanks for installing Nest 🙏
                                                                        Please consider donating to our open collective
                                                                               to help us maintain this package.


                                                                      🍷  Donate: https://opencollective.com/nest

# cd test
# yarn set version berry
warning package.json: "test" is also the name of a node core module
➤ YN0000: Retrieving https://repo.yarnpkg.com/3.2.2/packages/yarnpkg-cli/bin/yarn.js
➤ YN0000: Saving the new release in .yarn/releases/yarn-3.2.2.cjs
➤ YN0000: Done in 0s 876ms
# touch yarn.lock
# yarn install
➤ YN0000: ┌ Resolution step
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0002: │ test@workspace:. doesn't provide webpack (p5b92c), requested by ts-loader
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 7s 42ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yargs-parser@npm:21.1.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:17.5.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yn@npm:3.1.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ typescript@npm:4.7.4 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 34s 74ms
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0007: │ @nestjs/core@npm:9.0.8 [57297] must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 1s 625ms
➤ YN0000: Done with warnings in 42s 975ms
# yarn build
```

</details>

`body-parser` is a defined dependency in the `package.json` of `@nestjs/platform-express`. All of the others are either transitive or optional, and should not explicitly be relied upon unless requested.

**Comment by leomelki** [comment]
Hmm, that's wierd.
`yarn why body-parser` returns this on my end : 
![image](https://user-images.githubusercontent.com/4275184/183523757-4faf9bbb-5a57-48f4-93e4-30462e04f9b1.png)

**Comment by jmcdo29** [comment]
Those deps make sense, but it's also explicitly requested in the package.json so I don't know what yarn berry is complaining about. 

Like I said and showed above, your reproduction steps in a docker container worked fine, so I can only assume it's a library you've got installed instead that is causing some sort of issue

**Comment by leomelki** [comment]
You're true, I did the same on a blank docker image and it worked. Yes, I'll investigate it, and re open the issue if I find that it happened because of a problem on NestJS end (unlikely).

Thanks !
