### ISSUE TITLE
support "delete" or "rm" to revert "generate" command

### ISSUE THREAD

**Issue by ianzone** [nestjs/nest-cli#1745]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

none

### Describe the solution you'd like

create a "delete" or "rm" command to revert the "generate" command

### What is the motivation / use case for changing the behavior?

when I want to remove the code created by "next generate", I have to find and manually delete all related files and imports.

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
