### ISSUE TITLE
Generate resources from OpenAPI 

### ISSUE THREAD

**Issue by ianzone** [nestjs/nest-cli#1747]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

none

### Describe the solution you'd like

Generate controllers with validation and testing files from the OpenAPI specification.

### Teachability, documentation, adoption, migration strategy

nest g res --openapi api.json
or
nest g res --openapi api.yaml

### What is the motivation / use case for changing the behavior?

To implement the Design-First approach to API development

**Comment by micalevisk** [comment]
I like that. 

https://github.com/mrjmd/angular-openapi-schematics

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
