### ISSUE TITLE
override default apps folder name

### ISSUE THREAD

**Issue by Evanion** [nestjs/nest-cli#1748]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

running the cli in monorepo mode, It would help to be able to change the folder name where it generates the new apps. right now, it creates apps in the apps folder, but  I want it to generate all new apps in the services folder.

<project root>
|- clients // <- contains the frontend apps
|- libs // <- contains generated libs
|- services // <- contains all the backend microservices

### Describe the solution you'd like

I would like to be able to define the folder name for folders that contain apps and libs

### What is the motivation / use case for changing the behavior?

When working with a application monorepo, it's common to separate backend and frontend apps in to separate directories. 
The nest cli should be able to allow the user to describe for the cli where it should place different codebases in a way that _**doesn't**_ rely on specific monorepo structures or solutions (turbo, nx, yarn workspaces etc).

example
```
<project root>
|- clients // <- contains the frontend apps (react, react-native, solid, etc.)
  |- desktop
  |- mobile
  |- web
  ...
|- libs // <- contains generated libs (generated by nest cli or other clis)
  |- ui
  |- utils
  ...
|- services // <- contains all the backend microservices (nest.js apps)
  |- orders
  |- products
  |- users
  ... 
```
reference: https://discord.com/channels/520622812742811698/600684956288548866/1000147920408039424

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future. If you need more flexibility & want to organize your directories differently, you likely shouldn't be using the NestJS CLI monorepo mode.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
