### ISSUE TITLE
Generated project break if resizing terminal window

### ISSUE THREAD

**Issue by dreamdevil00** [nestjs/nest-cli#175]
My env

system: windows7 64bit
```
C:\Users\Administrator>nest --version
5.3.0

C:\Users\Administrator>node -v
v8.11.2

C:\Users\Administrator>npm -v
5.6.0
```
Please update generated ts-node version to lastest to fix the issue

**Comment by kamilmysliwiec** [comment]
Will be fixed by this PR https://github.com/nestjs/schematics/pull/92
