### ISSUE TITLE
TypeScript unsupported version by @typescript-eslint

### ISSUE THREAD

**Issue by Chris7ca** [nestjs/nest-cli#1750]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

After a fresh installation runs the `lint` script and this is the output

```
> users@0.0.1 lint
> eslint "{src,apps,libs,test}/**/*.ts" --fix

=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.8.0

YOUR TYPESCRIPT VERSION: 4.8.2

Please only submit bug reports when using the officially supported version.

=============

/home/user/test/users/src/app.controller.ts
  1:10  warning  'Controller' is defined but never used     @typescript-eslint/no-unused-vars
  1:22  warning  'Get' is defined but never used            @typescript-eslint/no-unused-vars
  5:14  warning  'AppController' is defined but never used  @typescript-eslint/no-unused-vars

/home/user/test/users/src/app.module.ts
   1:10  warning  'Module' is defined but never used         @typescript-eslint/no-unused-vars
   2:10  warning  'AppController' is defined but never used  @typescript-eslint/no-unused-vars
   3:10  warning  'AppService' is defined but never used     @typescript-eslint/no-unused-vars
  10:14  warning  'AppModule' is defined but never used      @typescript-eslint/no-unused-vars

/home/user/test/users/src/app.service.ts
  1:10  warning  'Injectable' is defined but never used  @typescript-eslint/no-unused-vars
  4:14  warning  'AppService' is defined but never used  @typescript-eslint/no-unused-vars

✖ 9 problems (0 errors, 9 warnings)
```

This heppens beacause in the package.json the typescript is required  like `"typescript": "^4.3.5"` and this get the latest version of typescript which is currently on [beta](https://www.typescriptlang.org/)

Temporary solution: downgrade to stable version 

```
$ npm i -D typescript@~4.7.4
```

### Minimum reproduction code

https://gist.github.com/Chris7ca/7a32496c00143d45f7dbaa3856e9e216

### Steps to reproduce

1. `npm run lint`

### Expected behavior

Lint all files without this warning message

```
> users@0.0.1 lint
> eslint "{src,apps,libs,test}/**/*.ts" --fix

=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.8.0

YOUR TYPESCRIPT VERSION: 4.8.2

Please only submit bug reports when using the officially supported version.

=============
```

### Package version

9.0.0

### NestJS version

9.0.0

### Node.js version

16.17.0

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [X] Linux

### Other

The `typescript-eslint` GitHub [page](https://github.com/typescript-eslint/typescript-eslint) propose a possible solution to remove that warning message (in the `.eslintrc.js` under `parserOptions` set `warnOnUnsupportedTypeScriptVersion: true` but this only remove the warning message and the lint is not working well yet

More info about it: [here](https://github.com/typescript-eslint/typescript-eslint/issues/5227)

**Comment by zynth17** [comment]
hope this got fixed, since 4,8 is already the latest stable release as of  yesterday

**Comment by micalevisk** [comment]
we could change the semver range on `typescript` until `@typescript-eslint/*` start supporting v4.8

PRs are more than welcomed: https://github.com/nestjs/schematics/blob/56fd9297814762c67c49bec724753a63b1b25c1b/src/lib/application/files/ts/package.json#L52

**Comment by Chris7ca** [comment]
For sure @micalevisk, I will

**Comment by yoshiishunichi** [comment]
I am facing a similar problem.
The version of nest-cli is 9.1.1.


Initialize the project, and then VScode you will see a `@typescript-eslint/no-unused-vars` warning about the class decorator.

![スクリーンショット 2022-08-29 19 05 26](https://user-images.githubusercontent.com/65440913/187178325-4c486c0b-658f-4f38-aac3-9d1e1a9a856e.png)

It can be easily ignored by downgrading the version to `@typescript-eslint/eslint-plugin:"^4.33.0"` in the `package.json` generated when the NestJS project is initialized.

However, variables that are not really in use will also go undetected.

**Comment by mikeogi** [comment]
> + I have the same problem 😒

**Comment by ducker-dev** [comment]
> I am facing a similar problem. The version of nest-cli is 9.1.1.
> 
> Initialize the project, and then VScode you will see a `@typescript-eslint/no-unused-vars` warning about the class decorator.
> 
> ![スクリーンショット 2022-08-29 19 05 26](https://user-images.githubusercontent.com/65440913/187178325-4c486c0b-658f-4f38-aac3-9d1e1a9a856e.png)
> 
> It can be easily ignored by downgrading the version to `@typescript-eslint/eslint-plugin:"^4.33.0"``package.json` in the generated when the NestJS project is initialized.
> 
> However, variables that are not really in use will also go undetected.

Yes, yes, I have the same, please correct
<img width="815" alt="image" src="https://user-images.githubusercontent.com/38755241/187196733-a13e8a7f-001a-42ad-8d9b-f80a608b00af.png">

**Comment by kamilmysliwiec** [comment]
AFAIK a compatible version of ESLint should have been published a few minutes ago

**Comment by ducker-dev** [comment]
How long will it take to fix this bug?

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest-cli/issues/1750#issuecomment-1230232257

**Comment by yoshiishunichi** [comment]
> How long will it take to fix this bug?

The bug seems to have been fixed in [this release.](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v5.36.0)
Thank you very much.
