### ISSUE TITLE
nest build error with typescript 4.8.2

### ISSUE THREAD

**Issue by SirReiva** [nestjs/nest-cli#1752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![image](https://user-images.githubusercontent.com/50754871/186890678-89925446-4b8b-44bf-bf65-193490417822.png)

### Minimum reproduction code

none

### Expected behavior

Successfully build the application

### Package version

9.0.0

### NestJS version

9.0.0

### Node.js version

16.13.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
It works here.

Please provide a minimum reproduction repository](https://jmcdo29.github.io/wtf-is-a-minimum-reproduction.

# [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by SirReiva** [comment]
I dont not exactly what ts transformation causes that error to build a reproduction repository

**Comment by micalevisk** [comment]
which version of typescript are you using? `npm ls typescript`

**Comment by SirReiva** [comment]
typescript v4.8.2
![image](https://user-images.githubusercontent.com/50754871/186923369-a9f22ee4-5f4f-49eb-b29c-e2db1419b325.png)

**Comment by micalevisk** [comment]
I belive it will work if you downgrade to `typescript@4.7`, for now

**Comment by sombochea** [comment]
> I belive it will work if you downgrade to `typescript@4.7`, for now
> 
> Looks like an issue with `@nestjs/grapqhl`

It works for version: `typescript@4.7.4` or below. Thanks!

**Comment by kamilmysliwiec** [comment]
This should be fixed in the latest version of @nestjs/graphql
