### ISSUE TITLE
Add a database step when creating a new project

### ISSUE THREAD

**Issue by IonelLupu** [nestjs/nest-cli#177]
I think a database is a key element in the majority of the apps. It would be nice to have a new step added for adding a database:

It can be something like this:
```
Database driver:

1. No database
2. Typeorm
3. Mongoose
4. Sequelize
```

The user can choose ` No database` if he doesn't use one or one of the other options depending what he needs.

**Comment by kamilmysliwiec** [comment]
We'll rather add support for `nest add` command (for example, `nest add typeorm` that would reduce the amount of boilerplate required to start playing with db).

**Comment by JCWolf** [comment]
That would be nice too.

**Comment by santoshyadav198613** [comment]
Hi @kamilmysliwiec ,

Let me know if i can work on it, looks like a big feature, we can do it in parts. I have worked on schematics, so i think i can help.

**Comment by l2ubin** [comment]
let me know if i can help with the code

**Comment by kamilmysliwiec** [comment]
More details here: https://github.com/nestjs/nest-cli/issues/177#issuecomment-446580241
