### ISSUE TITLE
boiler plate e2e-test should use 'beforeAll' when initializing modules

### ISSUE THREAD

**Issue by taisei-yamamoto** [nestjs/nest-cli#1776]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

When we use 'nest new my-nest-project', nest-cli will generate boiler plate plate codes.
They contain e2e-test code, `app.e2e-spec.ts` .

```ts
...

describe('AppController (e2e)', () => {
  let app: INestApplication;

  beforeEach(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    await app.init();
  });

  it('/ (GET)', () => {
    ...
```

### Describe the solution you'd like

I think that `beforeEach` should be `beforeAll` because we need initialize(create) module only once.
Some example codes seen in nestjs [document](https://docs.nestjs.com/fundamentals/testing#end-to-end-testing) and [Github](https://github.com/nestjs/nest/tree/master/sample) also use `beforeAll` when initializing module.

Is there any reason for using `beforeEach` in boiler plate codes? Thanks.

### What is the motivation / use case for changing the behavior?

When generating nestjs boiler plate codes and using sample e2e-test codes, users will be happy.

**Comment by kamilmysliwiec** [comment]
It just depends on what you want to accomplish. Certain users prefer to roll back actions per test, not per test suite. There's no recommended approach
