### ISSUE TITLE
boiler plate e2e-test should 'app.close' in 'afterAll' method

### ISSUE THREAD

**Issue by taisei-yamamoto** [nestjs/nest-cli#1777]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

When we use 'nest new my-nest-project', nest-cli will generate boiler plate plate codes.
They contain e2e-test code, app.e2e-spec.ts .

```ts
...

describe('AppController (e2e)', () => {
  let app: INestApplication;

  beforeEach(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    await app.init();
  });

  it('/ (GET)', () => {
    ...
```

### Describe the solution you'd like

I think that `app.close` should be call.
Some example codes seen in nestjs [Github](https://github.com/nestjs/nest/tree/master/sample) also call `app.close` in `beforeAll`

Is there any reason for not closing app in boiler plate codes? Thanks.

### What is the motivation / use case for changing the behavior?

When generating nestjs boiler plate codes and using sample e2e-test codes, users will be happy.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest-cli/issues/1776#issuecomment-1237765734
