### ISSUE TITLE
Using webpack, typescript are checked two times

### ISSUE THREAD

**Issue by phoenix741** [nestjs/nest-cli#1793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When use webpack with @nestjs/cli the webpack file generated by nest contains :

config.module.rules[0].use =>
```js
[
  {
    loader: 'ts-loader',
    options: {
      transpileOnly: true,
      configFile: 'apps/application/tsconfig.app.json',
      getCustomTransformers: [Function: getCustomTransformers]
    }
  }
]
```
config.plugins =>
```js
[
  IgnorePlugin {
    options: { checkResource: [Function: checkResource] },
    checkIgnore: [Function: bound checkIgnore]
  },
  ForkTsCheckerWebpackPlugin { options: { typescript: [Object] } },
  IgnorePlugin {
    options: { checkResource: [Function: checkResource] },
    checkIgnore: [Function: bound checkIgnore]
  }
]
web
```

From the documentation of webpack https://webpack.js.org/guides/build-performance/#typescript-loader if we put the plugin ForkTsCheckerWebpackPlugin, we should put transpileOnly to "true" to move the typechecker in another process.

We can find in https://www.npmjs.com/package/fork-ts-checker-webpack-plugin :

```js
        // add transpileOnly option if you use ts-loader < 9.3.0 
        // options: {
        //   transpileOnly: true
        // }
```

The transpileOnly should be put to false if ts-loader < 9.3.0, or nothing if >= 9.3.0.

The build time pass from 50s to 26s on my project when removing transpileOnly and typechecking continue to work.

### Minimum reproduction code

https://github.com/phoenix741/nestjs-optimize-bundle

### Expected behavior

Only make typechecking one times

### Package version

9.1.3

### NestJS version

9.1.3

### Node.js version

16.15.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Fixed in 9.1.4
