### ISSUE TITLE
[DISCUSSION] - Contributions guidelines

### ISSUE THREAD

**Issue by MonsieurMan** [nestjs/nest-cli#18]
I'm beginning working on the project, currently reading through the codebase.  

I think we should write a **CONTRIBUTE.md** file first and choose a way to proceed. 
@ThomRick, I think you have more experience than me on this field, maybe you could lead the way ?
We also need a place to keep the **roadmap**, maybe as a clear section in the readme ?

_I feel guilty when I see that the four opened issues are mine, I promise I'll PR to close them soon. :sweat_smile:_  
_By the way, congrats on the codebase, a pleasure to read it is._

**Comment by ThomRick** [comment]
Hey @MonsieurMan,

Totally agree about the CONTRIBUTE.md ! I'll add it soon to the repository.

About the roadmap I have created a Trello. 
I'll open it publicly and add the link to the README.md soon ;-)

Thank's a lot for the compliment about the code :-D
Actually I'm on a refactoring phase to have a nicer and evolutive code to implement the next features of the CLI. I also want to use the hexagonal architecture so that's a long journey regarding the actual code base.
Moreover I'll try to make a more stable build process to protect the master branch and help people to have an easier contribution time ! ;-)

Don't feel guilty because you use the project ;-)
Enjoy the contributions ! That's awesome ! :-D

**Comment by adrien2p** [comment]
Hey!

I waiting also the roadmap, i'll soon add to my repo's and maybe ill add few feature :)

See you

**Comment by ThomRick** [comment]
Hey guys,

I've just add the trello link to the roadmap on the README.md file.

I'll create the issues directly in the GitHub repository for you guys who want to contribute. ;-)

**Comment by MonsieurMan** [comment]
You should add this to the trello !
![nest](https://user-images.githubusercontent.com/13108166/31984625-809afddc-b962-11e7-937e-bea00581ed55.png)

**Comment by ThomRick** [comment]
Hey ! Done !

**Comment by MonsieurMan** [comment]
Hey, @ThomRick, what do you think about opening a Slack Channel (or something equivalent if you know of other platforms).  
I think we need to get this CLI moving quickly for the framework to be really appealing.  

I say this because I have a friend, @Nexyll, who wrote a little cli in C# yesterday because he was not confident using or contributing to this one.  
The thing is that I don't like issues for one thing, it's not possible to have a discussion over a couple of minutes with them.

@wbhob, I saw you were really active on the project, what do you think, would you use it or have any ideas?

**Comment by ThomRick** [comment]
Hey @MonsieurMan !

There is a Gitter already here https://gitter.im/nestjs/nest-cli
;-)

**Comment by ThomRick** [comment]
I think that contributing is not just write some code. 
So rewrite the tool is not the right solution.
If he is scared about write code he could take easy issues or experiment in a branch ;-)
(I have to flag easy issues / features by the way)

Having to code base for the same tool is a problem to synchronize these...

**Comment by MonsieurMan** [comment]
I was reading through CONTRIBUTING.md files and I found the [angular material one](https://github.com/angular/material2/blob/master/CONTRIBUTING.md) really nice. Maybe we could use it as a base. Just removing unnecessary parts and quoting them at the start.

**Comment by Nexyll** [comment]
Hi!
I'm not going to rewrite a new CLI in C# but just a tool to generate modules with CRUD controllers, Typeorm repositories and entities.
But i'm not against contributing on this project I just need some time to look at the architecture to code the feature properly (If you are interested in this feature 😄 ).

**Comment by ThomRick** [comment]
CONTRIBUTE.md on branch nest-v4 and nest-v5
Will be merged to master for current production code
