### ISSUE TITLE
Support cli hooks

### ISSUE THREAD

**Issue by KiritaniAyaka** [nestjs/nest-cli#1804]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Runs script at some specific time.

There is currently a resolution is that change scripts of package.json, but it has some shortcomings.

For example, I want to run script after compile and using `nest start --watch && node script.js`, my script will never run because of `--watch`. If using `node script.js && nest start --watch` for running before compile, scripts won't re-run while source code change.

### Describe the solution you'd like

The nest cli import `hooks/index.ts` at start of running. This ts file exports some hooks. The cli runs them at corresponding time.

```typescript
// run when all source code is not compiled
export const beforeCompile = () => {
	// do something
}

// sourceFile: the file path to be compiled
export const beforeCompileSource = (sourceFile: string) => {
	// do something

	// return true to skip this file
	return true
}

export const afterCompileSource = (sourceFile: string) => {
	// do something
}

// run after all source code compiled
export const afterCompile = () => {
	// do something
}
```

The above is just a simple design. It could be more detailed.

The cli can read config from `nest-cli.json` to support more number of hooks:

```json
{
  "$schema": "https://json.schemastore.org/nest-cli",
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {},
  "hooks": ["hooks/index.ts", "hooks/otherHooks.ts"]
}
```

### What is the motivation / use case for changing the behavior?

Runs script at the specific time. It can be used for running pre-build scripts, and scripts will re-run while source code change, and could be used for skip compile/copy procedure for some files.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by KiritaniAyaka** [comment]
> Would you like to create a PR for this issue?

I don't understand the source code of nest much, this may hard to me. 😢

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest-cli/pull/1808
