### ISSUE TITLE
Failed to execute command: pnpm install --reporter=silent

### ISSUE THREAD

**Issue by wangrongding** [nestjs/nest-cli#1806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

1. sudo npm i -g @nestjs/cli
2. nest new nestjs-demo
3. <img width="972" alt="image" src="https://user-images.githubusercontent.com/42437658/194120168-9ce81da8-c680-404e-ab37-785642295baa.png">

### Minimum reproduction code

no

### Steps to reproduce

1. sudo npm i -g @nestjs/cli
2. nest new nestjs-demo
3. <img width="972" alt="image" src="https://user-images.githubusercontent.com/42437658/194120168-9ce81da8-c680-404e-ab37-785642295baa.png">

### Expected behavior

`nest new nestjs-demo` works fine

### Package version

9.1.4

### Node.js version

v16.16.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
can you run `pnpm install` manually to see what's the error?

**Comment by jmcdo29** [comment]
Most likely due to peer deps. pnpm v7 is strict on them by default. I have `strict-peer-dependencies=false` in a global `.npmrc` to get around it, but we should probably update the flag for pnpm installs

**Comment by wangrongding** [comment]
> can you run `pnpm install` manually to see what's the error?

It only happens when running `nest new xxx`

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue @jmcdo29?

**Comment by jmcdo29** [comment]
> Would you like to create a PR for this issue @jmcdo29?

You got it! I'll try to get something up soon

**Comment by Just-imp** [comment]
this issue is not sloved
### environment
windows 11 22H2  22621.1413
- node v16.18.1
- nest v9.3.0
- pnpm 8.1.0
### issue 
![image](https://user-images.githubusercontent.com/65442050/229398777-fb8a8691-809d-4fe0-b2a1-69c51b9b8359.png)

**Comment by Just-imp** [comment]
> this issue is not sloved
> 
> ### environment
> windows 11 22H2 22621.1413
> 
> * node v16.18.1
> * nest v9.3.0
> * pnpm 8.1.0
> 
> ### issue
> ![image](https://user-images.githubusercontent.com/65442050/229398777-fb8a8691-809d-4fe0-b2a1-69c51b9b8359.png)

nest new has creat project and it can run command pnpm start  successfully, but CLI has prompt an error

**Comment by YogeshUmeshVaity** [comment]
I had this issue too. Turns out, I didn't have the pnpm installed previously. If anyone else stumbles across this, first install the pnpm before running `nest new` command:

`npm install -g pnpm`
