### ISSUE TITLE
Why is generated the gateway in root directory using Nest-CLI??

### ISSUE THREAD

**Issue by godtaehee** [nestjs/nest-cli#1807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

https://discord.com/channels/520622812742811698/1029268908999446528/1029268908999446528

I generate Gateway using Nest-CLI. I expect the gateway is also generated in domain folder like controller, service.

I mean, when I use those commands nest g module some-domoain, nest g controller some-domain, etc..

Nest-CLI make some-domain folder and also generate module, controller files in this folder.

But, I think gateway is not operated like it.

Any Advice?

### Minimum reproduction code

https://discord.com/channels/520622812742811698/1029268908999446528/1029268908999446528

### Steps to reproduce

<img width="676" alt="Screen Shot 2022-10-12 at 10 50 03 AM" src="https://user-images.githubusercontent.com/44861205/195230305-dc1bab9f-66af-41d2-9307-32482228ffc6.png">

### Expected behavior

Nest-CLI make some-domain folder and also generate module, controller files in this folder.

But, I think gateway is not operated like it.

### Package version

8.1.6

### NestJS version

8.0.0

### Node.js version

latest

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Tony133** [comment]
To add a new gateway file inside the dogs folder, you will need to do the following ( see screenshot)

<img width="852" alt="screenshot" src="https://user-images.githubusercontent.com/11542387/195596304-71521cad-5519-43c0-9b1d-c387f3747bda.png">

**Comment by kamilmysliwiec** [comment]
This is the expected behavior.

Please search through some of our old issues on this (this has been discussed several times in the past).
