### ISSUE TITLE
"add" command doesn't follow skip-install convention.

### ISSUE THREAD

**Issue by z3bra5hax** [nestjs/nest-cli#1809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```bash
nest add [library] --skip-install
```
does not skip installation, nor does --skipInstall (which is documented in @nestjs libraries such as azure-func-http)

### Minimum reproduction code

n/a

### Steps to reproduce

1. Install a package (here the reason is because the legacy-peer-deps flag was needed): `npm install --save @nestjs/azure-func-http --legacy-peer-deps`.

2. Attempt to utilize schematic with "add" action: `nest add @nestjs/azure-func-http --skip-install`.

Optional: Attempt skipInstall as documented in the above @nestjs library: `nest add @nestjs/azure-func-http --skip-install`. 

### Expected behavior

Successful schematic build.
(e.g.)
```bash
CREATE .funcignore (66 bytes)
CREATE host.json (23 bytes)
CREATE local.settings.json (116 bytes)
CREATE proxies.json (72 bytes)
CREATE main/function.json (294 bytes)
CREATE main/index.ts (287 bytes)
CREATE main/sample.dat (23 bytes)
CREATE src/main.azure.ts (321 bytes)
UPDATE package.json (2136 bytes)
```

### Package version

9.1.4

### NestJS version

9.1.4

### Node.js version

16.16.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

This may technically be more of a feature request; however as it would be more conventional and the aforementioned documentation in @nestjs libraries regarding skipping installation makes this seem like it falls more into the "bug" category.

Happy to pick this one up.

**Comment by z3bra5hax** [comment]
I'm happy to pick this one up!

**Comment by micalevisk** [comment]
but that's  not a valid option for `nest add`, see:

https://github.com/nestjs/nest-cli/blob/75e7a620ec284f0f35121e8edb2267cce6e449f5/commands/add.command.ts#L9-L17

**Comment by z3bra5hax** [comment]
Hey @micalevisk! Thank you, yeah I probably should have filed this as a feature request as opposed to bug: I noted my reasoning for the decision to go with "bug" in the "Other" section of the report but I certainly understand exactly where you're coming from.

**Comment by micalevisk** [comment]
Sounds like a good feature. Feel free to open a PR anytime, thanks :smiley_cat:

**Comment by z3bra5hax** [comment]
Related PR: https://github.com/nestjs/nest-cli/pull/1810

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest-cli/pull/1810
