### ISSUE TITLE
Trying to Import Library in to apps in mono repo but Cannot find module '@app/utils-library' or its corresponding type declarations. 

### ISSUE THREAD

**Issue by tylerjusfly** [nestjs/nest-cli#1811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

i ran the cli command of " nest g library utils-library " it got imported but i'm trying to make use of library in apps folder , but it can't find it

![image](https://user-images.githubusercontent.com/53145644/196792457-54dba084-12c3-4164-aa95-d34f3418beed.png)

all folders are in correct condition
![image](https://user-images.githubusercontent.com/53145644/196792559-dc32ffe7-7196-46f1-8f24-825c2e5f45a5.png)

### Minimum reproduction code

https://github.com/tylerjusfly/monorepo-microservice-app/blob/main/apps/products/src/products.module.ts

### Expected behavior

Cannot find module '@app/utils-library' or its corresponding type declarations.

### Package version

9.0.0

### NestJS version

9.1.3

### Node.js version

16.15.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

IDE _- vs code

**Comment by micalevisk** [comment]
did you got that error on building/running your project or just on your IDE?

**Comment by tylerjusfly** [comment]
@micalevisk  just in the IDE

**Comment by micalevisk** [comment]
than isn't related to nestjs at all.

We can close this.

Reload your IDE and you'll be fine, I guess.

Or maybe you've reach a known limitation of VSC: https://github.com/microsoft/vscode/issues/3772

**Comment by tylerjusfly** [comment]
oh no , thank you
