### ISSUE TITLE
nest add mo module-name.postfix

### ISSUE THREAD

**Issue by nickerlan** [nestjs/nest-cli#1813]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

When I try to add entity with name containing dot `nest add mo module-name.postfix`, it creates valid filename (`module-name.postfix.module.ts`) but generates invalid class name `ModuleName.Postfix`

### Describe the solution you'd like

Remove dot from generated class name and generate class `ModuleNamePostfix`

### What is the motivation / use case for changing the behavior?

For better code structure I distinguish different module types (e.g. i use different module names for Repos and Features)

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
