### ISSUE TITLE
On build, not all the assets configured are copied.

### ISSUE THREAD

**Issue by greg-md** [nestjs/nest-cli#1828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When you want to copy a big amount of assets on build, not all the files are copied to dist folder.

```
{
  "$schema": "https://json.schemastore.org/nest-cli",
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "assets": [
      {
        "include": "**/*.{js,css,ejs,html,json,less,png,svg,twig}",
        "watchAssets": true
      }
    ]
  }
}
```

The problem is because the assets manager kills the process after 1 second. See: https://github.com/nestjs/nest-cli/blob/master/lib/compiler/assets-manager.ts#L26

### Minimum reproduction code

https://github.com/nestjs/nest-cli/blob/master/lib/compiler/assets-manager.ts#L26

### Steps to reproduce

Try to copy a big amout of files, which would take more than 1 second and run `nest build`.

### Expected behavior

It should copy all the files provided in the assets.

### Package version

9.1.5

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

Setting a timeout before stopping the watcher will not work. There should be found other ways of doing it.

I see that chokidar have a `ready` event for when it completes the first scan, which could be used in non watching mode.
```
.on('ready', () => log('Initial scan complete. Ready for changes'))
```

So the fix would be like:
```
.on('ready', () => !isWatchEnabled && watcher.close())
```

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by greg-md** [comment]
@kamilmysliwiec Done. https://github.com/nestjs/nest-cli/pull/1829

**Comment by greg-md** [comment]
@kamilmysliwiec do you have an estimation date when this will get merged & released?

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest-cli/pull/1829

**Comment by greg-md** [comment]
@kamilmysliwiec how about this issue? Is it going to be fixed properly?

**Comment by e-boudhina** [comment]
I am still having this issue:
    "email": {
      "type": "application",
      "root": "apps/email",
      "entryFile": "main",
      "sourceRoot": "apps/email/src",
      "compilerOptions": {
        "tsConfigPath": "apps/email/tsconfig.app.json",
        "assets": [
          {
            "include": "x/**/*",
            "outDir": "dist/apps/email/src",
            "watchAssets": true # without the variable set to true nothing gets copied why?
          }
        ]
      }
    },
