### ISSUE TITLE
Error  The "@nestjs/swagger" plugin is not compatible with Nest CLI. Neither "after()" nor "before()" nor "afterDeclarations()" function have been provided.

### ISSUE THREAD

**Issue by ricardodantas** [nestjs/nest-cli#1836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using `pnpm` within the Docker image, I am getting this error:

```
Error  The "@nestjs/swagger" plugin is not compatible with Nest CLI. Neither "after()" nor "before()" nor "afterDeclarations()" function have been provided.
```
This problem was also mentioned here https://github.com/nestjs/nest/issues/9650 by @piosystems.

**SOLUTION:** Once I removed the `compilerOptions` from the `nest-cli.json` file, I got it working.

### Minimum reproduction code

it is a private repo

### Steps to reproduce

```Dockerfile

# ...
RUN pnpm fetch
RUN pnpm install -r --frozen-lockfile --offline --filter '...'
RUN pnpm --filter '...' build
#...
```

### Expected behavior

Build the nestjs application using Docker and PNPM

### Package version

9.0.0

### NestJS version

9.0.11

### Node.js version

16.18

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

**Comment by kerryChen95** [comment]
I found the reason by adding the line 24, the error message told me that missing the package `typescript`, so I just moved `typescript` from `devDependencies` to `dependencies` and the error was resolved for me.

You can print the error message by yourself to debugging this error.

![image](https://user-images.githubusercontent.com/1589388/221498900-2e395a4f-87b5-4cc5-8e3e-1a8739bc65d9.png)

```
# Dockerfile
RUN pnpm fetch --prod
RUN pnpm install -r --offline --prod
RUN pnpm run build
```

**Comment by jsonchou** [comment]
Mark
``` js
just move typescript from devDependencies to dependencies
```
