### ISSUE TITLE
Cannot create new project

### ISSUE THREAD

**Issue by RonAlmog** [nestjs/nest-cli#1837]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

latest version of nest installed globally, 9.1.5, node version is v18.9.0.   windows 11.
nest new myproject
result is:
Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID

Failed to execute command: node @nestjs/schematics:application --name=myproject --directory=undefined --no-dry-run --no-skip-git --no-strict --package-manager=undefined --collection="@nestjs/schematics" --language="ts"

### Minimum reproduction code

nestjs.org

### Steps to reproduce

nest new myproject

### Expected behavior

new project created

### Package version

9.1.5

### NestJS version

9.1.5

### Node.js version

18.9.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

⚡  We will scaffold your app in a few seconds..

Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID

Failed to execute command: node @nestjs/schematics:application --name=myproject --directory=undefined --no-dry-run --no-skip-git --no-strict --package-manager=undefined --collection="@nestjs/schematics" --language="ts"

**Comment by RonAlmog** [comment]
i'm on windows 11. same results on plain cmd window, and Cmdr, which is a fancy terminal.

**Comment by RonAlmog** [comment]
reverting to older node version, 16.3, same result :(

**Comment by jmcdo29** [comment]
This is most likely due to an old install of `@nestjs/schematics`. The angular devkit that gets used under the hood was updated and no longer supports `id`. 

Here are some old issues around the same:

https://github.com/nestjs/nest-cli/issues/1573
https://github.com/nestjs/nest-cli/issues/1448
https://github.com/nestjs/nest/issues/9516

**Comment by micalevisk** [comment]
@RonAlmog have you tried `npx @nestjs/cli@latest new` instead of `nest new`?

**Comment by RonAlmog** [comment]
ok, so I followed #1573 and it solved the issue. remainders from older installation. reinstalling the latest @nestjs/core solved the issue. thanks everyone!
