### ISSUE TITLE
nest g class  -> the directory is mistake

### ISSUE THREAD

**Issue by qs-coder** [nestjs/nest-cli#1838]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

 nest g class demo/dto/create-demo.dto --no-spec

<img width="362" alt="image" src="https://user-images.githubusercontent.com/116894423/204992823-7fd2d38b-a2c0-4a2e-b759-2eabc83b5735.png">

### Minimum reproduction code

 nest g class demo/dto/create-demo.dto --no-spec

_No response_

### Expected behavior

 <img width="381" alt="image" src="https://user-images.githubusercontent.com/116894423/204993155-827f2e19-fa19-4225-b8ff-6bacbf11c62f.png">

### Package version

9.1.5

### NestJS version

9.2.1

### Node.js version

16.16.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
