### ISSUE TITLE
Allow to pass the base directory for generate command in nest-cli.json

### ISSUE THREAD

**Issue by devule** [nestjs/nest-cli#1849]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

When modules are in a separate directory e.g. `src/modules` (`src/modules/app/app.module.ts`), the generate commands become longer: `nest g mo modules/auth && nest g s modules/auth && nest g co modules/auth`
Also, it is a problem for it to import newly created files into app module if it is nested

### Describe the solution you'd like

add an option to nest-cli.json:
```json
{
  "generateOptions": {
    "baseDir": "modules"
  }
}
```
so new files will be created related to that directory and correctly imported into app module

### What is the motivation / use case for changing the behavior?

`nest g mo auth` instead of `nest g mo modules/auth` and so on

**Comment by devule** [comment]
i'd like to create a pull request for this if the feature is approved

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest-cli/pull/2087
