### ISSUE TITLE
cli can`t build anymore

### ISSUE THREAD

**Issue by pharindoko** [nestjs/nest-cli#1865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

using 9.1.7 when I run

```
npm run build or nest build
```
the process doesn´t end. 
Recognized it when CI / CD got stuck.

Build process runs as expected when v 9.1.5 is used.

### Minimum reproduction code

https://github.com/kelseyhightower/nocode

### Steps to reproduce

1. `npm i`
2. `npm i -D @nestjs/cli@latest`
3. `nest build`

### Expected behavior

build process ends as expected.

### Package version

9.1.7

### NestJS version

9

### Node.js version

v14.19.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

nest cli config

```json
{
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "assets": [
      "shared/mail/templates/**",
      {
        "include": "../views",
        "outDir": "dist/views",
        "watchAssets": true
      }
    ],
    "watchAssets": true,
    "plugins": [
      {
        "name": "@nestjs/swagger",
        "options": {
          "classValidatorShim": true,
          "introspectComments": true
        }
      }
    ]
  }
}

```

**Comment by pharindoko** [comment]
ok fine - recognized it works if nest-cli.json is an empty object...
```json
{
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {}
   
}
```

**Comment by pharindoko** [comment]
Ok I narrowed it down to the assets part in the compilerOptions

```json
{
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "assets": [
      "shared/mail/templates/**",
      {
        "include": "../views",
        "outDir": "dist/views",
        "watchAssets": true
      }
    ]
  }
}
```

and it doesn`t matter which asset I keep in the array - fails with both options...



using ```nest build --watch``` compiles correctly

```
[12:12:11 PM] Starting compilation in watch mode...

[12:12:22 PM] Found 0 errors. Watching for file changes.

```

**Comment by micalevisk** [comment]
I guess this has something to do with your project's file structure + assets.

Hard to tell without a reproduction project.

**Comment by piotar** [comment]
I have the same problem

`nest build` won't work properly.

The `watchAssets` option set to `true` in `compilerOptions` are blocking the project build. (watching mode was `on` ? in build ?)

The problem occurs after updating `@nestjs/cli` to version `9.1.7`.

**Comment by micalevisk** [comment]
@piotar so you didn't change anything other upgrading `@nestjs/cli`? also, can you share the output of `npx nest info`

**Comment by piotar** [comment]
I just updated `@nestjs/cli` form `"9.1.5` to `"9.1.7` and `@nestjs/axios` from `1.0.0` to `1.0.1`

`npx nest info`

```
[System Information]
OS Version     : macOS
NodeJS Version : v18.12.1
NPM Version    : 8.19.2 

[Nest CLI]
Nest CLI Version : 9.1.7 

[Nest Platform Information]
platform-express version : 9.2.1
swagger version          : 6.1.4
testing version          : 9.2.1
common version           : 9.2.1
axios version            : 1.0.1
core version             : 9.2.1
cli version              : 9.1.7
```

**Comment by micalevisk** [comment]
this could be related with fee2571c0b4000

**Comment by kamilmysliwiec** [comment]
Reverted in 9.1.8

**Comment by hsycc** [comment]
This problem still exists in version 9.2.0.

**Comment by natoszme** [comment]
Hi there! Same thing happening here: sometimes in my deploys in aws beanstalk, the assets folder is missing in one of the instances. Never happened in my local environment, so could not reproduce it yet.
But it did happen several times since I started using nest :(

Nest version: 9.2.0
Node version: 14.18.0
