### ISSUE TITLE
use any name contain '_' to create a new app will failure

### ISSUE THREAD

**Issue by gylove1994** [nestjs/nest-cli#1870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```
nest new login_                                    
⚡  We will scaffold your app in a few seconds..

? Which package manager would you ❤️  to use? yarn
CREATE login-/.eslintrc.js (631 bytes)
CREATE login-/.prettierrc (51 bytes)
CREATE login-/README.md (3346 bytes)
CREATE login-/nest-cli.json (64 bytes)
CREATE login-/package.json (1995 bytes)
CREATE login-/tsconfig.build.json (97 bytes)
CREATE login-/tsconfig.json (546 bytes)
CREATE login-/src/app.controller.spec.ts (617 bytes)
CREATE login-/src/app.controller.ts (274 bytes)
CREATE login-/src/app.module.ts (249 bytes)
CREATE login-/src/app.service.ts (142 bytes)
CREATE login-/src/main.ts (208 bytes)
CREATE login-/test/app.e2e-spec.ts (630 bytes)
CREATE login-/test/jest-e2e.json (183 bytes)

▹▹▹▹▹ Installation in progress... ☕node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: spawn /bin/sh ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /bin/sh',
  path: '/bin/sh',
  spawnargs: [ '-c', 'yarn install --silent' ]
}

Node.js v18.12.1
```

### Minimum reproduction code

https://gist.github.com/gylove1994/3f3ffaba8467f2beac7a9fe16f030c2d

### Steps to reproduce

1. nest new _

### Expected behavior

Successfully created project

### Package version

9.1.8

### NestJS version

8.4.7

### Node.js version

v18.12.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

[System Information]
OS Version     :  macOS 13.0(m1 chip)

**Comment by micalevisk** [comment]
I didn't manage to reproduce this on Linux

![image](https://user-images.githubusercontent.com/13461315/210183329-4f77edef-65f7-46f1-9839-e655b8ae991b.png)


Can you please try that out with `npx @nestjs/cli@latest new` instead? _looks_ like you're using an old version of the CLI :thinking:  that's why I don't recommend installing `@nestjs/cli` globally btw.

**Comment by gylove1994** [comment]
> I didn't manage to reproduce this on Linux
> 
> ![image](https://user-images.githubusercontent.com/13461315/210183329-4f77edef-65f7-46f1-9839-e655b8ae991b.png)
> 
> Can you please try that out with `npx @nestjs/cli@latest new` instead? _looks_ like you're using an old version of the CLI 🤔 that's why I don't recommend installing `@nestjs/cli` globally btw.

Thanks for your reply!

`npx @nestjs/cli@latest new` seems fine to me.

But I can't understand why I reinstall nestjs/cli to the latest(9.1.8) globally, it still got the same problem.

**Comment by micalevisk** [comment]
run `nest -v` and `npx nest -v` in your newly created project. I don't think you're using the latest one

**Comment by gylove1994** [comment]
> 

<img width="764" alt="image" src="https://user-images.githubusercontent.com/47300853/210183714-a8d2879f-fe88-41be-84a3-950cdd7c9519.png">

**Comment by micalevisk** [comment]
now run `nest -v` outside of any nestjs project.

**Comment by gylove1994** [comment]
> 

<img width="719" alt="image" src="https://user-images.githubusercontent.com/47300853/210183801-8e685ff4-5d50-4433-b3da-a3079962e7de.png">

**Comment by micalevisk** [comment]
I still didn't manage to reproduce that issue with `npm i -g @nestjs/cli`

![image](https://user-images.githubusercontent.com/13461315/210183859-ac45a8d4-0c74-4eec-baa8-4ea5c23f9d5d.png)

somehow you ends up using an old version of the CLI...

**Comment by gylove1994** [comment]
I am using the yarn to install @nestjs/cli globally now.
May be caused by this?
I will try to use npm to do it again.

**Comment by micalevisk** [comment]
`yarn global list` and `npm ls -g --depth=0` to list all globally installed ones. See which version you got for `@nestjs/cli`

**Comment by gylove1994** [comment]
<img width="365" alt="image" src="https://user-images.githubusercontent.com/47300853/210184116-781b47b4-3ae1-4e0d-83d7-73bcff2b0d89.png">

<img width="463" alt="image" src="https://user-images.githubusercontent.com/47300853/210184135-229a5edd-3b8a-40ad-82e3-ca6e9ba8987b.png">

Seem still show the latest one.

**Comment by micalevisk** [comment]
`yarn global remove @nestjs/cli` and `npm i -g @nestjs/cli`

then run `nest new login_` again

**Comment by gylove1994** [comment]
`npm i -g @nestjs/cli@latest` working fine.

When I try to reinstall it by yarn it happens again.

Seem is the yarn problem?

**Comment by micalevisk** [comment]
The real issue is that the yarn version somehow is using an old version. Thus, there's nothing to change in `@nestjs/cli`.

**Comment by gylove1994** [comment]
Thanks for your help! @micalevisk 

I will close the issue.
