### ISSUE TITLE
Build failed in watch mode

### ISSUE THREAD

**Issue by zanminkian** [nestjs/nest-cli#1878]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Build failed in watch mode. But it will be success without watch mode.

### Minimum reproduction code

https://github.com/ZanMinKian/nestcli-bug-in-watch-mode

### Steps to reproduce

1. pnpm v7 and node v16
2. run `pnpm i`
3. run `pnpm nest build -w` will be fail (which should not be)
4. but run `pnpm nest build` will be success

### Expected behavior

1. pnpm v7 and node v16
2. run `pnpm i`
3. run `pnpm nest build -w` should be success
4. run `pnpm nest build` should be success

### Package version

9.1.8

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest-cli/pull/1879
