### ISSUE TITLE
Peer Dep ERR on node v14

### ISSUE THREAD

**Issue by ushiii111798** [nestjs/nest-cli#1890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When install @nestjs/cli(v9.1.8) on node v14, it shows peer dep missing error on ajv@^6.9.1 (required by ajv-keywords@3.5.2)

### Minimum reproduction code

npm i -g @nestjs/cli

### Steps to reproduce

npm i -g @nestjs/cli

### Expected behavior

no error while installing @nestjs/cli package
all dependency need to be installed currectly

### Package version

9.1.8

### NestJS version

none (due to installed global)

### Node.js version

14.21.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
