### ISSUE TITLE
[DISCUSSION] - Keep up

### ISSUE THREAD

**Issue by sandorvasas** [nestjs/nest-cli#19]
Hi,

I just found out about Nest.js today and am excited about it! Having a background in C/C++, Java Spring MVC and Node.js, it seems fantastic to have the bests of all areas. 

Are you still working on the CLI? I see the latest commits are 2-4 months old and serve/build is not implemented. I think this project is about to explode in popularity especially if it has such a great scaffolding/generating mechanism like the angular-cli.

Are you planning to integrate GraphQL support to the CLI - and to the core of Nest.js?

Looking forward to further advancements, seems really promising at first glance! Can't wait to have some free hours to try.

**Comment by ThomRick** [comment]
Hey @sandorvasas !

Thanks a lot for your interest about Nest ! 

I'm still working on the CLI but I had no time last weeks / months to develop on it. 
I try to organize my time to continue feature developments.
I'm currently in a refactoring phase to have a better code base and continuous integration to help contributors to develop on the project.

About GraphQL it's not yet in the roadmap but your feedback help us to add feature enhancement in the current project.

In an other way if you want to contribute to project (feature / bug fix / enhancement) to hesitate.
That's the purpose of the open source ;-)

I've just add the trello link to the roadmap but I think about create issues to be attached to pull requests for contributors.

**Comment by wbhob** [comment]
@ThomRick In terms of Nest style guide, I'd love to have a conversation with you and/or @kamilmysliwiec in regards to refactoring the "preferred" structure of a Nest project. Right now, it strongly deviates from that of Angular and that could cause issues for people trying to adapt to the framework. (for example, a modules folder is unnecessary, since everything is, by definition, a module. Things that are core app functionality should be in a `core` module, not a `common` module, and other nomenclature things like that.)

**Comment by ThomRick** [comment]
Hey @wbhob !
Sur it could be great to discuss about the Nest project structure.
Don't hesitate to go on Gitter:
https://gitter.im/nestjs/nestjs
https://gitter.im/nestjs/nest-cli

**Comment by myflowpl** [comment]
I have one suggestion about the CLI itself
have you check out the angular-devkit/schematics ?
currently angular-cli is based on it, and it looks like really grate tool for all kind of CLI projects
here is good video introduction to it: https://youtu.be/ZKyz0lb0GjA?t=17m38s
I think it will be good idea to use common generator structure, so other developers can easly go into the nest-cli project and add/fix more features

**Comment by ThomRick** [comment]
Hey @myflowpl I'll check on it ! 
Thanks a lot for the link !

**Comment by ThomRick** [comment]
CONTRIBUTE.md on branch nest-v4 and nest-v5
Will be merged to master for current production code
