### ISSUE TITLE
nest generate doesn't work for me after upgrading to 9.2.0

### ISSUE THREAD

**Issue by elmogallen** [nestjs/nest-cli#1914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I tried upgrading @nestjs/cli to 9.2.0, then tried `nest g module something` and it didn't do anything. No error. It just exited and returned to the prompt with no output. I saw somewhere to update @nestjs/schematics to the latest version, so I tried updating that to 9.0.4, and it still didn't work. 

I then downgraded @nestjs/cli to 9.1.9 and tried `nest g module something` again, and this time it worked.

Any idea why that would be?

### Minimum reproduction code

n/a

### Steps to reproduce

1. Install @nestjs/cli 9.2.0
2. Try to generate a resource like `nest g module something`

### Expected behavior

I expected it to create the resource, but it didn't do anything. And it gave me no output.

### Package version

9.2.0

### NestJS version

9.3.2

### Node.js version

16.18.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Everything looks working fine to me
![image](https://user-images.githubusercontent.com/28268680/216709057-79ec7bf8-fac2-4a1d-a023-b222865f5056.png)

**Comment by Lindennerd** [comment]
I'm getting the same error, both in a Windows and a Ubuntu machine

**Comment by AgrYpn1a** [comment]
Same happens to me on Mac, any updates?

**Comment by jmcdo29** [comment]
Can somebody please provide a minimum reproduction? As I showed in my screenshot above, 9.2.0's `generate` command _can_ work fine. So we need context as to _when_ it doesn't. 

Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by jmcdo29** [comment]
@AgrYpn1a do you use `nest g` directly, or `npm/pnpm/yarn nest g` to use the local version?

**Comment by AgrYpn1a** [comment]
@jmcdo29 I've used `nest g` directly

**Comment by elmogallen** [comment]
Me too. Nest g directlyDaveOn Feb 4, 2023, at 4:04 PM, Rastko Tojagic ***@***.***> wrote:﻿
@jmcdo29 I've used nest g directly

**Comment by jmcdo29** [comment]
So it sounds like an issue with the global commandat 9.1.9 vs the local at 9.2.0 (maybe not even related to the local command, just the Nest version)

Can someone _please_ provide a repository where this is giving them issues?

**Comment by sfase3** [comment]
I have the same problem. Trying to generate a module or controller, and it doesn't do anything, just returning for next commands

**Comment by faithfulojebiyi** [comment]
I have have same issues nestjs cli does not work

**Comment by AgrYpn1a** [comment]
@jmcdo29 I think to reproduce it is enough to have an empty repository with local nestjs cli version `9.2.0` and a global version `9.1.9` it could maybe be that the version mismatch is the cause, but not sure.

**Comment by faithfulojebiyi** [comment]
@AgrYpn1a Yes it is. I was able to figure that out after running several tests on my local machine. After updating but global and local with matching versions it started working fine.

**Comment by kamilmysliwiec** [comment]
So it sounds like you just have to make sure the globally installed version == local version. I'm assuming this might be related to the recent upgrade of the underlying Angular devkit schematics package and so there's not much we can do on our side

**Comment by RezaNorm** [comment]
> .

running the command fixed it

**Comment by RezaNorm** [comment]
> Ah, so the globally installed nestjs CLI version takes precedence. I, also, did `npm i -g @nestjs/cli` and it works now.
> 
> Thanks for the help.
running the command fixed it.

**Comment by Andynopol** [comment]
Install the cli globally and remove the one from devDependencies. Resintall the node_modules and it should work. It worked for me. I don't know why locally it's not working. And it happends only on bash. On other terminals like zsh(on mac) it works without any problems.

**Comment by faithfulojebiyi** [comment]
You just have to make sure the local and global are the same version.
