### ISSUE TITLE
Cli just use npm to install dependencies when generate first resource Crud with endpoint although i use yarn or pnpm

### ISSUE THREAD

**Issue by luantran2k** [nestjs/nest-cli#1923]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![image](https://user-images.githubusercontent.com/75030293/217442825-f0926826-bc79-4d65-9e1d-f8650596aa50.png)
When i use yarn, it generate successfully. But in use npm to install so that package-log.json appear

![image](https://user-images.githubusercontent.com/75030293/217443033-b349ec0a-1866-4282-9bb8-8e720beb7026.png)
When i use pnpm, it error

### Minimum reproduction code

Empty

### Steps to reproduce

nest new test-pnpm
nest g res products

### Expected behavior

It use pnpm or yarn to install dependecies when generate 

### Package version

9.2.0

### NestJS version

9.3.5

### Node.js version

19.5.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
