### ISSUE TITLE
Failed to execute command: node @nestjs/schematics:application --name=my-first-project --directory=undefined --no-dry-run --no-skip-git --no-strict --package-manager="npm" --collection="@nestjs/schematics" --language="ts"

### ISSUE THREAD

**Issue by juzarantri** [nestjs/nest-cli#1954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am trying to create a nest app but it gives me the error

### Minimum reproduction code

https://github.com/juzarantri/creole

### Steps to reproduce

nest new my-first-project

### Expected behavior

I expect that my first app should be created and run successfully.

### Package version

9.2.0

### NestJS version

9.2.0

### Node.js version

14.17.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

<img width="960" alt="image" src="https://user-images.githubusercontent.com/82743796/222641997-97a3ce46-68fc-43d9-9b23-5dcf3ff99e44.png">
`Please help me resolve this issue`

**Comment by viveksinh007** [comment]
update the node version to the latest version 

Tip: Use nvm to upgrade the node version and change node versions anytime

**Comment by juzarantri** [comment]
yes this worked for me
