### ISSUE TITLE
webpack version needs bump - npm audit

### ISSUE THREAD

**Issue by ssipos90** [nestjs/nest-cli#1976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

There's an audit issue reported by npm:
```
$ npm audit
# npm audit report

webpack  5.0.0 - 5.75.0
Severity: high
Cross-realm object access in Webpack 5 - https://github.com/advisories/GHSA-hc6q-2mpp-qw7j
fix available via `npm audit fix --force`
Will install @nestjs/cli@7.5.1, which is a breaking change
node_modules/@nestjs/cli/node_modules/webpack
  @nestjs/cli  7.5.1-next.1 || >=7.5.2-next.2
  Depends on vulnerable versions of webpack
  node_modules/@nestjs/cli

2 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
```
Running
```bash
$ npm ls webpack
xxxx@0.0.1 /home/xxx/xxxx
├─┬ @nestjs/cli@9.2.0
│ ├─┬ fork-ts-checker-webpack-plugin@7.3.0
│ │ └── webpack@5.76.1 deduped
│ └─┬ webpack@5.75.0  # <=== this seems to be the culprit.
│   └─┬ terser-webpack-plugin@5.3.7
│     └── webpack@5.76.1 deduped
└─┬ ts-loader@9.4.2
  └── webpack@5.76.1
```

### Minimum reproduction code

-

### Steps to reproduce

`npm audit` in a newly created project.

### Expected behavior

No audit warnings/errors in audit.

### Package version

9.2.0

### NestJS version

9.3.9

### Node.js version

18.14

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
hi! thanks for reporting

We are aware of this thanks to Renovate bot (and Dependa bot):

- #1974
- #1975

**Comment by tolgap** [comment]
@micalevisk but why is it recommending to install `@nestjs/cli@7.5.1` as a potential fix? That's the strange part 😄

**Comment by tan-dd** [comment]
Any ETA for this update in the package?
![image](https://user-images.githubusercontent.com/47315850/225230176-915ef664-3a6a-4b38-9205-aaa73ffd32c7.png)

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest-cli/pull/1975
