### ISSUE TITLE
Less strict dependency versions for quick patch updates of dependencies

### ISSUE THREAD

**Issue by w3nl** [nestjs/nest-cli#1977]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Like the Webpack issue: https://github.com/advisories/GHSA-hc6q-2mpp-qw7j
We have to wait on Nest to release a new version: https://github.com/nestjs/nest-cli/issues/1976

### Describe the solution you'd like

If you use ^ for all dependencies, we dont have to wait on Nest to release a version with the latest Webpack patch.
See also semver: https://github.com/npm/node-semver#caret-ranges-123-025-004
And npm: https://docs.npmjs.com/cli/v9/configuring-npm/package-json#dependencies

### What is the motivation / use case for changing the behavior?

It can speed up hotfix releases of dependencies (of dependencies) with security fixes.
We don't have to wait hours till some packages will release a new version with the updated dependency with security fixes.
And Nest doesn't need to release a new version for a security issue of a dependency.

**Comment by jmcdo29** [comment]
We've used `^` in the past, and when downstream dependencies accidentally publish breaking or incompatible changes, we end up getting **several** issues about it when there's nothing we can do but pin the dependencies. It's a double edge sword either way.

**Comment by w3nl** [comment]
I understand the issue, and indeed you can receive some issues if dependencies accidentally break it and come to you.
In the NPM world we have a lot of small packages, and your node_modules folder will be large in most cases if you use e.g. a large framework like Nest.
So we always have a lot of dependency updates, and we want to keep them up-to-date, and quick fix security issues.
Personally I think users have more benefits on quick fixes then some pointing fingers if a dependency makes a mistake and point the finger on to wrong package.

We also have today package lock files to keep the current version if you want to stay in a version (like for deployments)

But I realize also if you start with Nest on the wrong time (with a breaking change of a dependency), and you are a starting (JS) developer, it can be hard to get started.

If a dependency does break often, you can keep it more strict for these dependencies or look for another solution/dependency.
If you trust dependencies, I think you help a lot a users with the `^`.

But that's my opinion.

**Comment by pieter-pon** [comment]
I found it when you pin it to strict dependency versions: https://github.com/nestjs/nest-cli/pull/235

**Comment by w3nl** [comment]
I found it when you pin it to strict dependency versions: https://github.com/nestjs/nest-cli/pull/235

**Comment by jaonoctus** [comment]
nACK

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest-cli/issues/1977#issuecomment-1468783469
