### ISSUE TITLE
Bump webpack version to 5.76.0

### ISSUE THREAD

**Issue by toppermitz** [nestjs/nest-cli#1983]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Version 9.2.0 use webpack version 5.75.0, this version has a vulnerability `Cross-realm object access in Webpack 5` [see](https://github.com/advisories/GHSA-hc6q-2mpp-qw7j)

### Describe the solution you'd like

Bump version of webpack to 5.76.0

### What is the motivation / use case for changing the behavior?

Only for security reasons

**Comment by kamilmysliwiec** [comment]
![Uploading image.png…]()
