### ISSUE TITLE
Failed to execute command

### ISSUE THREAD

**Issue by MontassarHammouda** [nestjs/nest-cli#1987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Failed to execute command: node @nestjs/schematics:resource --name=user --no-dry-run --project="pnpm" --no-skip-import --language="ts" --source-root="src" --spec --no-flat

### Minimum reproduction code

Na

### Steps to reproduce

nest g res user -p pnpm
? What transport layer do you use? REST API
? Would you like to generate CRUD entry points? Yes
CREATE src/user/user.controller.spec.ts (556 bytes)
CREATE src/user/user.controller.ts (883 bytes)
CREATE src/user/user.module.ts (240 bytes)
CREATE src/user/user.service.spec.ts (446 bytes)
CREATE src/user/user.service.ts (607 bytes)
CREATE src/user/dto/create-user.dto.ts (30 bytes)
CREATE src/user/dto/update-user.dto.ts (169 bytes)
CREATE src/user/entities/user.entity.ts (21 bytes)
UPDATE package.json (1981 bytes)
UPDATE src/app.module.ts (308 bytes)
⠦ Installing packages (npm)...npm ERR! Cannot read properties of null (reading 'matches')

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/montasar/.npm/_logs/2023-03-17T11_24_14_687Z-debug-0.log
✖ Package install failed, see above.
The Schematic workflow failed. See above.

Failed to execute command: node @nestjs/schematics:resource --name=user --no-dry-run --project="pnpm" --no-skip-import --language="ts" --source-root="src" --spec --no-flat

### Expected behavior

nest g res user -p pnpm
? What transport layer do you use? REST API
? Would you like to generate CRUD entry points? Yes
CREATE src/user/user.controller.spec.ts (556 bytes)
CREATE src/user/user.controller.ts (883 bytes)
CREATE src/user/user.module.ts (240 bytes)
CREATE src/user/user.service.spec.ts (446 bytes)
CREATE src/user/user.service.ts (607 bytes)
CREATE src/user/dto/create-user.dto.ts (30 bytes)
CREATE src/user/dto/update-user.dto.ts (169 bytes)
CREATE src/user/entities/user.entity.ts (21 bytes)
UPDATE package.json (1981 bytes)
UPDATE src/app.module.ts (308 bytes)
⠦ Installing packages (npm)...npm ERR! Cannot read properties of null (reading 'matches')

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/montasar/.npm/_logs/2023-03-17T11_24_14_687Z-debug-0.log
✖ Package install failed, see above.
The Schematic workflow failed. See above.

### Package version

9.0.0

### NestJS version

9.0.0

### Node.js version

18.14.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
#1910
