### ISSUE TITLE
`npm run build` does not produce the webpack file cache

### ISSUE THREAD

**Issue by hkjeffchan** [nestjs/nest-cli#1995]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

https://github.com/webpack/webpack/issues/12345

compiler.close() should be called somewhere.
I tried to fix it by calling compiler.close() in lib/compiler/webpack-compiler.ts but it does now work

### Minimum reproduction code

https://github.com/hkjeffchan/nestjsCliWebpackCacheDemo

### Steps to reproduce

1. `npm run build` does not produce the webpack file cache
2. `npm run start:dev` does produce the webpack file cache

### Expected behavior

`npm run build` should produce the webpack file cache

### Package version

9.3.0

### NestJS version

9.3.11

### Node.js version

18.15.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by hkjeffchan** [comment]
I tried to modify lib/compiler/webpack-compiler.ts and add this before `compiler.run(afterCallback);`

```
            compiler.hooks.shutdown.tap('shutdown', () => {
              console.log('shutdown');
              compiler.close(); 
            });
```
This does not work as this is not called.

```
            compiler.hooks.done.tap('done', () => {
              console.log('done');
              compiler.close(); 
            });
```
This does create the cache directory and it said "webpack 5.76.2 compiled successfully" but i got the following errors:

```
/Applications/MAMP/htdocs/nest-playground/node_modules/webpack/lib/HookWebpackError.js:68
                callback(null, result);
                ^

TypeError: callback is not a function
    at /Applications/MAMP/htdocs/nest-playground/node_modules/webpack/lib/HookWebpackError.js:68:3
    at _done (eval at create (/Applications/MAMP/htdocs/nest-playground/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (/Applications/MAMP/htdocs/nest-playground/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:22)
```

**Comment by hkjeffchan** [comment]
I fixed it... a callback function is required for compiler.close()

created a PR for this

**Comment by hkjeffchan** [comment]
https://github.com/nestjs/nest-cli/pull/1997

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest-cli/pull/1997
