### ISSUE TITLE
Using --entryFile flag with webpack doesn't work

### ISSUE THREAD

**Issue by mentos1386** [nestjs/nest-cli#2039]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using `--entryFile` with `nest start` command to specify different file to run (`repl.ts` for example) doesn't work as intended when using `webpack` instead of `tsc`.

When using custom `webpack.config.js` in following manner to diagnose the issue:
```js
module.exports = options => {
  console.log(options.output.filename);
  console.log(options.entry);
  return options;
}
```

We get the following output:
```js
> nest start graphql --entryFile generate

apps/graphql/main.js
/workspace/apps/graphql/src/main.ts

webpack 5.79.0 compiled successfully in 1323 ms
Error: Cannot find module '/workspace/dist/apps/graphql/generate'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1021:15)
    at Function.Module._load (node:internal/modules/cjs/loader:866:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47
```

Which indicates that `--entryFile` has no affect on webpack and it continues to compile the `main.ts` which is defined in `nest-cli.json` as `entryFile`.

Using `nest start --tsc --entryFile repl` works as intended.

### Minimum reproduction code

https://github.com/mentos1386/nest-cli-entryfile-repro

### Steps to reproduce

1. `npm i`
2. `npx nest start --entryFile repl`

### Expected behavior

`repl.ts` should be compiled and started.

### Package version

9.4.0

### NestJS version

9.4.0

### Node.js version

16

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

Relates to #1691

**Comment by mentos1386** [comment]
Workarround that we are using is:

In `package.json`
```json
    "repl": "ENTRY_FILE=repl nest start graphql --watch --entryFile repl"
```

In `webpack.config.js`
```js
const path = require('node:path');

module.exports = options => {
  const entryFile = process.env.ENTRY_FILE;
  const outputDir = path.dirname(options.output.filename);
  const sourceDir = path.dirname(options.entry);

  const getSourceFile = () => {
    if (entryFile) return `${sourceDir}/${entryFile}.ts`;
    return options.entry;
  };

  const getOutputFile = () => {
    if (entryFile) return `${outputDir}/${entryFile}.js`;
    return options.output.filename;
  };

  return {
    ...options,
    entry: getSourceFile(),
    output: {
      ...options.output,
      filename: getOutputFile(),
    },
  };
};
```

**Comment by micalevisk** [comment]
Hi! Would you like to create a Pull Request to fix that?

**Comment by mentos1386** [comment]
I was looking at the code and i couldn't easily figure out what's going on :(

**Comment by micalevisk** [comment]
@mentos1386 I guess that is due to this:

https://github.com/nestjs/nest-cli/blob/86e5e5e7a0bc3f0e20238e89257fef5eb073e57e/lib/compiler/webpack-compiler.ts#L60-L64

https://github.com/nestjs/nest-cli/blob/86e5e5e7a0bc3f0e20238e89257fef5eb073e57e/lib/compiler/helpers/get-value-or-default.ts#L4

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest-cli/pull/2043
