### ISSUE TITLE
tsc is expected to support custom arguments at start or build, especially the --build argument

### ISSUE THREAD

**Issue by yuntian001** [nestjs/nest-cli#2072]
### Is there an existing issue that is already proposing this?

- [ ] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I want to use typescript's Project References feature but the compile option does not support --build

### Describe the solution you'd like

tsc is expected to support custom arguments at start or build, especially the --build argument

### What is the motivation / use case for changing the behavior?

I want to use typescript's Project References feature

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest-cli/issues/392
