### ISSUE TITLE
Cannot create a new project: "Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID"

### ISSUE THREAD

**Issue by rixcian** [nestjs/nest-cli#2073]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am trying to create a new nest application but it gives me this error:

```
Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID

Failed to execute command: node @nestjs/schematics:application --name=test-project --directory=undefined --no-dry-run --no-skip-git --no-strict --package-manager="yarn" --collection="@nestjs/schematics" --language="ts"
```

### Minimum reproduction code

None, because can't create one.

### Steps to reproduce

1. `nest new test-project`
2. The error occurs

### Expected behavior

Create a new Nest project

### Package version

9.4.2

### NestJS version

9.4.0

### Node.js version

16.17.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

I've followed all the instructions in this issue #1837 (uninstall and install the `@nestjs/cli` package, install the `@nestjs/core` package), but nothing helped.

btw, yarn version: 3.5.1

![image](https://github.com/nestjs/nest-cli/assets/14358496/8d06f7db-171f-44a7-a7b3-2ab9cda6821f)

**Comment by micalevisk** [comment]
Try this instead: `npx @nestjs/cli@latest new`

**Comment by rixcian** [comment]
The same result.

![image](https://github.com/nestjs/nest-cli/assets/14358496/cf9a9708-4d5a-411b-b4bf-bf292cad13c0)

**Comment by rixcian** [comment]
Yep :disappointed: 

![image](https://github.com/nestjs/nest-cli/assets/14358496/d3495633-532f-426e-9a8f-8ce6eb67729b)

**Comment by micalevisk** [comment]
uninstall the global one (`npm uninstall -g @nestjs/cli`) and use `npx` again, please

**Comment by rixcian** [comment]
Tried with `yarn` and with `npm`, the same results again.
 
![image](https://github.com/nestjs/nest-cli/assets/14358496/b64dd6b4-c365-4c7f-994a-e26323486c2e)

**Comment by micalevisk** [comment]
did you have some `node_modules` in that directory? if yes, try that command in another one like `/tmp/`

**Comment by rixcian** [comment]
No, I don't.

**Comment by kamilmysliwiec** [comment]
You must have an old version of `@nestjs/schematics` installed somewhere on your machine (global node modules I'd guess). Your CLI version uses the updated version of Angular schematics pkg that no longer supports `id` and the old schematics you have installed are still using it, that's the only reason why you're seeing this issue.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
