### ISSUE TITLE
Allow to use a web collection without install

### ISSUE THREAD

**Issue by ymoreiratiti** [nestjs/nest-cli#2094]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

We need to install this on the repo or globally to use the collection. This makes it hard to maintain the collection updated on all microservices that use the collection 

### Describe the solution you'd like

allow using collection without installing locally/globally. 

This will help to ensure that the developers are always using the latest version of the collection

### Teachability, documentation, adoption, migration strategy

Currently, we run nest CLI and receive an error if the collection is not available

```shell
$ nest -c @condoso/custom-nest-schematics g module
Error: Collection "@condoso/custom-nest-schematics" cannot be resolved.
```

My proposal: Instead of displaying an error that collection cannot be resolved, try to download this from the NPM registry. If no version is specified, download the latest. 

This will allow people to use custom collections without the need to install them locally

### What is the motivation / use case for changing the behavior?

We need to ensure that the DEV are using the latest version of the collection always and without the need to always upgrade this on all microservices that use the collection.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
