### ISSUE TITLE
[Documentation] manualRestart compiler option missing from https://json.schemastore.org/nest-cli

### ISSUE THREAD

**Issue by stefaanMLB** [nestjs/nest-cli#2109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The `manualRestart` option is indicates as "not allowed".
I checked the definition file at https://json.schemastore.org/nest-cli and found the `manualRestart` option is missing.
example `nest-cli.json` below
```json
{
  "$schema": "https://json.schemastore.org/nest-cli",
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "deleteOutDir": true,
    "manualRestart": true
  }
}
```

### Minimum reproduction code

see below

### Expected behavior

no error indication

### Package version

9.5.0

### NestJS version

9.4.2

### Node.js version

18.17.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR to the schemastore?

**Comment by stefaanMLB** [comment]
I'll give it a try, never done that before

**Comment by stefaanMLB** [comment]
Hmm, Can't even find the source that I have to adapt.
Any hints ?

**Comment by kamilmysliwiec** [comment]
You can submit a PR here https://github.com/SchemaStore/schemastore (search for `nest-cli`)
