### ISSUE TITLE
Cross-realm object access in Webpack 5

### ISSUE THREAD

**Issue by todbapi** [nestjs/nest-cli#2119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

https://github.com/nestjs/nest-cli/blob/c0cc86450b86b357c720bb05a837fcbbeaa58673/package.json#L67
https://github.com/advisories/GHSA-hc6q-2mpp-qw7j

### Minimum reproduction code

https://github.com/nestjs/nest-cli/blob/c0cc86450b86b357c720bb05a837fcbbeaa58673/package.json#L67

### Steps to reproduce

npm i

### Expected behavior

fix https://github.com/advisories/GHSA-hc6q-2mpp-qw7j

### Package version

8.0.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest-cli/pull/2118
