### ISSUE TITLE
SWC builder doesn't respect folder organization from webpack

### ISSUE THREAD

**Issue by leonard-henriquez** [nestjs/nest-cli#2123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

SWC builder doesn't respect folder organization from webpack.
Now modules are directly at the top of `dist` directory.
It breaks anything that is outside of the `src` directory (such as my test suite in the `tests` directory).

```bash
> tree -L 1 dist
dist
├── module_1
├── module_2
...
├── app.module.js
├── app.module.js.map
├── app.resolver.js
└── app.resolver.js.map
```

### Minimum reproduction code

none

### Steps to reproduce

nest-cli.json:
```json
{
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "builder": "swc",
    "plugins": []
  }
}
```

.swcrc:
```json
{
  "$schema": "https://json.schemastore.org/swcrc",
  "sourceMaps": true,
  "module": {
    "type": "commonjs"
  },
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "dynamicImport": true
    },
    "baseUrl": "./"
  },
  "minify": false
}
```

tsconfig.json:
```json
{
  "extends": "./base.json",
  "compilerOptions": {
    "target": "es2017",
    "outDir": "dist",
    "rootDir": ".",
  },
  "types": ["node", "jest"],
  "include": [
    "src/**/*.ts"
  ],
}
```

### Expected behavior

```bash
> tree -L 1 dist
dist
├── forest
└── src
```

### Package version

10.0.1

### NestJS version

10.0.0

### Node.js version

18.12.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).
