### ISSUE TITLE
Support setting SWC configuration file path

### ISSUE THREAD

**Issue by gamedevsam** [nestjs/nest-cli#2131]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Projects force me to put files in the root directory.

### Describe the solution you'd like

I always create an `infrastructure` folder and place all my configs in there. The newly released SWC compiler integration is great, but doesn't allow me to place configs wherever I like.

I'd love if we could set the SWC compiler options in `nest-cli.json` (as a `swcCompilerOptions` field possibly), or alternatively pass a compiler option to @nest/cli to configure the swc config path.

### Teachability, documentation, adoption, migration strategy

This feature should be optional.

### What is the motivation / use case for changing the behavior?

Improves flexibility and makes SWC compatibility on par with existing solutions.

**Comment by kamilmysliwiec** [comment]
I'm OK with adding the `swcConfigPath` (under `compilerOptions`) option to the `nest-cli.json`. Contributions are more than welcome if you'd like to take a stab at this issue!  

https://github.com/nestjs/nest-cli/blob/c2bc3da759e0a9d66159bb473fc884ab47dea64b/lib/compiler/swc/swc-compiler.ts#L179

**Comment by kamilmysliwiec** [comment]
```json
{
  "$schema": "https://json.schemastore.org/nest-cli",
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "deleteOutDir": true,
    "typeCheck": true,
    "builder": {
      "type": "swc",
      "options": {
        "swcrcPath": "infrastructure/.swcrc"
      }
    }
  }
}
