### ISSUE TITLE
`jsc.paths` in  .swcrc is not recognized.

### ISSUE THREAD

**Issue by yuntian001** [nestjs/nest-cli#2135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I compile with `nest start-b swc` , `jsc.paths` in  .swcrc is not recognized.
It works when I use the `swc --ignore \"**/*.spec.ts,src/hmr.ts\" --delete-dir-on-start --out-dir dist/ src/` command

### Minimum reproduction code

This is a cli error with no corresponding replicating code

### Steps to reproduce

1. create  .swc
```
{
  "$schema": "https://json.schemastore.org/swcrc",
  "sourceMaps": true,
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "dynamicImport": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "paths": {
      "@/*": ["src/*"]
    },
    "baseUrl": "./"
  },
  "minify": false
}
```
2. `npx nest start-b swc`

### Expected behavior

'@/app' in the project is escaped as a relative path

### Package version

10.0.3

### NestJS version

10.0.3

### Node.js version

16.18.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by thenglong** [comment]
same issue here

**Comment by thenglong** [comment]
I think it's related to this https://github.com/swc-project/swc/issues/2725

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

**Comment by hengkx** [comment]
Have you solved the same problem?

**Comment by hengkx** [comment]
https://github.com/fityannugroho/idn-area/pull/92
