### ISSUE TITLE
SWC builder fails to recognize dirs outside of `src/`

### ISSUE THREAD

**Issue by elijaholmos** [nestjs/nest-cli#2136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Building a nestjs app with SWC (`nest start -b swc`) results in a startup error when the source code references files outside of the `src/` dir.

```zsh
$ pnpm nest start -b swc
>  SWC  Running...
Successfully compiled: 5 files with swc (27.43ms)
Error: Cannot find module '../graphql/scalars/TestScalar'
Require stack:
- C:\nestjs-swc-missing-dir\dist\app.module.js
- C:\nestjs-swc-missing-dir\dist\app.js
- C:\nestjs-swc-missing-dir\dist\main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Function.Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\nestjs-swc-missing-dir\dist\app.module.js:15:21)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
```

### Minimum reproduction code

https://github.com/elijaholmos/nestjs-swc-missing-dir

### Steps to reproduce

1. `pnpm i`
2. `pnpm nest start`
	- Notice that the application starts successfully
3. `rm -rf dist` 
	- This is important to give the swc compilation a fresh start
4. `pnpm nest start -b swc`
	- Note the error

### Expected behavior

I expect SWC to properly include all files outside of the `src/` directory that are also referenced at runtime. 

Note the difference between the Nest `dist/` dir and the SWC `dist/` dir:
![image](https://github.com/nestjs/nest-cli/assets/35435704/90b158d7-311e-44b3-aa37-ecf21dcc8f32)

![image](https://github.com/nestjs/nest-cli/assets/35435704/79e0104b-fc5b-4706-8b89-55771e26c458)

### Package version

10.0.5

### NestJS version

10.0.3

### Node.js version

18.16.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
> I expect SWC to properly include all files outside of the src/ directory that are also referenced at runtime.

That's not how SWC works. SWC only compiles explicitly specified files/directories.

We can add a configuration option to `nest-cli.json` to customize the `filenames` passed to SWC CLI (currently hardcoded to "src")

**Comment by medz** [comment]
I think this issue can be closed, it will be supported in #2140

**Comment by elijaholmos** [comment]
Hey @medz, thank you for your hard work on this and greatly improving the nestjs SWC process.

I updated my reproduction repo at https://github.com/elijaholmos/nestjs-swc-missing-dir to contain a new `nest-cli` configuration file like the sample offered in https://github.com/nestjs/nest-cli/pull/2140#issuecomment-1614332083. I run `pnpm nest build`, and the output dir now contains any compiled JS files which are located outside of the `src/` dir 🎉

Unfortunately... SWC flattens the directory output and still doesn't properly map files like the nest compiler, which yields the original issue error. The new directory structure is as follows:
![image](https://github.com/nestjs/nest-cli/assets/35435704/3a1d5bc7-d798-4100-981b-6e4b9b23a6dc)
when it should look something akin to:
![image](https://github.com/nestjs/nest-cli/assets/35435704/effe0ec3-4df6-43d6-851e-7baacce8c217)


Do you have any suggestions or solutions for me to try to obtain the desired directory output, or is this beyond the capabilities of SWC?

**Comment by medz** [comment]
> Hey @medz, thank you for your hard work on this and greatly improving the nestjs SWC process.
> 
> I updated my reproduction repo at https://github.com/elijaholmos/nestjs-swc-missing-dir to contain a new `nest-cli` configuration file like the sample offered in [#2140 (comment)](https://github.com/nestjs/nest-cli/pull/2140#issuecomment-1614332083). I run `pnpm nest build`, and the output dir now contains any compiled JS files which are located outside of the `src/` dir 🎉
> 
> Unfortunately... SWC flattens the directory output and still doesn't properly map files like the nest compiler, which yields the original issue error. The new directory structure is as follows: ![image](https://user-images.githubusercontent.com/35435704/250170772-3a1d5bc7-d798-4100-981b-6e4b9b23a6dc.png) when it should look something akin to: ![image](https://user-images.githubusercontent.com/35435704/250171164-effe0ec3-4df6-43d6-851e-7baacce8c217.png)
> 
> Do you have any suggestions or solutions for me to try to obtain the desired directory output, or is this beyond the capabilities of SWC?

@elijaholmos 
SWC does flatten multiple input directories, this is a known issue with SWC.

I rarely use it, I think it is a wrong design to edit the source code itself in a directory other than src~

You can try the following structure:

```
src/
  - app/
      - app.modele.ts
      - ... more
  - graphql/
      - schema.graphql
      - scalars/
  - env/
  - main.ts
```

**Comment by akshaya-ananda2524** [comment]
> Hey @medz, thank you for your hard work on this and greatly improving the nestjs SWC process.
> 
> I updated my reproduction repo at https://github.com/elijaholmos/nestjs-swc-missing-dir to contain a new `nest-cli` configuration file like the sample offered in [#2140 (comment)](https://github.com/nestjs/nest-cli/pull/2140#issuecomment-1614332083). I run `pnpm nest build`, and the output dir now contains any compiled JS files which are located outside of the `src/` dir 🎉
> 
> Unfortunately... SWC flattens the directory output and still doesn't properly map files like the nest compiler, which yields the original issue error. The new directory structure is as follows: ![image](https://user-images.githubusercontent.com/35435704/250170772-3a1d5bc7-d798-4100-981b-6e4b9b23a6dc.png) when it should look something akin to: ![image](https://user-images.githubusercontent.com/35435704/250171164-effe0ec3-4df6-43d6-851e-7baacce8c217.png)
> 
> Do you have any suggestions or solutions for me to try to obtain the desired directory output, or is this beyond the capabilities of SWC?

Hi @elijaholmos , did you  find solution for this issue. I am too facing same issue.

**Comment by elijaholmos** [comment]
@akshaya-ananda2524, unfortunately I did not find a solution to the issue as it is still an open problem with the SWC project.

**Comment by akshaya-ananda2524** [comment]
> @akshaya-ananda2524, unfortunately I did not find a solution to the issue as it is still an open problem with the SWC project.

Okay Thanks @elijaholmos
