### ISSUE TITLE
SWC builder cannot customize `sourceRoot`, only allowed to be set to `src`

### ISSUE THREAD

**Issue by medz** [nestjs/nest-cli#2138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

SWC builder cannot customize `sourceRoot`, only allowed to be set to `src`

### Minimum reproduction code

No

### Steps to reproduce

custom: 

## `.swcrc`
```json
{ "jsc": { "baseUrl": "src2" }
```

## `nest-cli.json`
```json
{
    "sourceRoot": "src2"
}
```

### Expected behavior

Correctly compile the TS files under src2

### Package version

10.0.5

### NestJS version

10.0.3

### Node.js version

v20.3.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest-cli/pull/2140
