### ISSUE TITLE
SWC builder output directory is not as expected

### ISSUE THREAD

**Issue by medz** [nestjs/nest-cli#2139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

SWC fixed output compiled code to `dist`

**None**: `tsc` and `webpack` is success.

### Minimum reproduction code

No

### Steps to reproduce

custom `tsconfig.json`:

```json
{
    "outDir": "custom-out-dir"
}
```

### Expected behavior

Doesn't output compiled code correctly to custom directory, but tsc and webpack builder are correct

### Package version

10.0.5

### NestJS version

10.0.3

### Node.js version

v20.3.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
swc doesn't read the `outDir` from the `tsconfig.json`

**Comment by medz** [comment]
@jmcdo29 

https://github.com/nestjs/nest-cli/blob/master/lib/compiler/defaults/swc-defaults.ts#L28C1-L28C1

Setting `cliOptions` via `.swcrc` still has no effect.

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by medz** [comment]
@jmcdo29 https://github.com/medz/nest-custom-output

At the same time I don't think this problem requires the simplest repository code (although I have written it)

As you can see from https://github.com/nestjs/nest-cli/blob/master/lib/compiler/swc/swc-compiler.ts#L155-L161, the input and output directories are fixed.

I'm guessing #2138 is also related to this, and this simple code works for #2138 as well

**Comment by jmcdo29** [comment]
The code you are saying is "fixed" are defaults and can (and should) be overridden by a .swcrc file

**Comment by medz** [comment]
> The code you are saying is "fixed" are defaults and can (and should) be overridden by a .swcrc file

@jmcdo29 When I read `swc-compiler.ts` I found that it is a fixed value and cannot be overridden by `.swcrc` `cliOptions`.

I created a PR #2140 which fixes this issue

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest-cli/pull/2140
