### ISSUE TITLE
Watch mode when using SWC broken since @nest/cli 10.1.

### ISSUE THREAD

**Issue by DanHulton** [nestjs/nest-cli#2152]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Versions

10.0.5 -> 10.1.0

### Describe the regression

When enabling SWC as the builder for Nest, watching does not work since @nest/cli 10.0.5.  The app builds just fine and SWC will place the updated JS code in the `dist` directory, but NestJS will not notice the updated changes and restart.  When manually restarting, the new changes are displayed, but never caught by the watcher.

Discord conversation that lead to this discovery: https://discord.com/channels/520622812742811698/1125576739083526174

### Minimum reproduction code

To observe the issue:

1) Install fresh NestJS 10.x install
2) Follow SWC Recipe from docs: https://docs.nestjs.com/recipes/swc
3) Start in watch mode with `nest start --watch`
4) Change a file.

Workaround:

1) In package.json, pin the following package: `"@nestjs/cli": "10.0.5",`
2) `npm i`
3) Start in watch mode with `nest start --watch`
4) Change a file

### Expected behavior

I would expect that, on changing a file, the NestJS watcher would realize that SWC had successfully compiled the file and restart the NestJS app.  However, with @nest/cli 10.1.0 and onwards, NestJS just sits there, not noticing.

With the workaround enabled, the changes are picked up and the package restarts.

### Other

Changes from 10.0.5 -> 10.1.0:

https://github.com/nestjs/nest-cli/compare/10.0.5...10.1.0

**Comment by kamilmysliwiec** [comment]
Thanks for reporting! Fixed in 10.1.2
