### ISSUE TITLE
Problem changing main.ts file path with swc configured.

### ISSUE THREAD

**Issue by carvalhoviniciusluiz** [nestjs/nest-cli#2166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

the error manifests itself when I change the root path to the src/main.ts file and add the configs for swc support

### Minimum reproduction code

https://github.com/carvalhoviniciusluiz/project-test-2

### Steps to reproduce

1 - inside the src folder create a new folder and call it whatever you want, here I called it nestjs and it puts all the files that are inside the src then it will look like this

src/nestjs
![IMAGE 2023-07-11 11:01:46](https://github.com/nestjs/nest-cli/assets/22005684/00df5744-fd41-4720-af88-a3aa5d4e4d29)

then change the root file nest-cli.json to the following...  

```json
{
  "$schema": "https://json.schemastore.org/nest-cli",
  "collection": "@nestjs/schematics",
  "sourceRoot": "./http/nestjs",
  "compilerOptions": {
    "deleteOutDir": true
  }
}
```
even in this configuration the project has to keep working because we didn't touch anything else until then we just taught nestjs the path it will need to know to find the main.ts file of the new route.

2 - now if we add the new swc configs the result will change and the error will appear
![IMAGE 2023-07-11 11:05:02](https://github.com/nestjs/nest-cli/assets/22005684/9cb7daed-d28b-41a2-a063-ad38c1e84777)

even if the route is fixed to "src/http/nestjs" the error will remain

### Expected behavior

I was able to change the main.ts file route to nestjs with the swc settings present and allowing the service to start without errors.

### Package version

10.1.8

### NestJS version

10.0.5

### Node.js version

19.3.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

problem detected here https://github.com/nestjs/nest/issues/11978

**Comment by kamilmysliwiec** [comment]
NestJS CLI is looking for `main.ts` file in `dist` directory by default, regardless of what builder you use. To change the entry file location & configure CLI to look for this file elsewhere, simply add the `entryFile` attribute to your `nest-cli.json` file:

```json
{
  "$schema": "https://json.schemastore.org/nest-cli",
  "collection": "@nestjs/schematics",
  "sourceRoot": "src/nestjs",
  "entryFile": "nestjs/main",
  "compilerOptions": {
    "deleteOutDir": true,
    "builder": "swc"
  }
}
```

**Comment by carvalhoviniciusluiz** [comment]
@kamilmysliwiec i noticed that when I add the swc settings through the nest-cli.json file, the only folder that is kept in the dist is the folder that contains nestjs, all the others are deleted.

Is this a behavior of nestjs itself or is the swc having this behavior?

https://github.com/nestjs/nest-cli/assets/22005684/f8fff02c-b527-4ea6-b480-0629fc79389f

**Comment by Karbashevskyi** [comment]
Hi @carvalhoviniciusluiz, did you find any solutions?

**Comment by dngconsulting** [comment]
Is there any solution to this issue ?
