### ISSUE TITLE
Creating a project called help

### ISSUE THREAD

**Issue by ethansocal** [nestjs/nest-cli#2167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Creating a project named help doesn't work. Instead, the following is outputted with no prompt for input at all:

![image](https://github.com/nestjs/nest-cli/assets/79533577/0bf4b898-87de-4569-98e3-90521485c371)

### Minimum reproduction code

N/A

### Steps to reproduce

1. `nest new help`
2. The package manager prompt is displayed, along with the help message. Then, it exits immediately. The package manager prompt doesn't let you input anything, as it already just kicks you out of the command.

### Expected behavior

A new project named `help` should be created.

### Package version

10.1.8

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Interesting. This looks to be a side effect of commander. I checked with my `@ogma/cli` package which uses `commander` under the hood, and got the same immediate `help` output as if I had passed the `--help` flag

**Comment by micalevisk** [comment]
that help message is displayed after calling this line 

https://github.com/nestjs/nest-cli/blob/72b272f722fcdd172ee3d49c65ffa3a9e2474170/bin/nest.ts#L27

Also, that `parseAsync` returns a promise so I believe that we missed the `await` in there. But the error persists besides that

**Comment by kamilmysliwiec** [comment]
Should we create a corresponding issue in the commander repository?
