### ISSUE TITLE
When using global nest cli, swc doesn't work

### ISSUE THREAD

**Issue by ethansocal** [nestjs/nest-cli#2168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When only using the global nest cli, the swc builder doesn't work. `nest build` and `nest start` only output `Failed to load "Error @swc/cli" and "@swc/core" packages. Please, install them by running "npm i -D @swc/cli @swc/core".`

### Minimum reproduction code

https://github.com/ethansocal/nest-bug-reproduction

### Steps to reproduce

1. Remove `@nestjs/cli` from the dependencies of the project
2. Change builder to "swc"
3. `nest build` fails.

### Expected behavior

`nest build` and `nest start` to work, or an error message explaining that the global nest cli cannot work with swc.

### Package version

10.1.8

### NestJS version

10.0.4

### Node.js version

19.0.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Not sure if I'm following. If you want to use a globally installed Nest CLI binary (without having a local copy), then you also have to install SWC globally. 

Still, it's recommended to have a `@nestjs/cli` installed as a dev dependency in your project - in this case, the global copy will always fall back to the locally installed one (for a specific project). Then, as long as swc is installed locally, you should be good to go.
