### ISSUE TITLE
Created app "start:prod" should be "node dist/src/main" not "node dist/main"

### ISSUE THREAD

**Issue by ruoduan-hub** [nestjs/nest-cli#2172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

- Created app "start:prod" should be "node dist/src/main" not "node dist/main"

QA: https://stackoverflow.com/questions/73733844/how-to-run-development-and-production-nestjs-app-docker-docker-compose

node: v18.15.0
cli: @nestjs/cli@10.1.7

```
"@nestjs/common": "^10.0.0",     
"@nestjs/core": "^10.0.0",     
"@nestjs/platform-express": "^10.0.0",     
"reflect-metadata": "^0.1.13",     
"rxjs": "^7.8.1"
```

### Minimum reproduction code

https://stackoverflow.com/questions/73733844/how-to-run-development-and-production-nestjs-app-docker-docker-compose

### Expected behavior

"start:prod" should be "node dist/src/main"

### Package version

@nestjs/cli@10.1.7

### NestJS version

^10.0.0

### Node.js version

v18.15.0

### In which operating systems have you tested?

- [x] macOS
- [x] Windows
- [x] Linux

**Comment by jmcdo29** [comment]
This is dependent on what files get complex and not the default behavior of a `nest new` application. If you think I'm wrong, try it. `nest new -p test && cd test &&npm run build && npm run start:prod`. Everything will start up as expected.

The only reason you would get `dist/src` is if typescript is trying to compile/read a time outside of `src` during the build step, so it does it's best to keep the directory structure in the `outDir`
