### ISSUE TITLE
Monorepo app output path changes when importing from monorepo libs when uing tsc as builder.

### ISSUE THREAD

**Issue by xpol** [nestjs/nest-cli#2174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The `nest build my-app` outputs to `dist/apps/my-app` when there is no importing of workspace libraries.
But it changes to `dist/apps/my-app/apps/my-app/src` when I have importing from the workspace libraries.

### Minimum reproduction code

https://github.com/xpol/my-app

### Steps to reproduce

I have nest-cli managed mono repo with the layout

```
- nest-cli.json
- apps/
    - my-app/
        - src
            -  main.ts
             - ...
    - my-app-with-import/
        - src
            -  main.ts
             - ...
- libs/
    - shared
```

They are all freshly generated with
```
nest new my-app
cd my-app
nest g app my-app-with-import
nest g lib shared 
```

And I have set the `compilerOptions.webpack` to `false` in the `nest-cli.json` file.
And add a import line in the `apps/my-app-with-import/src/my-app-with-import.module.ts`

```patch
+ import { SharedModule } from "@app/shared";
import { Module } from '@nestjs/common';
import { MyAppWithImportController } from './my-app-with-import.controller';
import { MyAppWithImportService } from './my-app-with-import.service';

@Module({
-  imports: [],
+  imports: [SharedModule],
  controllers: [MyAppWithImportController],
  providers: [MyAppWithImportService],
})
```

The command `nest build my-app` output the js files under `dist/apps/my-app`.
Eg. for the `apps/my-app/src/main.ts` will output to `dist/apps/my-app/main.js`.

But the `nest build my-app-with-import`command will generate output js under `dist/apps/my-app-with-import/apps/my-app-with-import/src`.
Eg. for the `apps/my-app-with-import/src/main.ts` will output to `dist/apps/my-app-with-import/apps/my-app-with-import/src/main.js`.

The filnal structure of dist
```
dist
└── apps
    ├── my-app
    │   ├── app.controller.js
    │   ├── app.controller.js.map
    │   ├── app.module.js
    │   ├── app.module.js.map
    │   ├── app.service.js
    │   ├── app.service.js.map
    │   ├── main.js
    │   ├── main.js.map
    │   └── tsconfig.app.tsbuildinfo
    └── my-app-with-import
        ├── apps
        │   └── my-app-with-import
        │       └── src
        │           ├── main.js
        │           ├── main.js.map
        │           ├── my-app-with-import.controller.js
        │           ├── my-app-with-import.controller.js.map
        │           ├── my-app-with-import.module.js
        │           ├── my-app-with-import.module.js.map
        │           ├── my-app-with-import.service.js
        │           └── my-app-with-import.service.js.map
        ├── libs
        │   └── shared
        │       └── src
        │           ├── index.js
        │           ├── index.js.map
        │           ├── shared.module.js
        │           ├── shared.module.js.map
        │           ├── shared.service.js
        │           └── shared.service.js.map
        └── tsconfig.app.tsbuildinfo

```

### Expected behavior

The nest build still outputs to `dist/apps/my-app-with-import` insted of the current behavior outputs to `dist/apps/my-app-with-import/apps/my-app-with-import/src`.

Or at least the output path does change despite of importing from the workspace library or not.instead

### Package version

10.1.8

### NestJS version

10.0.5

### Node.js version

v18.16.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

I also noticed if I switch to Webpack, it works fine.

```
dist
└── apps
    ├── my-app
    │   └── main.js
    └── my-app-with-import
        └── main.js
```

**Comment by jmcdo29** [comment]
This is nothing new, it's how tsc works by default to keep the directory structure. That's why nest's default builder for monorepo mode is webpack, because it's output is consistent regardless of whether you import from a library or not

**Comment by xpol** [comment]
Yes, tried Webpack, but it does not copy assets.
