### ISSUE TITLE
Add flag to CLI to automatically open Swagger docs in browser

### ISSUE THREAD

**Issue by jtreeves** [nestjs/nest-cli#2178]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently, if I want to view my Swagger documentation in the browser, I have to execute the `nest start` CLI command, wait for it to build, then manually open my browser and go to `localhost:3000/api` (my documentation lives at the `api` endpoint).

### Describe the solution you'd like

I would like a CLI flag to automatically open the the browser and go to the URL indicated in my `main.ts` file (which identifies both the port and the Swagger endpoint). Ideally, something like `--openSwagger`. Even better would be an additional, Swagger-specific CLI command, like `nest swagger`. While I know that BE development doesn't really require having an `--open` configuration (unlike FE development), I think Nest's Swagger integration is a real selling point, and _that_ should be viewed in a browser, thus making such a flag a big value-add for Nest.

### Teachability, documentation, adoption, migration strategy

Currently, I can use built-in CLI commands to achieve something similar to what's desired:

```bash
( sleep 3 ; open 'http://localhost:3000/api' ) | nest start
```

The implementation could be as simple as adding a flag to `nest start`, like `--openSwagger`, that on execution forces it to be exactly what I've put there. Even better would be a new CLI command, like `nest swagger`, and its implementation could be exactly what I've written (at least for now, with plans to refine it in the future, and perhaps temporarily adding an addendum in the documentation it only works for Swagger documentation living at the `api` endpoint).

Ideally, instead of using the `sleep` command, it would just execute `curl` commands against `localhost:3000` every second (or whatever time interval) until it receives a result, and once that condition is met, it attempts to open the site.

**Key Commands Being Hacked**
- `sleep` command tells it to wait 3 seconds until trying to open it in the browser, since if I tried to open it automatically, the server wouldn't be up and running yet
- `open` command tells it to open the specific URI, which should launch it in your default browser; as mentioned previously, I needed to use the sleep command to ensure this doesn't get run automatically
- `;` separates the delay command (`sleep`) from the key command (`open`)
- `( ` and ` )` commands (with spaces!) clarify that this entire section should be dealt with as a block operation
- `|` command uses or logic, so the script will first try the first block, which will "fail," so then it will move on to the second block, which will "succeed," but since the first block was still running in the background, it will eventually execute as well
- `nest start` command needs to go at the very end of all

I previously had tried to do `open 'http://localhost:3000/api' && nest start`, which would open it but before the server was built. That could work, but you would have to manually refresh the page, which is unideal. I also previously tried to do `nest start && open 'http://localhost:3000/api'`, but since `nest` is a Node command, everything after it doesn't fire.

### What is the motivation / use case for changing the behavior?

I really wish Nest had a CLI flag for this, and since it doesn't I have had to hack something together by using some native CLI commands:

```bash
( sleep 3 ; open 'http://localhost:3000/api' ) | nest start
```

It would so much easier if I could just execute this:

```bash
nest start --openSwagger
```

Or this:

```bash
nest swagger
```

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
