### ISSUE TITLE
SWC doesn't reload the application

### ISSUE THREAD

**Issue by afaq1182** [nestjs/nest-cli#2187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The swc compiles the file that are changed but doesn't restart the server. I followed exact tutorial as in nestjs official documentation. The files are compiled but the changes aren't reflected in runtime, If I change port in main.ts file and save the file, the app continues running on the previous port.
this is my package.json 
`{
  "name": "total-cx",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:swc": "npx nest start -b swc --watch --type-check",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/config": "^3.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/mapped-types": "*",
    "@nestjs/platform-express": "^10.0.0",
    "@nestjs/schedule": "^3.0.1",
    "@nestjs/typeorm": "^10.0.0",
    "mysql2": "^3.5.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1",
    "typeorm": "^0.3.17"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@swc/cli": "^0.1.62",
    "@swc/core": "^1.3.68",
    "@types/cron": "^2.0.1",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.59.11",
    "@typescript-eslint/parser": "^5.59.11",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-prettier": "^4.2.1",
    "jest": "^29.5.0",
    "prettier": "^2.8.8",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}
`

and this is `.swcrc` 
`{
    "sourceMaps": true,
    "module": {
      "type": "commonjs",
      "strict": true
    },
    "jsc": {
      "target": "es2021",
      "parser": {
        "syntax": "typescript",
        "decorators": true
      },
      "transform": {
        "legacyDecorator": true,
        "decoratorMetadata": true
      },
      "keepClassNames": true
    }
  }`

commands I have tried 
`nest start -b swc -w --type-check`,
`npx nest start -b swc --watch --type-check`,
this is `nest-cli.json`,
`{
  "$schema": "https://json.schemastore.org/nest-cli",
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "deleteOutDir": true,
    "builder": "swc",
    "typeCheck": true
  }
}
`

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-typescript-starter-extwt2?file=nest-cli.json,.swcrc,src%2Fapp.service.ts,package.json

### Steps to reproduce

normal steps

### Expected behavior

I saw on Kamil twitter in which when he saves the file, the server restarts immediately.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

swc

### NestJS version

10

### Packages versions

```json

```

### Node.js version

19.x

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by JohanManders** [comment]
Just a quick little test on my Windows machine with Node v18.17.0:

```js
import { isAbsolute as isAbsolutePath } from 'path';

console.log(isAbsolutePath('D:/apps/nestjs-app/dist')); // true
console.log(isAbsolutePath('D:\\apps\\nestjs-app\\dist')); // true
console.log(isAbsolutePath('./dist')); // false

import { isAbsolute as isAbsolutePosix } from 'path/posix';

console.log(isAbsolutePosix('D:/apps/nestjs-app/dist')); // false
console.log(isAbsolutePosix('D:\\apps\\nestjs-app\\dist')); // false
console.log(isAbsolutePosix('./dist')); // false
```

I really think the posix version should not be used (here).

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest-cli/pull/2188

**Comment by ggagosh** [comment]
Hey, #2188 is for Windows, but I have the same problem for OS X. The application won't reload after compiled

<img width="943" alt="image" src="https://github.com/nestjs/nest-cli/assets/1367931/0e349785-e963-462a-ac68-4f53d2607cb9">

node: v18.16.0 with
osx: 14.0 
```
"@nestjs/core": "^10.0.5"
"@nestjs/cli": "^10.1.18"
"@swc/cli": "^0.1.62"
"@swc/core": "1.3.90"
```

**Comment by sheyDev** [comment]
Application not reloading on Windows using SWC
nest-cli.json
{
    "collection": "@nestjs/schematics",
    "sourceRoot": "src",
    "entryFile": "main",
    "compilerOptions": {
        "assets": [
            "**/*.hbs"
        ],
        "builder": "swc",
        "typeCheck": true
    }
}

versions
"@nestjs/cli": "^10.3.2",

**Comment by sheyDev** [comment]
Application not reloading on Windows using SWC
nest-cli.json
``
{
"collection": "@nestjs/schematics",
"sourceRoot": "src",
"entryFile": "main",
"compilerOptions": {
"assets": [
"**/*.hbs"
],
"builder": "swc",
"typeCheck": true
}
}
``
versions
"@nestjs/cli": "^10.3.2",
