### ISSUE TITLE
Fails to import another package from my pnpm monorepo with Nest 10

### ISSUE THREAD

**Issue by Spoutnik97** [nestjs/nest-cli#2193]
### Did you read the migration guide?

- [x] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Versions

10.1.9

### Describe the regression

I have a pnpm monorepo : 
- packages
-- api (-> my NestJS app)
-- shared (-> some ts files)

I used SWC with nest 9 like described in the doc : 
- 1 terminal to launch `npx swc --out-dir dist -w src`
- 1 terminal to launch `nodemon dist/main` 

With this configuration, when I modified, then built my shared package (`tsc build`), and refreshed nodemon (with the `rs` command), my NestJS app included the new code modified in the shared package

Now, when I launch my nest app with `nest start -w`, my shared package is not imported (the same `const` than before is undefined)

My first question is : How can I use my `shared` package with the new SWC config ? 
My second one : I need to manually build the shared package, then restart my NestJS app. How my NestJS app would watch the changes in the shared package to be restarted automatically ?

### Minimum reproduction code

./pnpm-workspace.yaml
```yaml
packages:
  - "packages/*"

```

./pacakges/api/.swcrc
```json
{
  "$schema": "https://json.schemastore.org/swcrc",
  "sourceMaps": true,
  "module": {
    "type": "commonjs"
  },
  "jsc": {
    "target": "es2017",
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "dynamicImport": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "keepClassNames": true,
    "baseUrl": "./"
  },
  "minify": false
}

```
./packages/api/nest-cli.json
```json
{
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "builder": {
      "type": "swc",
      "options": {
        "swcrcPath": ".swcrc"
      }
    },
    "typeCheck": true
  }
}
```

### Expected behavior

The NestJs app (api package) can import a const from the shared package

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
