### ISSUE TITLE
ERR_REQUIRE_ESM error when trying to import inquirer in Node.js v18.17.0

### ISSUE THREAD

**Issue by geetika-iag** [nestjs/nest-cli#2198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I recently encountered an issue when running my application with Node.js v18.17.0 using the @nestjs/cli package. Here's the error I received:
It seems the require() function does not support ES modules, which causes this error when trying to require the 'inquirer' 
module in 'project-utils.js'. It seems like this might be a compatibility issue with newer versions of Node.js.

I tried upgrading @nestjs/cli to the latest version, but the issue persists.

Environment details:

OS: mac
Node.js version: v18.17.0
NestJS CLI version: v10.1.10

Any help on this issue would be greatly appreciated. Thanks in advance!

### Minimum reproduction code

its behind corporate proxy

### Expected behavior

it shouldn't error out

### Package version

10.1.10

### NestJS version

10.0.5

### Node.js version

18.17.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
see https://github.com/nestjs/nest/issues/12102

**Comment by berenar** [comment]
My two cents here, upgrading to [yarn 3](https://yarnpkg.com/migration/guide) worked for me!
