### ISSUE TITLE
Re-open #1220

### ISSUE THREAD

**Issue by davidmwhynot** [nestjs/nest-cli#2205]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Please re-open this issue: https://github.com/nestjs/nest-cli/issues/1220
(or at least explain why it was closed)

### Describe the solution you'd like

The issue to be re-opened as it was inexplicably closed.

### What is the motivation / use case for changing the behavior?

I'm having the same problem outlined in the issue. The issue hasn't received any attention, probably because it was closed.

**Comment by micalevisk** [comment]
looks like we already support that option:

https://github.com/nestjs/nest-cli/blob/ddcaaa1f194a6f869b39c2f539ef43c2b82bbee2/actions/build.action.ts#L230-L233

but it's missing at the `commands/build.command.ts` file

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest-cli/pull/2206
