### ISSUE TITLE
nest generate configuration is creating a 'undefined' directory for non-monorepo mode

### ISSUE THREAD

**Issue by micalevisk** [nestjs/nest-cli#2207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

when the app isn't in a monorepo mode, `nest g config` will create a file called `undefined/nest-cli.json`

![Image](https://user-images.githubusercontent.com/13461315/257021171-bdcf9300-97f4-451a-bd91-930531f9a272.png)

![image](https://github.com/nestjs/nest-cli/assets/13461315/c291e3c3-eb58-4e9d-9f2b-b31c7d74355a)

That's because the following IF is returning `false`. And the `project` option is not being equals to `"."` (as I expect) for this scenario

https://github.com/nestjs/nest-cli/blob/ddcaaa1f194a6f869b39c2f539ef43c2b82bbee2/actions/generate.action.ts#L77

### Minimum reproduction code

https://github.com/nestjs/typescript-starter

### Steps to reproduce

```
git clone https://github.com/nestjs/typescript-starter
cd typescript-starter
npm i
npx nest g config
```

Note that that project isn't in a monorepo mode

it generates the file `undefined/nest-cli.json`

### Expected behavior

if we already has a `nest-cli.json` in our project, I'd see an error (from angular schematics). If not, a file `nest-cli.json` will be created. Basically, the `options.project` should be `"."` here: https://github.com/nestjs/schematics/blob/07be8d05ae1b78c46267a31bfca8e711e682214a/src/lib/configuration/configuration.factory.ts#L33

To easily fix that, we could just change that line to `options.project || "."` but I'm not sure if this seems correct from the schematics PoV

### Package version

10.1.10

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

> To easily fix that, we could just change that line to options.project || "." but I'm not sure if this seems correct from the schematics PoV

Sounds reasonable
