### ISSUE TITLE
Using swc with paths creates incorrect imports on Windows

### ISSUE THREAD

**Issue by MarkNjunge** [nestjs/nest-cli#2211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Building using swc leads to imports that use paths to be absolute paths instead of relative ones.

```
nest build -b swc

const _appservice = require("C:/path/to/nest-swc-paths-issue/src/app.service");
```

Building using swc directly does not have the same issue
```
npx swc ./src -d dist

const _appservice = require("./app.service");
```

Since using swc directly does not have this issue, it is unlikely that the problem lies there.

The issue likely only affects windows.

### Minimum reproduction code

https://github.com/MarkNjunge/nest-swc-paths-issue

### Expected behavior

The import paths should be relative

### Package version

10.0.0

### NestJS version

10.0.0

### Node.js version

16.15.1, 18.17.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
https://github.com/nestjs/nest/issues/11891

**Comment by MarkNjunge** [comment]
It's not a problem with swc. Building via swc directly works. The issue arises when using nestjs.

**Comment by micalevisk** [comment]
@MarkNjunge did you tested with `@nestjs/cli@10.0.0` or just with the latest version?

**Comment by MarkNjunge** [comment]
@micalevisk I've tested again after ensuring @nestjs/cli@10.0.0 and I'm still experience the same issue.

**Comment by kamilmysliwiec** [comment]
What if you remove paths from your `tsconfig.json` file https://github.com/MarkNjunge/nest-swc-paths-issue/blob/master/tsconfig.json?

**Comment by MarkNjunge** [comment]
I've tried that it's still the same.

**Comment by powerfulyang** [comment]
Temporarily fix by setting [swcOptions](https://github.com/nestjs/nest-cli/blob/183d07b8aed1dce921953ef09486d299cb173097/lib/compiler/swc/swc-compiler.ts#L175) to undefined and defined `paths` and `baseUrl` in .swcrc.

**Comment by kamilmysliwiec** [comment]
For Windows users, path mapping (auto-inheriting baseUrl and paths from tsconfig by swc) was turned off in 10.1.16.

**Comment by MarkNjunge** [comment]
What's the correct config to get it to work? I've updated the dependencies and the issue persists.

I've updated the repo to reflect the changes. https://github.com/MarkNjunge/nest-swc-paths-issue

**Comment by powerfulyang** [comment]
> Temporarily fix by setting [swcOptions](https://github.com/nestjs/nest-cli/blob/183d07b8aed1dce921953ef09486d299cb173097/lib/compiler/swc/swc-compiler.ts#L175) to undefine and set `paths` and `baseUrl` in .swcrc. Here is a [demo](https://github.com/powerfulyang/api.powerfulyang.com/blob/master/patches/%40nestjs__cli%4010.1.13.patch).

`swcOptions` shouldn't be an object when use node to run @swc/cli on Windows.

**Comment by powerfulyang** [comment]
https://github.com/powerfulyang/api.powerfulyang.com/actions/runs/5947215073/job/16128968492#step:9:35

**Comment by MarkNjunge** [comment]
As @powerfulyang suggested, I was able to get it to work by changing `swcOptions` to `undefined`.

https://github.com/nestjs/nest-cli/blob/6c085971b23909f66e309d4d1b94380709429eed/lib/compiler/swc/swc-compiler.ts#L175

**Comment by smiley-uriux** [comment]
FWIW I'm seeing absolute paths in *nix builds too after upgrading to the latest @nestjs/cli and @swc/core packages without having an .swrc file in my project. Everything was working great until all the recent movement.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest-cli/pull/2271
