### ISSUE TITLE
Default library prefix configuration in monorepo styled project

### ISSUE THREAD

**Issue by ph55** [nestjs/nest-cli#2217]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Right now when new library is created via CLI in monorepo configuration it is asking every time for prefix, and the default prefix is always `@app`

### Describe the solution you'd like

Provide the way to configure alternative default prefix via `nest-cli.json`

### Teachability, documentation, adoption, migration strategy

```JSON
{
  "$schema": "https://json.schemastore.org/nest-cli",
  "collection": "@nestjs/schematics",
  "monorepo": true,
  "defaultLibraryNamespace": "@my-org-name"
}
```

### What is the motivation / use case for changing the behavior?

Often when developing in monorepo style default namespace of the libraries would be name of the organization.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?
