### ISSUE TITLE
SWC error to compile

### ISSUE THREAD

**Issue by thomasync** [nestjs/nest-cli#2234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

As soon as I try to compile the code with swc, I get an error, whereas it works fine with tsc.

I've put a quick overview of my main.ts
But I have other problems on my main project with SWC, like the fact that it doesn't execute shutdown hooks even with cli.enableShutdownHooks();

And of course, I tried to change jsc.baseUrl in the .swcrc configuration file, with different paths, but nothing helped.

### Minimum reproduction code

https://github.com/thomasync/swc-nestjs-compilation

### Steps to reproduce

1. pnpm install
2. pnpm run start:app:swc 
  _OR_
3. pnpm run start:cli:swc

### Expected behavior

Output of:
`pnpm run start:app:swc`

Should be Equal To:
`pnpm run start:app:tsc`

---

Output of:
`pnpm run start:cli:swc`

Should be Equal To:
`pnpm run start:cli:tsc`

### Package version

10.0.0

### NestJS version

10.0.0

### Node.js version

20.5.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

$ pnpm run start:cli:swc                                                       

> swc-nestjs-exiting@0.0.1 start:cli:swc /Users/thomasync/Developpement/bazard/swc-nestjs-exiting
> NODE_ENV=cli nest start -b swc

>  SWC  Running...
thread 'thread 'thread 'thread '<unnamed>' panicked at '<unnamed>base_dir(./) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly.<unnamed>' panicked at '' panicked at 'base_dir(./) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly.', <unnamed>', ' panicked at '/Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_transforms_module-0.173.28/src/path.rs/Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_transforms_module-0.173.28/src/path.rs:base_dir(./) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly.:', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_transforms_module-0.173.28/src/path.rs:base_dir(./) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly.', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_transforms_module-0.173.28/src/path.rs:104104:104::131313

104:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failed to handle: base_dir(./) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly.
thread '<unnamed>' panicked at 'base_dir(./) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly.', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_transforms_module-0.173.28/src/path.rs:104:13
failed to handle: base_dir(./) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly.
failed to handle: base_dir(./) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly.
failed to handle: base_dir(./) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly.
thread '<unnamed>' panicked at 'base_dir(./) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly.', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_transforms_module-0.173.28/src/path.rs:104:13
failed to handle: base_dir(./) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly.
failed to handle: base_dir(./) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly.
Failed to compile 6 files with swc.

 Error  Failed to compile:
src/main.ts
src/modules/app/app.controller.ts
src/modules/app/app.module.ts
src/modules/app/app.service.ts
src/modules/cli/cli.module.ts
src/modules/cli/cli.service.ts

**Comment by thomasync** [comment]
I've just tried from scratch the instructions on [https://docs.nestjs.com/recipes/swc](https://docs.nestjs.com/recipes/swc) 
And it crashes too, maybe it's coming from swc directly? 

- `nest new swc-nestjs`
- `cd swc-nestjs`
- `pnpm install`
- `pnpm i --save-dev @swc/cli @swc/core`
- `nest start -b swc`

```bash
>  SWC  Running...
thread 'thread 'thread 'thread '<unnamed><unnamed><unnamed>' panicked at '' panicked at '' panicked at 'base_dir(./) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly.<unnamed>base_dir(./) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly.', ' panicked at '', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_transforms_module-0.173.28/src/path.rsbase_dir(./) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly./Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_transforms_module-0.173.28/src/path.rs:', :/Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_transforms_module-0.173.28/src/path.rs:base_dir(./) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly.', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_transforms_module-0.173.28/src/path.rs:104:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
104104::1313

104:13
failed to handle: base_dir(./) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly.
thread '<unnamed>' panicked at 'base_dir(./) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly.', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_transforms_module-0.173.28/src/path.rs:104:13
failed to handle: base_dir(./) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly.
failed to handle: base_dir(./) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly.
failed to handle: base_dir(./) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly.
failed to handle: base_dir(./) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly.
Failed to compile 5 files with swc.

 Error  Failed to compile:
src/app.controller.spec.ts
src/app.controller.ts
src/app.module.ts
src/app.service.ts
src/main.ts
```

**Comment by kamilmysliwiec** [comment]
https://github.com/swc-project/swc/issues/7800

**Comment by zhangyuang** [comment]
The problem remains
