### ISSUE TITLE
View Generation

### ISSUE THREAD

**Issue by MohammedBageri** [nestjs/nest-cli#2238]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I was an asp.net core developer but I have been using nestjs and nest cli for a while now, I always generate resource with their crud operations. but I usually make the view as well since I use mvc, so I was wondering if I can also generate the view as well from the cli

### Describe the solution you'd like

generating the view from the cli as well, similar to generating controllers, services, etc.

### What is the motivation / use case for changing the behavior?

I want nestjs to be an easier and better framework for people coming from asp.net core, Laravel, and Ruby on Rails. and having such an easy way to generate mvc application will be an easier start.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
