### ISSUE TITLE
jsonSchema of nest-cli should be updated.

### ISSUE THREAD

**Issue by shoma-mano** [nestjs/nest-cli#2285]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I want to compile tsx by swc to use vercel/satori in NestJS Project.

But in default, jsx and tsx are not included in target.
https://github.com/nestjs/nest-cli/blob/88ed13d26fdf580e4248a544f24a6100111ce698/lib/compiler/defaults/swc-defaults.ts#L41C1-L42C1

I solved this problem by setting compileOptions.builder to
```
    "builder": {
      "type":"swc",
      "options":{"extensions": [".ts", ".tsx", ".js", ".jsx"]}
    }
```
But this builder type is not included in current jsonSchema.
https://github.com/SchemaStore/schemastore/blob/b1c6f263b36fd045e98f37bc78dd1d45017f86f1/src/schemas/json/nest-cli.json#L18

This should be updated.

### Describe the solution you'd like

At first, jsonSchema should be updated.

### What is the motivation / use case for changing the behavior?

To support compilation of jsx with swc.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by shoma-mano** [comment]
yes...I created PR already.
This json worked in local, but If something is wrong with this, please tell me.
https://github.com/SchemaStore/schemastore/pull/3224
