### ISSUE TITLE
Bun package manager

### ISSUE THREAD

**Issue by Pedromdsn** [nestjs/nest-cli#2286]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

As most of you may already know, bun has just released version 1.0, i.e. the production version.
Bun is an all-in-one JavaScript runtime, that is, it also includes a package manager that I think would be an added value, since according to its graphics it presents exceptional results.

![image](https://github.com/nestjs/nest-cli/assets/57453260/707bd6c4-a79c-42ca-be53-51251889181e)

### Describe the solution you'd like

Add a package-maner and runner to bun.

### Teachability, documentation, adoption, migration strategy

[Bun docs](https://bun.sh/docs)

### What is the motivation / use case for changing the behavior?

I believe that the initial solution would be to add the runtime to the nestjs cli to make the lives of programmers who want to use it easier.

**Comment by jmcdo29** [comment]
[Is it really that hard to search the open PRs?](https://github.com/nestjs/nest-cli/pull/2223)
