### ISSUE TITLE
[BUG - Windows] - Generate deletes module content

### ISSUE THREAD

**Issue by MartinFreire** [nestjs/nest-cli#23]
Hi

I tried using the cli in W10 with a new project

When I tried to add a controller to a module, in both cases the module content is erased and a ".ts.lock" file is created

This is the log of the console on a fresh project

```
C:\Users\USER\liquidaciones>nest generate module operaciones
create src\app\modules\operaciones\operaciones.module.ts

C:\Users\USER\liquidaciones>nest g controller operaciones operaciones
create src\app\modules\operaciones\controllers\operaciones\operaciones.controller.ts
create src\app\modules\operaciones\controllers\operaciones\operaciones.controller.spec.ts
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\USER\liquidaciones\src\app\modules\operaciones\operaciones.module.ts.lock'
    at Error (native)
```

Previously I did `nest new my-app` and then `npm install`

Thanks!

**Comment by ThomRick** [comment]
Hey @MartinFreire !
Sorry for the response time ! 
And I'm also  sorry about your problem.
I think Windows users are forgotten in this Nest-CLI adventure ><
A lot of bugs on Windows.

But what version of Node do you use ?

I'm thinking about building docker images of Nest-CLI...

**Comment by MartinFreire** [comment]
Hi! no worry. I know it's a little project so I just tried to let you know of what happen to other people
It's an awesome project.
I'm using LTS v8.9.1
I know it will take time to work well on Windows, but if I can help somehow I think this could grow and I don't want it to die...
I really like the AngularCLI concept
Thanks!

**Comment by ThomRick** [comment]
Hey @MartinFreire 
I'm thinking about remove de module update feature for the next version to develop it more efficiently and be both compatible Unix and Windows OS
