### ISSUE TITLE
Using Webpack Compiler and watchAssets is true, nest start's process can't be stopped from entry file.

### ISSUE THREAD

**Issue by tkow** [nestjs/nest-cli#2303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If we use nest webpack compiler and watchAssets flag is true, we can't exit a process created by `nest start` command because watchAssets listener is separated from bootstrap process.  In the result, It's uncomfortable to use nest as command line tools using webpack, given if like nest-commander.

See: ( https://github.com/tkow/nest-watch-assets-demo/blob/master/src/main.ts )

### Minimum reproduction code

https://github.com/tkow/nest-watch-assets-demo

### Steps to reproduce

1. pnpm i
2. npx nest start -- hello
3. The process isn't exited unless you send signal INT

### Expected behavior

When process.exit() calls from somewhere of entry files the nest start process should stop.  

### Package version

10.0.1

### NestJS version

10.0.1

### Node.js version

18.15.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

I already suggest a way to fix this bug in [the PR](https://github.com/nestjs/nest-cli/pull/2293).
Also chokidar listener can't listen to complete all copied processes. So if watchAssets: false specified, I think  its' better that nest's logic fallback to sync process and I did in it.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest-cli/pull/2293
