### ISSUE TITLE
[Minor-Security] String formatting function is prone to misuse / abuse

### ISSUE THREAD

**Issue by espoal** [nestjs/nest-cli#2336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The string formatting [function](https://github.com/nestjs/nest-cli/blob/be5aab2940af67886acf6175097b066766632597/lib/utils/formatting.ts#L8) is prone to misuse / abuse, due to poor behaviour on special characters.

In a monorepo setup you could overwrite the main `package.json` by mistake.

With a little bit of creativity it's possible to use shell expansion to do a bit of damage to the filesystem by overwriting possibly important files.

### Minimum reproduction code

https://github.com/espoal/kebab-or-snake

### Steps to reproduce

Type

`nest new -s`

When prompted for a name give

`$test`

### Expected behavior

The `$` should be dropped from the name (or kept) and the app should be created in the `test` (`$test`) folder.

### Package version

10.1.7

### Node.js version

18.16.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

Incidentally, this issue is fixed by these PRs:

- [1501](https://github.com/nestjs/schematics/pull/1501)
- [2208](https://github.com/nestjs/nest-cli/pull/2208)

**Comment by kamilmysliwiec** [comment]
Let's track this here then https://github.com/nestjs/nest-cli/pull/2208
