### ISSUE TITLE
The application won't reload after compiled OS X

### ISSUE THREAD

**Issue by ggagosh** [nestjs/nest-cli#2408]
Hey, #2188 is for Windows, but I have the same problem for OS X. The application won't reload after compiled

<img width="943" alt="image" src="https://github.com/nestjs/nest-cli/assets/1367931/0e349785-e963-462a-ac68-4f53d2607cb9">

node: v18.16.0 with
osx: 14.0 
```
"@nestjs/core": "^10.0.5"
"@nestjs/cli": "^10.1.18"
"@swc/cli": "^0.1.62"
"@swc/core": "1.3.90"
```

_Originally posted by @ggagosh in https://github.com/nestjs/nest-cli/issues/2187#issuecomment-1748842420_

**Comment by sshkodunishka** [comment]
I have same issue, did you fixed it ?

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

**Comment by ggagosh** [comment]
> Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

I'll try to put together a repo to replicate the issue, but it's a bit tricky – it doesn't occur regularly, just appears out of nowhere sometimes, which makes it hard to determine a pattern or reproduce it intentionally. 👀

**Comment by maisnamraju** [comment]
@ggagosh try this instead of the default command. Looks like the `--watch` property is not read when using swc ( atleast in my case) 

```
"start": "nest start --watch",
```
