### ISSUE TITLE
Errors in default webpack config file (webpack.config.json) are silently ignored

### ISSUE THREAD

**Issue by Glandos** [nestjs/nest-cli#2421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When a `webpack.config.js` has some error (either syntax or runtime), this is silently ignored, and replaced with default configuration.

See https://github.com/nestjs/nest-cli/blame/a95b21e02ff9333b48264ae5f1d2d9b941f56a36/actions/build.action.ts#L272

I guess this was done to ignore FileNotFound errors, but then, only this error should be ignored.

### Minimum reproduction code

https://example.com

### Expected behavior

Error from default configuration file should be reported

### Package version

10.2.1

### NestJS version

10.2.10

### Node.js version

v16.20.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?
