### ISSUE TITLE
Regression > Copying assets is broken on Windows devices

### ISSUE THREAD

**Issue by ErazerBrecht** [nestjs/nest-cli#2429]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Versions

8.1.X -> 8.2.X

### Describe the regression

When running `npm run start` you will get the following error:
> Error  An error occurred during the assets copying process. cant go up that far

This only seems to be the case in Windows.
In our docker containers in PROD everything works (Linux containers). Also our MacOS developers don't have the problem.

### Minimum reproduction code

Adding a file to the assets config in `nest-cli.json`

```
 "assets": ["settings.json"]
```

Quickly created a git repro to showcase the problem
https://github.com/ErazerBrecht/nestjs_regression

[Master branch](https://github.com/ErazerBrecht/nestjs_regression) latest NestJS version => Doesn't work
[Reverted branch](https://github.com/ErazerBrecht/nestjs_regression/tree/reverted_version) NestJS 10.1.X => Works

### Expected behavior

The expected behavior is the as-is behavior in the 10.1.X version.
It should just copy the 'settings.json' file to the dist folder.

### Other

This issue might be related: 
https://github.com/nestjs/nest-cli/issues/2397
But that issue describes the files aren't copied in my case the cli already "crashes". It also sounds like it only happens with a glob pattern. Which I don't use here.

**Comment by kamilmysliwiec** [comment]
Fixed in 10.4.0

**Comment by lmedinaC** [comment]
im using 10.4.7 and i have the same problem ... i tried with compilerOptions in nest-cli.json and is the same 
![image](https://github.com/user-attachments/assets/f5c23b8a-f2cc-471f-8173-ba5471f19a46)
