### ISSUE TITLE
odd behavior when the config file can't be read

### ISSUE THREAD

**Issue by micalevisk** [nestjs/nest-cli#2434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When we have some nest config file but the system user running the nodejs process has no permissions to _read_ the file the CLI silently ignores that, which could lead to confusion. For example: someone changed the content of `nest-cli.json` but the CLI ends up using the default values due to missing permissions.

This behavior is due to the following lines:

https://github.com/nestjs/nest-cli/blob/6617460c4f027aa32145af8dcac85ad72920932b/lib/readers/file-system.reader.ts#L21-L25

### Minimum reproduction code

https://github.com/nestjs/typescript-starter

### Steps to reproduce

```bash
git clone https://github.com/nestjs/typescript-starter
cd typescript-starter
npm install

## change the nest-cli.json to an invalid config (eg: change the entryFile)

chmod -r nest-cli.json

npm run start:dev # see no errors
```

### Expected behavior

either exiting with an error due to a non-readable nest config file or a warning message.

Exiting with an error seems better to me but it would be breaking change if the present behavior is a feature not a bug

### Package version

10.2.1

### Other

I can make a PR to address this

**Comment by kamilmysliwiec** [comment]
I'd love to see a PR for this issue so yes please go ahead 🙏

**Comment by major-winter** [comment]
Hello, I'm new in the open source contribution community. I'm also interested in this issue. I wonder should we check the user's permission on file before actually reading it.

**Comment by micalevisk** [comment]
@major-winter what I'm doing so far is checking the exception thrown on reading, because this is an edge case

But I'm not done yet so you can open a PR to address this

Another thing that I'd do in the PR: use the `fs.readSync` instead of the promise-based API, for performance reasons

**Comment by major-winter** [comment]
@micalevisk Great, I'll wait for your PR.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest-cli/pull/2446
