### ISSUE TITLE
false-positive warning message for `@nestjs/schematics`

### ISSUE THREAD

**Issue by micalevisk** [nestjs/nest-cli#2458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

the lastest version of `@nestjs/schematics` is 10.1.x not 10.3.x, so when running `nest info` we'll see the following warning:

```
[Warnings]
The following packages are not in the same minor version
This could lead to runtime errors
* Under version 10.3
- @nestjs/platform-express 10.3.0
- @nestjs/common 10.3.0
- @nestjs/core 10.3.0
* Under version 10.1
- @nestjs/schematics 10.1.0
```

### Minimum reproduction code

N/A

### Expected behavior

I'm not sure if `@nestjs/schematics` is supposed to be updated to 10.3 or not, if not, I'd suggest to drop the minor-level checking and check only the major slice instead

### Package version

10.3.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
> I'd suggest to drop the minor-level checking and check only the major slice instead

Would you like to create a PR for this issue?
