### ISSUE TITLE
Update gitignore to include more common files or folders 

### ISSUE THREAD

**Issue by kishorliv** [nestjs/nest-cli#2471]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

After creating a nest project and adding `.env` file, i sometimes accidentally commit it. 

### Describe the solution you'd like

Update gitignore to contain `.env` and some other common files/folders like `build`, `.tmp`, `.log`, etc by default. 

### What is the motivation / use case for changing the behavior?

Prevent accidentally committing important files

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by kishorliv** [comment]
Sure, will create a PR for this.

**Comment by micalevisk** [comment]
I guess you pick peek ones from https://www.toptal.com/developers/gitignore/api/node

**Comment by kishorliv** [comment]
@micalevisk yep, i usually use it for my projects... will use most of them... it seems to missing `DS_Store`, will add it too...

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest-cli/pull/2476
