### ISSUE TITLE
add "compilerOptions.sourceMaps" option is nest-cli-json

### ISSUE THREAD

**Issue by ianzone** [nestjs/nest-cli#2493]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

none

### Describe the solution you'd like

control source map generation via nest-cli.json
```
{
  "$schema": "https://json.schemastore.org/nest-cli",
  "collection": "@nestjs/schematics",
  "compilerOptions": {
    "sourceMaps": true
  }
}
```

### What is the motivation / use case for changing the behavior?

avoiding adding more rc/json files.

**Comment by kamilmysliwiec** [comment]
NestJS CLI doesn't generate any source maps
