### ISSUE TITLE
Clean up dependencies

### ISSUE THREAD

**Issue by cojack** [nestjs/nest-cli#2512]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Does typescript or wepback are mendatory production dependency?

### Describe the solution you'd like

Move dev dependencies from dependencies list to devDependencies, to reduce production installation size of node_modules

### What is the motivation / use case for changing the behavior?

Reduce the size of node_modules

**Comment by micalevisk** [comment]
They are mandatory due to few features of the CLI.

Also, you shouldn't be using nestjs CLI in production. This is against nodejs's best practices. You only need to build and then use `node`, as any other TS project
