### ISSUE TITLE
Listing all the routes/endpoints with their types and middleware  in project 

### ISSUE THREAD

**Issue by kumarabhiyadav** [nestjs/nest-cli#2521]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Facing issues while get list of all routes in nest application, recently I created a nested routes in UserController (v1/users/login) post request but I failed to know the end point of the controller function.

### Describe the solution you'd like

We can implement like Laravel command ie. php artisan routes:list for nests cli, which can show clear list of all avaliable  endpoints with the request types 
![route_list](https://github.com/nestjs/nest-cli/assets/69810292/e73047ca-a700-44cb-8758-2fe9e76cb662)

### Teachability, documentation, adoption, migration strategy

users can easily use nest routes:list 

### What is the motivation / use case for changing the behavior?

It's hard to identify routes / endpoints in large applications

**Comment by micalevisk** [comment]
duplicate #15

**Comment by kamilmysliwiec** [comment]
https://www.devtools.nestjs.com/
