### ISSUE TITLE
CLI not work whit PowerShell

### ISSUE THREAD

**Issue by C1ach0** [nestjs/nest-cli#2555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

There's an issue with the CLI when using PowerShell. By default, on Windows with VSCode, PowerShell is used, but it's not possible to call the `nest` command.

![image](https://github.com/nestjs/nest-cli/assets/90418900/ceae9204-d84f-4666-b4f9-2bbed3889d8a)

### Minimum reproduction code

https://github.com/nestjs/nest-cli

### Steps to reproduce

1. `Open PowerShell`
2. `nest`
3. `See Error`

### Expected behavior

There's an issue with the CLI when using PowerShell. By default, on Windows with VSCode, PowerShell is used, but it's not possible to call the `nest` command.

### Package version

10.0.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by Tony133** [comment]
Have you also tried using the `npx` command?

by doing: `npx @nestjs/cli new project-name`

**Comment by micalevisk** [comment]
I don't think this is a `@nestjs/cli` but a setup issue on your side. I know people that are using the CLI globally just fine. But I'd recommend you to avoid using `nest` globally like that. Always use `npx nest` (ie., the local one, per project)

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
