### ISSUE TITLE
Class generator creating file inside non specified folder on Windows 11

### ISSUE THREAD

**Issue by cedaesca** [nestjs/nest-cli#2581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Manifests in a fresh nestjs install.

### Minimum reproduction code

https://github.com/nestjs/nest-cli

### Steps to reproduce

1. Be on Windows 11
2. Fresh install a nestjs app using the nestjs CLI
3. Generate a new class, specifying a custom path, eg: `nest g class coffee/dto/update-coffee.dto`
4. See the generated class being put into `coffee/dto/update-coffee.dto/update-coffee.dto.ts`

### Expected behavior

If I run `nest g class coffee/dto/update-coffee.dto`, I would expect the file to be put in `coffee/dto/update-coffee.dto.ts`

### Package version

10.3.2

### NestJS version

10.3.2

### Node.js version

20.12.2

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

no

**Comment by cedaesca** [comment]
> npx nest g class coffee/dto/update-coffee.dto

Same issue.
![image](https://github.com/nestjs/nest-cli/assets/26552106/cf3a8ed6-9d45-43a3-8771-f8337b5603a8)

**Comment by micalevisk** [comment]
actually, that's the expected behavior

you must use the flag `--flat` at the end instead

**Comment by cedaesca** [comment]
> actually, that's the expected behavior
> 
> you must use the flag `--flat` at the end instead
> 
> or add the following to your `nest-cli.json`
> 
> ```
> "generateOptions": {
>     "flat": true
>   },
> ```

Oh. This wasn't mentioned by the instructor in the official course. Thanks.
