### ISSUE TITLE
How to configure the cli for auto importing the generated controller and services

### ISSUE THREAD

**Issue by justinlazaro-ubidy** [nestjs/nest-cli#259]
Hi, is possible to configure the cli for auto import the generated controller and services? 
right now my folder structure is

```
src
   rootApp
      -- app.module.ts
      -- app.service.ts
      -- app.controller.ts
   modules
      user 
      -- user .module.ts
      -- user .service.ts
      -- user .controller.ts
      authentication
      -- authentication.module.ts
      -- authentication.service.ts
      -- authentication.controller.ts
```

thanks.

**Comment by kamilmysliwiec** [comment]
CLI should automatically update your imports if your directories structure is in line with the framework recommendations. For instance, in your example, `rootApp` folder shouldn't exist (and its content should be moved straight to the `src` dir).
