### ISSUE TITLE
SWC: NestCLI still starts the Nest server, even TypeCheck with TSC fails.

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [nestjs/nest-cli#2599]
### Did you read the migration guide?

- [ ] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Versions

@nestjs/cli@10.3.2, @swc/core@1.5.5

### Describe the regression

NestJS is still started in "dev", regardless that TSC finds a type error. 
This only happens when using SWC as a compiler, as described on the NestJS website.

### Minimum reproduction code

```ts

```

### Expected behavior

Just like TSC path, on type error, NestJS should be kept stopped, until that error is resolved.

**Comment by kamilmysliwiec** [comment]
This is the expected behavior (TS checker runs asynchronously, independent of the compilation process).
