### ISSUE TITLE
npm WARN deprecated inflight@1.0.6

### ISSUE THREAD

**Issue by yusuf-saydullayev** [nestjs/nest-cli#2609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.

### Minimum reproduction code

Since this happens with CLI usage, I don't see how I can provide meaningful reproduction code.

### Steps to reproduce

1. npm i -g @nestjs/cli
2. See warning 

### Expected behavior

wihtout warning

### Package version

10.3.2

### Node.js version

20.13.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by Levon770** [comment]
same on Node.js version 22.2.0

**Comment by micalevisk** [comment]
![image](https://github.com/nestjs/nest-cli/assets/13461315/da18fbb6-ef97-44bc-a6ae-2054221648e3)

that is a transitive dependency

it's used by `shelljs` so you should report this to https://github.com/shelljs/shelljs

As long as you don't use the asset feature, you don't need to worry about it.

https://github.com/nestjs/nest-cli/blob/77c3e454170cd55d238c4e8121c2e48ef6d8800c/lib/compiler/assets-manager.ts#L139-L140

I guess we can do much on our side

**Comment by jaimeviloriogreen** [comment]
I had de same issue when installing nest cli

**Comment by TheStutzen** [comment]
- I have exactly the same problem when installing nest.js on a mac apple sillicon

```
npm i -g @nestjs/cli
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
```

**Comment by TheStutzen** [comment]
- I solved the problem by changing the package manager to yarn, but this does not solve the problem with a clean installation of nest.js using the yarn package manager

**Comment by tanayvaswani** [comment]
Same error Macbook Air M2, any ideas why is this happening? 

```
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
```

**Comment by micalevisk** [comment]
@tanayvaswani https://github.com/nestjs/nest-cli/issues/2609#issuecomment-2143424589

**Comment by micalevisk** [comment]
btw this is being tracked here: https://github.com/shelljs/shelljs/issues/1149

**Comment by adeboyega** [comment]
I cant use vite, react or Next.js right now do i need to update something ?>

'_Wisdom\my-app\node_modules\.bin\' is not recognized as an internal or external command,
operable program or batch file.
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module 'C:\Users\USER\Desktop\Webprojects\next\dist\bin\next'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.11.0

**Comment by MalahimHaseeb** [comment]
i also currently facing this error .How to resolve it ?
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead

**Comment by adeboyega** [comment]
"Deprecated" does not mean "wrong" or "bad"; it simply means that you
should use something that is maintained because it will no longer be
maintained.

**Comment by Al-Sharif** [comment]
@adeboyega, " This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful."

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest-cli/pull/2526

**Comment by teo-lin** [comment]
With the latest node LTS (20.16.0 as of now), you can solve the issue by upgrading the problematic packages in the package-lock.json. There are many edits needed, you can use the attached one until the next nestjs update. [package-lock.json](https://github.com/user-attachments/files/16639373/package-lock.json)

**Comment by alxdrl** [comment]
`nest new` with version 11.0.7 stil yields the issue.

I added overrides as explained here https://stackoverflow.com/a/78799034

This is advertised as a temporary solution, not sure what the long term fix is though once the app is initialized.
