### ISSUE TITLE
Ability to use node cli parameters in nest cli commands

### ISSUE THREAD

**Issue by Vigneshwaran16** [nestjs/nest-cli#2612]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Node cli accepts optional parameters. For example, say, `--env-file <env_file_path>` parameter which accepts env file location. I couldn't be able to find (if any?) a provision in existing nestjs cli to achieve this behavior. 

### Describe the solution you'd like

It would be great if this way of providing node cli parameters to nest cli. 

### What is the motivation / use case for changing the behavior?

I believe this would be straight forward feature, which aligns to that of node cli.

**Comment by micalevisk** [comment]
not needed as we can supply any nodejs cli options to Nestjs CLI already. See: [NestJS tip: how to use Node.js built-in .env file reader with NestJS CLI ](https://dev.to/micalevisk/nestjs-tip-how-to-use-nodejs-built-in-env-file-reader-with-nestjs-cli-4alm)

**Comment by Vigneshwaran16** [comment]
@micalevisk Thanks for this info. On a different thought, what did you mean by 

> nodejs has several options, copy few of them to nestjs cli won't scale

**Comment by micalevisk** [comment]
--env-file  is a nodejs option

If we start adding those runtime options as well in nestjs cli but with different logic around it, people will ask for more and more. And may introduce confusion since the one from nestjs won't behave the same as the one from nodejs

**Comment by Vigneshwaran16** [comment]
Thanks for the answer. Closing as resolved.
