### ISSUE TITLE
Nest CLI Project version issue

### ISSUE THREAD

**Issue by viswatejavissamsetty** [nestjs/nest-cli#2613]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When we created project with latest nest cli version still its generating project with older version of nest. in my system i have installed nest cli version 10.3.2 
![image](https://github.com/nestjs/nest-cli/assets/63993225/f7c5bc7f-8844-43ca-9114-2da87e100e6e)
but it has created a project with version 10.0.0 
![image](https://github.com/nestjs/nest-cli/assets/63993225/16f43e6c-4cf6-42e7-a172-a78930faa92c)

because of this we need to manually upgrade project version after project creation.

### Minimum reproduction code

https://github.com/viswatejavissamsetty/a-project

### Steps to reproduce

1. npm i -g @nestjs/cli
2. nest new project1

### Expected behavior

the nest cli commands need to create project as per the installed version.

### Package version

10.3.2

### NestJS version

10.3.2

### Node.js version

20.12.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

No Comments

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
