### ISSUE TITLE
Remove 'source-map-support' package in favor of Nodejs built-in source mapping feature

### ISSUE THREAD

**Issue by micalevisk** [nestjs/nest-cli#2629]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

as of now `@nestjs/cli` injects [`source-map-support`](https://github.com/evanw/node-source-map-support). But as they say in their README:

![image](https://github.com/nestjs/nest-cli/assets/13461315/226531c3-4d73-4763-82fc-8a1cea439a52)

we can use nodejs's [`--enable-source-maps`](https://nodejs.org/docs/latest-v16.x/api/cli.html#--enable-source-maps) flag instead since nodejs v12

I don't know why this package was added since v12 is too old, to be honest :thinking: 

### Describe the solution you'd like

update the following lines to replace `-r "source-map-support/register"` with `--enable-source-maps`

https://github.com/nestjs/nest-cli/blob/d87405a09d9a8a9758cce1c114e36c40e272ebd8/actions/start.action.ts#L178-L181

I tested this is a simple nestjs app and it seems to be working:

<details>
<summary>code</summary>

![image](https://github.com/nestjs/nest-cli/assets/13461315/0505e8a8-c5f2-4b2f-a59f-d1f967f008b9)

</details>

<details>
<summary>when <code>sourceMap:true</code> in our tsconfig</summary>

![image](https://github.com/nestjs/nest-cli/assets/13461315/a86cce18-4b6d-44ee-a5be-bba217afaa4e)

</details>

<details>
<summary>when <code>sourceMap:false</code> in our tsconfig</summary>

![image](https://github.com/nestjs/nest-cli/assets/13461315/a2f2643e-1bf9-433e-9550-12cb824a5349)

</details>

### What is the motivation / use case for changing the behavior?

1. `source-map-support` looks abandoned. Their github repository has many PRs and issues open
2. it has issues such as #2533 that `@nestjs/cli` cannot work around
3. we would have one less dependency on `@nestjs/cli`

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?
