### ISSUE TITLE
Faster startup with -w parameter on Windows platform in monorepo mode

### ISSUE THREAD

**Issue by winkcc** [nestjs/nest-cli#2651]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

When using the nest start app command in monorepo mode on the Windows platform, adding the -w parameter results in a significantly faster startup compared to the normal startup process. 

### Describe the solution you'd like

I think that the nest start app command should be as fast as when the -w parameter is added.

### What is the motivation / use case for changing the behavior?

When I start an empty Nest project on Windows with nest start app, it takes 1700ms. However, when I use nest start  app -w, the startup time is reduced to 200ms.  I tested both tsc and webpack as the bundling tools, and the results were the same. 

However, it seems that in larger projects, the startup times remain slow regardless of the -w parameter.(i am not sure)

**Comment by kamilmysliwiec** [comment]
This can be reproduced with `tsc` and `tsc -w` so it's unrelated to the NestJS CLI itself
