### ISSUE TITLE
Unblocking TypeScript project reference builds

### ISSUE THREAD

**Issue by mashedkeyboard** [nestjs/nest-cli#2656]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently, the Nest CLI doesn't support building TypeScript project references at the same time as building the app itself. This was discussed in #392, an issue that remains open, but the issue has for some reason been locked as "spam". The issue had previously been marked as blocked, but [an upstream resolution for this was merged years ago in 2019](https://github.com/TypeStrong/ts-loader/pull/935).

### Describe the solution you'd like

Could we consider reopening that issue, and/or utilising the upstream implemented functionality to support solution builds with references incorporated into the Nest CLI?

### What is the motivation / use case for changing the behavior?

Developer experience is currently compromised by having to build dependencies separately to the application, in a way that other projects using ts-loader are not required to do.

**Comment by kamilmysliwiec** [comment]
The issue is locked because there's nothing else to say. If anyone is interested in creating a PR, please, go ahead. Otherwise, there's no reason to keep this issue open so that folks can post "+1" comments every now and then.
