### ISSUE TITLE
Error building app when including file asset from nestjs root folder in nest-cli.json

### ISSUE THREAD

**Issue by jaunusa** [nestjs/nest-cli#2677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The nestjs build fails when addeing a single file asset item to copy a config file from the nestjs root directory.

nest-cli throws: `cant go up that far`

`tsconfig.json` customization:
```
...
"outDir": "../../dist/server",
"rootDir": "./"
```

assets configuration in `nest-cli.json`:
```
{
  "$schema": "https://json.schemastore.org/nest-cli",
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "deleteOutDir": true,
    "assets": [
        {
            "include": "../.config.yaml",
            "watchAssets": true
        },
        {
            "include": "../assets",
            "watchAssets": true,
            "outDir": "../../dist/server/assets"
        }
    ]
  }
}
```

### Minimum reproduction code

https://github.com/jaunusa/nestjs-file-asset-issue

### Steps to reproduce

1. cd apps/server
2. npm install
3. nest build
4. see error: cant go up that far

### Expected behavior

I would expect that building the app copies `.config.yaml` to build output directory like it does with the `assets` folder. When I remove the assets entry for `.config.yaml` the assets folder is copied whithout throwing any error.

### Package version

10.4.2

### NestJS version

10.3.10

### Node.js version

18.18.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

The reproduction projects structure with custom output paths, is a simplified example for using nestjs in a monorepo setup.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR that changes this line

https://github.com/nestjs/nest-cli/blob/8416f33e3bf7c1bb822da644d1a8f3531d5ad25c/lib/compiler/helpers/copy-path-resolve.ts#L18-L19

to `up - 1` (in the `if` condition)? We could also improve the error message to make it a bit more self descriptive

**Comment by jaunusa** [comment]
PR created: https://github.com/nestjs/nest-cli/pull/2681

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest-cli/pull/2681
