### ISSUE TITLE
--enable-source-maps native binding doesn't work with ts-node

### ISSUE THREAD

**Issue by garrypas** [nestjs/nest-cli#2678]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Potential Commit/PR that introduced the regression

2630

### Versions

10.0.0->10.4.2

### Describe the regression

I have a NestJS app. When I try to run it I encounter an error

Tracking it I can see it's hitting [this bit of code](https://github.com/TypeStrong/ts-node/blob/ddb05ef23be92a90c3ecac5a0220435c65ebbd2a/src/bin.ts#L100) in ts-node, which is missing `--enable-source-maps` - as a result the "arg" lib throws the following error:

`Error: Unknown or unexpected option: --enable-source-maps`

### Minimum reproduction code

This is my start script (there's some stuff specific to my app), but I can see that the nest-cli lib adds an `--enable-source-maps` onto the ts-node run command:

```sh
cross-env NODE_ENV=development ENV=development nest start --watch -e \"ts-node -r ./src/env/env.module.ts -r ./src/db/test-data-run.ts\"
```

### Expected behavior

Removing [this line](https://github.com/nestjs/nest-cli/blob/8416f33e3bf7c1bb822da644d1a8f3531d5ad25c/actions/start.action.ts#L178) (or downgrading to v10.4.1) makes the error go away. It doesn't seem to work when you use the latest version of ts-node.

**Comment by micalevisk** [comment]
can you clarify why you're using `ts-node` with Nest's CLI? :thinking: 

Also, I'm not sure if this must be handled by `ts-node`. There are few open issues on their side regarding `--enable-source-maps`

**Comment by garrypas** [comment]
The run command was originally `NODE_ENV=development ENV=development nest start --watch`, which I think was derived from the command originally generated by the NestJS wizard used at the time.

The command is trying to seed some data in a DB on dev start. It only works like this for local dev, elsewhere it just uses node against a ./dist folder which all work fine. I don't know why this particular approach to run locally was chosen tbh.

**Comment by micalevisk** [comment]
I guess you can use `node` instead of `ts-node` but I see that this can be seem as a regression because `--enable-source-maps` might not be available for others binaries -- this was not clear to me before.

So I can see two approaches to fix this:

1. revert the changes made in #2630 commit (which is pretty sad because `source-map-support` is poorly maintained)
2. use `source-map-support` instead of adding the `--enable-source-maps` flag when the binary to run is not nodejs

which one do you prefer @kamilmysliwiec ?

**Comment by garrypas** [comment]
@micalevisk as a solution I ran the app using ts-node without using the nest-cli (I guess your suggestion would work too), but the tricky thing for me was understanding what had gone wrong, I had to do some digging through the libs to figure it out.

Thanks for the response.

**Comment by kamilmysliwiec** [comment]
If you want to use `ts-node` then I'd say you probably don't need `nest start` (pre-start build is not needed) - you can safely use `ts-node` alone
