### ISSUE TITLE
How can I delete resources automatically created by nestjs?

### ISSUE THREAD

**Issue by com0t** [nestjs/nest-cli#2679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I create resource with command: `nest g resource user`
Now I want to delete resource related to `user` but can't find suitable command.
I am new to nestjs

### Minimum reproduction code

https://github.com/nestjs/nest-cli/blob/8416f33e3bf7c1bb822da644d1a8f3531d5ad25c/bin/nest.ts#L34

### Expected behavior

please show me how can i delete resource auto generated by nestjs

### Package version

10.4.2

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
