### ISSUE TITLE
use rspack by default

### ISSUE THREAD

**Issue by ianzone** [nestjs/nest-cli#2695]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

https://github.com/nestjs/nest-cli/issues/1549#issuecomment-1573324404

### Describe the solution you'd like

use nest-cli as usual but utilize rspack for dev HMR and prod build. 

### What is the motivation / use case for changing the behavior?

better DX

**Comment by micalevisk** [comment]
I don't see any good reason to use anything but typescript by default. Specially now that nodejs is creating solutions to support typescript (kinda) out of the box.

Also, changing to another builder should be easy.

**Comment by ianzone** [comment]
I want to keep using nest-cli because of its plugins, but I'd also want it to be able to 1. HMR, 2. bundle dependencies, 3. better speed. 

If I simply use another builder, I can't use the plugins.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
