### ISSUE TITLE
security issue in dependency

### ISSUE THREAD

**Issue by wtrzy** [nestjs/nest-cli#2710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Performing npm audit returns security issue with webpack (5.93.0).
```
# npm audit
# npm audit report

webpack  <5.94.0
Severity: moderate
Webpack's AutoPublicPathRuntimeModule has a DOM Clobbering Gadget that leads to XSS - https://github.com/advisories/GHSA-4vvj-4cpr-p986
fix available via `npm audit fix --force`
Will install @nestjs/cli@6.6.4, which is a breaking change
node_modules/@nestjs/cli/node_modules/webpack
  @nestjs/cli  6.6.4-rc.1 - 6.6.4-rc.3 || >=6.7.0
  Depends on vulnerable versions of webpack
  node_modules/@nestjs/cli

2 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
```

### Minimum reproduction code

https://github.com/advisories/GHSA-4vvj-4cpr-p986

### Steps to reproduce

1. `npm audit`
2. `npm audit fix`
3. `npm audit`

### Expected behavior

1. `npm audit`
2. `npm audit fix`
3. `npm audit | grep "found 0 vulnerabilities"`

### Package version

10.4.4

### NestJS version

10.4.1

### Node.js version

20.12.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

development environment: VSCode devcontainer running Oracle Linux 8
package manager: npm 10.5.0

Fixed version of webpack is already available - 5.94.0

**Comment by mattpass** [comment]
Same for MacOS (not that the OS matters here). Running `npm audit fix --force` drops the version waaay down to `^6.6.4` and then has more vulns at that point. :-D

npm then suggests running this again which then bumps all way up to latest (`10.4.4`) where this vuln lingers with 2 moderate severity vulns.

Overall just needs a patch up from 5.93.0 to 5.94.0.

**Comment by mattpass** [comment]
Seems to be a [PR](https://github.com/nestjs/nest-cli/pull/2704) created by security bot last week, just needs a merge.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest-cli/pull/2712
