### ISSUE TITLE
Support `typeCheck: false` to disable tsc builder type checking

### ISSUE THREAD

**Issue by micalevisk** [nestjs/nest-cli#2766]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

as of now `typeCheck` config is only useful for `swc` builder

but when using `tsc` builder, we may want to: run `nest start` with type checking disabled so we can focus on runtime errors only, specially because we cannot supply the [`--noCheck`](https://www.typescriptlang.org/tsconfig/#noCheck) flag to the underlying `tsc` program being invoked by NestJS's CLI.

### Describe the solution you'd like

- `typeCheck` defaults to `true` for `tsc` builder. This is kinda expected because the docs mention that "SWC does not perform any type checking itself (as opposed to the default TypeScript compiler)"
- when using `"typeCheck": false` on `nest-cli.json` and `tsc` builder, it should run with [`--noCheck`](https://www.typescriptlang.org/tsconfig/#noCheck) flag from tsc.

From what I tested locally, this is feasiable. It's just a matter of supplying `noCheck:true` to the `options` object that will be passed to `typescript.createProgram` calls. So it would look like this:

[demo.webm](https://github.com/user-attachments/assets/9850f62f-3502-481c-bcbf-1a7de3e34cad)

### Teachability, documentation, adoption, migration strategy

I guess this can only be introduced in NestJS v11 but I'm not sure. 

### What is the motivation / use case for changing the behavior?

1. inspired by this question on our Discord: https://discord.com/channels/520622812742811698/1298644036470444082
2. make `typeCheck` feature useful to others builders other than `swc`

**Comment by kamilmysliwiec** [comment]
> but when using tsc builder, we may want to: run nest start with type checking disabled so we can focus on runtime errors only

Wouldn't this break CLI plugins?

**Comment by micalevisk** [comment]
I'm not sure on that.

To be fair, the use case of disabling type checking isn't that good because a lot of nestjs APIs are relying on them to work correctly. So I think that we can abort this feature request this until this become a hot topic
