### ISSUE TITLE
cli/service is throwing bug

### ISSUE THREAD

**Issue by genGit963** [nestjs/nest-cli#2783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

# cmd :  nest generate service todo

Error: (0 , util_1.isNullOrUndefined) is not a function

Failed to execute command: node @nestjs/schematics:service --name=todo --no-dry-run --no-skip-import --language="ts"--source-root="src" --spec --no-flat --spec-file-suffix="spec"

### Minimum reproduction code

https://github.com/genGit963/tma

### Steps to reproduce

1. nest generate service todo

### Expected behavior

Should have generated  /src/todo/todo.service.ts and  /src/todo/todo.service.spec.ts and updated todo.module.ts @Module() providers

### Package version

^10.0.0

### NestJS version

^10.0.0

### Node.js version

23.1.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
Make sure you're using the latest version of `@nestjs/cli`.

`npm view @nestjs/cli version` to see which version is that

**Comment by micalevisk** [comment]
this was resolved but we have to wait for a new version of the `@nestjs/cli` that is using `@nestjs/schematics` v10.2.3+

**Comment by kamilmysliwiec** [comment]
`@nestjs/schematics` is not locked https://github.com/nestjs/nest-cli/blob/master/package.json#L44 so just install the latest version and you should be fine
