### ISSUE TITLE
Unmatching engines on Glob library update

### ISSUE THREAD

**Issue by jirp-upc** [nestjs/nest-cli#2785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Glob 11.0.0 specifies those engines:

`"engines": {
    "node": "20 || >=22"
  },`

while this repository specifies:

`"engines": {
    "node": ">= 16.14"
  },`
  
  This update was made from this commit: [https://github.com/nestjs/nest-cli/commit/fc6e7a166f94389a5a0378d275ef5e3b86ed7bc5](fc6e7a1)

### Minimum reproduction code

https://github.com/nestjs/nest-cli/commit/fc6e7a166f94389a5a0378d275ef5e3b86ed7bc5

### Steps to reproduce

`pnpm i `

### Expected behavior

Use a glob version that matches engines specification of this repository

### Package version

10.4.6

### Node.js version

18.17.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest-cli/pull/2786

**Comment by dnln** [comment]
@kamilmysliwiec I'm seeing this issue with `11.0.1` which looks to have been released to npm a few hours ago. 

Locally I've pinned the version to `10.4.9` which resolves the issue, but this bug seems to have been reintroduced.

**Comment by kamilmysliwiec** [comment]
@dnln 

![Image](https://github.com/user-attachments/assets/7fab8761-5691-4e6e-b367-d2241a35f9e2)

Nest CLI v11 requires Node v20
