### ISSUE TITLE
nest g app  test; The generated module name I want to be customizable

### ISSUE THREAD

**Issue by JoeABCDEF** [nestjs/nest-cli#2827]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

`
nest g app  test
`

CREATE apps/test/src/test.controller.ts (330 bytes)
CREATE apps/test/src/test.controller.spec.ts (734 bytes)
CREATE apps/test/src/test.module.ts (312 bytes)
CREATE apps/test/src/test.service.ts (157 bytes)

When I want to create a sub-app, I want to add an option to customize the name, for example: I want to be an app by default

### Describe the solution you'd like

Something like that, I only need to create a sub-app to have that, I didn't find any similar issues, and the documentation doesn't seem to have any similar configuration items
`
nest g app  test --name app
`
CREATE apps/test/src/app.controller.ts (330 bytes)
CREATE apps/test/src/app.controller.spec.ts (734 bytes)
CREATE apps/test/src/app.module.ts (312 bytes)
CREATE apps/test/src/app.service.ts (157 bytes)

### What is the motivation / use case for changing the behavior?

If the name is long or something like that, or it makes it look bloated and ugly.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
