### ISSUE TITLE
use command `nest new blog`  have error : Error: Cannot find module 'C:\Users\starry\AppData\Roaming\npm\node_modules\@nestjs\cli\bin\nest.js'

### ISSUE THREAD

**Issue by Mhist** [nestjs/nest-cli#2834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![image](https://github.com/user-attachments/assets/4fc781ae-df3f-4a60-8bbd-ce5ed2fb403a)

### Minimum reproduction code

npm install -g @nestjs/cli

### Expected behavior

need create project normally

### Package version

latest

### NestJS version

latest

### Node.js version

23.3.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by Mhist** [comment]
`npx @nestjs/cli new project-name`
it‘s ok!

![image](https://github.com/user-attachments/assets/f0383413-0a7a-4ae7-8977-d4bfa0d2d048)

**Comment by kamilmysliwiec** [comment]
I can't reproduce your issue. Have you tried reinstalling npm?

**Comment by micalevisk** [comment]
Try using `npx @nestjs/cli new`

**Comment by kamilmysliwiec** [comment]
Sounds like `npx @nestjs/cli new` works @micalevisk https://github.com/nestjs/nest-cli/issues/2834#issuecomment-2519725731
