### ISSUE TITLE
webpack build failes - Can't resolve 'class-transformer/storage'

### ISSUE THREAD

**Issue by yifanwww** [nestjs/nest-cli#2835]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Build failes with 1 module not found error:
> Module not found: Error: Can't resolve 'class-transformer/storage' in ...

### Minimum reproduction code

https://gist.github.com/yifanwww/0e843ee0d5ba66a2dfd34fe3300c66bf

### Steps to reproduce

1. `nest new test`
2. add/install `class-validator`, `class-transformer` and `@nestjs/mapped-types`
3. update `nest-cli.json` to switch builder to webpack (according to https://docs.nestjs.com/cli/monorepo#global-compiler-options)
4. create webpack.config.js with following contents (according to https://docs.nestjs.com/cli/monorepo#webpack-options):
```
module.exports = {
  externals: [],
};
```
5. add the following code to src/main.ts
```js
import { IntersectionType } from '@nestjs/mapped-types';

class DtoA {}

class DtoB {}

class DtoC extends IntersectionType(DtoA, DtoB) {}

DtoC;
```
6. `npm run build` produces 1 error

> Module not found: Error: Can't resolve 'class-transformer/storage' in ...

### Expected behavior

`lib/compiler/defaults/webpack-defaults/ts` should be upgraded as following shows

```diff
          const lazyImports = [
            '@nestjs/microservices',
            '@nestjs/microservices/microservices-module',
            '@nestjs/websockets/socket-module',
            'class-validator',
            'class-transformer',
+            'class-transformer/storage',
          ];
```

### Package version

10.4.8

### NestJS version

10.3.8

### Node.js version

20.17.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

similar to this [issue](https://github.com/nestjs/nest-cli/issues/2799)
relevant to this [issue](https://github.com/nestjs/mapped-types/issues/486#issuecomment-932715880)

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?
