### ISSUE TITLE
Path Resolution Issues in NestJS Monorepo with SWC and TSC Builders

### ISSUE THREAD

**Issue by ziyaDev** [nestjs/nest-cli#2843]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

I am facing path resolution issues when using external libraries (outside app root) in a NestJS monorepo setup. This issue arises specifically when switching between the SWC and TSC builders in NestJS.

### Minimum reproduction code

https://github.com/ziyaDev/nestjs-monorepo-repro

### Steps to reproduce

1. Clone this repository
2. Install dependencies: `pnpm install`
3. Run `nest start` (builds successfully initially)
4. Change builder to TSC in nest-cli.json
5. Run `nest start` - Notice nested build output structure:
   ```
   └── apps
       └── api
           ├── apps
           │   └── api
           │       └── src
           │           ├── main.js
           │           └── ...
   ```
6. Update `apps/api/tsconfig.build.json` outDir to `../../dist`
7. Run `nest start` - Nesting fixed but path issues remain:
   ```
   ├── packages
   │   └── sar
   │       ├── index.js
   │       └── index.js.map
   └── tsconfig.build.tsbuildinfo
   ```
8. Switch back to SWC builder in nest-cli.json
9. Run `nest start` - Get flat structure but error:
   ```
   └── dist
       ├── apps
       │   └── api
       │   └── src
       │       ├── main.js
       │       └── ...
   ```
   Error output:
   ```
   node:internal/modules/cjs/loader:1148
     throw err;
     ^

   Error: Cannot find module '/Users/ziyadev/Desktop/repos/my-project/dist/main'
       at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
       at Module._load (node:internal/modules/cjs/loader:986:27)
       at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
       at node:internal/main/run_main_module:28:49 {
     code: 'MODULE_NOT_FOUND',
     requireStack: []
   }

   Node.js v20.15.1
   ```

Note: main.js is located in the api/src folder

### Expected behavior

- The external library paths (e.g., in packages/sar) should resolve correctly relative to the app root directory (apps/api), not relative to the current working directory.

- The build output should be structured correctly and should not result in module resolution errors like Cannot find module '/dist/main'.

### Package version

^0.5.2

### NestJS version

^10.0.0

### Node.js version

v20.15.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

      System Version: macOS 12.7.5 (21H1222)
      Kernel Version: Darwin 21.6.0
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled

**Comment by kamilmysliwiec** [comment]
You shouldn't use TSC to build your packages when in NestJS Monorepo mode. Use yarn/lerna workspaces/turborepo for this instead.
