### ISSUE TITLE
Move development back onto Master branch

### ISSUE THREAD

**Issue by wbhob** [nestjs/nest-cli#29]
Having a branch specifically for development is redundant since that is what `master` is for. We'd need to coordinate an effort to merge `develop` into master, and to set master as the default branch. All PRs against develop would have to be changed to compare against master, so this would be best when there are no open PRs.

**Comment by ThomRick** [comment]
Hey @wbhob you're right about the master / develop branch redundancy.
I'll talk to @kamilmysliwiec to have full admin rights on this repo and do job !
