### ISSUE TITLE
CLI schematics integration

### ISSUE THREAD

**Issue by ThomRick** [nestjs/nest-cli#303]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
CLI schematics are in dependencies.

## Expected behavior
Schematics should be in the CLI source code.

## What is the motivation / use case for changing the behavior?
- Avoid development on 2 separate repositories.
- Reduce dependency management issues.
- Reduce release time.

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
> Schematics should be in the CLI source code.

They have to exist as 2 separate packages because other tools (e.g. `nx`, Angular Console) are using schematics separately from `@nestjs/cli`.

**Comment by ThomRick** [comment]
Right ! I didn't remember why we choose to use 2 separate packages ! 
I close the issue
