### ISSUE TITLE
serve option not present?

### ISSUE THREAD

**Issue by kmkatsma** [nestjs/nest-cli#32]
Just started using this today, and think this is pretty awesome! Something approaching a dream come true from server side framework, for those of us working with Angular.

I see there's documentation indicating the CLI has a 'serve' option for hot reload, but when I try it it doesn't seem to exist.  I just did global install with latest (shows 1.7.8 index.js)

Any suggestions for things to try?

**Comment by ThomRick** [comment]
Hello @kmkatsma 
Yes you're right ! 
The serve command is not in the nest-cli v1.7.8 but currently on merge process.

I think a change log could be great to not be in your case next times.

**Comment by MonsieurMan** [comment]
I think the real problem is that unreleased features should not end up on the default branch readme.  
Anyway a changelog can't be a bad idea ^^

**Comment by ThomRick** [comment]
Features are released on v1.8.0 ==> upgrade ;-)
Sorry for the synchronized issue
