### ISSUE TITLE
Nest CLI builders feature

### ISSUE THREAD

**Issue by marcus-sa** [nestjs/nest-cli#349]
## Is your feature request related to a problem? Please describe.

I see so many issues daily where users try to pin point their missing dependencies and circular references.

## Describe the solution you'd like

Upgrading the CLI to support AOT checking/compilation much like what the Angular CLI does.
This will allow us to pinpoint dependency issues at compile time instead of run time.
This will also solve several issues where the dependencies not resolved can be better described by their actual paths and names, whereas at runtime they'd be undefined.

**Comment by kamilmysliwiec** [comment]
I've been thinking about providing `nest build` command that should address the majority of all community issues. By making use of AST, we could preprocess the code and eliminate some of the common issues that developers face every day.

Angular CLI is using builders and runners built on top of the `@angular-devkit/architect`. However, in our case, I feel like the compilation process is incomparably easier which makes the usage of an architect a bit.. over-engineered IMO. So we can either integrate architect at the CLI level (but that would require some extra work) or just provide a build command and wrap TS compilation process with our pre-processors.

Nonetheless, that, on the other hand, will create some inconsistency in the community. People have built a wide-range of various apps based on different techs (Nx for monorepos for instance) that are just using webpack/normal TS. We probably shouldn't force them to migrate, so anything that we'd build into this command, cannot differ too much with those "default" strategies.

Anyways, feel free to tackle this issue if you have some time, PRs are welcome!
