### ISSUE TITLE
`__dirname` is `/` in monorepo mode

### ISSUE THREAD

**Issue by wxs77577** [nestjs/nest-cli#419]
`__dirname` is always `/` after I change to monorepo mode.

**Comment by iamsteeve** [comment]
I have the same problem.

**Comment by iamsteeve** [comment]
```js
// webpack.config.js
// nodeEnv for use undefined and not string 'none'
// __filename and __dirname false to use the current directory
module.exports = function(options) {
  return {
    ...options,
    optimization: {
      nodeEnv: false,
    },
    node: {
      __filename: false,
      __dirname: false,
    }
  };
}

```
Using a webpack.config.js is the best option for now, although I think it should be a default setting in the nest cli c: like NODE_ENV and __filename

This is a webpack configuration, which affects me too much ... in my case. Use __dirname to search for the entities of the application but they no longer exist, instead there is only one main.js xD
