### ISSUE TITLE
Add .gitignore when generate a new project by default

### ISSUE THREAD

**Issue by GustavoRPS** [nestjs/nest-cli#42]
Here is a reference: https://github.com/github/gitignore/blob/e68f3c0984f96ab262db7871f23a818ca0c097e2/Node.gitignore)

**Comment by GustavoRPS** [comment]
I don't get why `.gitignore` on [ThomRick/nest-typescript-starter](https://github.com/ThomRick/nest-typescript-starter) is not created when a execute te command `nest new some-app`

**Comment by ThomRick** [comment]
Hey @GustavoRPS !
The purpose is to generate the project structure without subversion configuration.
If you use SVN / Mercurial or CVS (why not) you don't want to have a .gitignore generated, isn't it ?
Can we close the issue or you want to open the discussion on https://gitter.im/nestjs/nest-cli ?

**Comment by GustavoRPS** [comment]
@ThomRick 
I understand your point. 
It is possible to handle different types of versioning system? Just asking.

**Comment by ThomRick** [comment]
Will manage .gitgnore by default and add different kind of subversion systems by asking user input should be the best for this feature.
Will mark as a feature !

**Comment by janckerchen** [comment]
+1
