### ISSUE TITLE
[FEATURE] - Add Generator Root Path Location

### ISSUE THREAD

**Issue by Pekes317** [nestjs/nest-cli#45]
It would be great if we could define where the generator creates files base on the templates.

**Comment by ThomRick** [comment]
Hey @Pekes317 
Thanks for feedbacks. 
Can you explain how you need this feature works ?

**Comment by Pekes317** [comment]
Sure, currently the Nest cli generates the templates in using a "src" folder as the root. Ex. "src/controllers/main/main.contoller.ts" It would nice to be able to change it to a different folder like "server" if the current "src" folder is being used for another component. Does that make sense?

**Comment by ThomRick** [comment]
Yeah totally !

If you want try to develop and make a PR about this cool feature ! ;-)
Start from master that will be released very soon on v2.0.0-rc1.

**Comment by ThomRick** [comment]
The CLI tool was rebuild from scratch and integrate schematics to generate assets.
Please upgrade to v4.0.0-rc1

**Comment by mmenik** [comment]
Sorry but I did not understand if this feature was implemented? thks

**Comment by iamsteeve** [comment]
This may help some who modify their nestjs to create a ```nest-cli.json``` that already comes in a generated project if it is not added and change the sourceRoot by the desired one.

``` json
{ 
    "language": "ts", 
    "sourceRoot": "src" 
} 
```
