### ISSUE TITLE
Provider best practice?

### ISSUE THREAD

**Issue by coffeestains1908** [nestjs/nest-cli#456]
Tried `nest g pr db` and generated a db.ts without the *.provider formatting.
Which got me confused because I was expecting it to follow the best practices.

Read from the docs
https://docs.nestjs.com/recipes/sql-typeorm
`Following best practices, we declared the custom provider in the separated file which has a *.providers.ts suffix.`

or am I wrong?

**Comment by kamilmysliwiec** [comment]
Provider !== custom provider.

Custom providers should be declared in the separated file. "Class-type" provider is just a JS class. Hence, according to the best practices, each class should have its own file.
