### ISSUE TITLE
Add configuration option to generate files with PascalCase instead of the default naming convention

### ISSUE THREAD

**Issue by bbenoist** [nestjs/nest-cli#462]
## I'm submitting a...

- [x] Feature request

## Current behavior

As of now, if I generate a new file with `nest g`, its is named `name.type.ts` (e.g. `my.module.ts`).

I'd like the tool to create a file named `NameType.ts` (e.g. `MyModule.ts`) so that it matches the name of the class it contains.

## Expected behavior

Ideally, a `fileNameCase` configuration option in `nest-cli.json` of type `"dot" | "pascal" | "camel" | "snake" | "kebab"` would be nice.

## Minimal reproduction of the problem with instructions

`nest g mo my` generates a file named `my.module.ts`

## What is the motivation / use case for changing the behavior?

All of my company source files are named with the same name as the classes that they include. It's a common convention we see in a lot of OOP projects.

**Comment by bbenoist** [comment]
Side-demand. It would be nice to also support naming test files with `.test.ts` instead of `.spec.ts` via a `testFileExtension` option too.

**Comment by kamilmysliwiec** [comment]
> Side-demand. It would be nice to also support naming test files with .test.ts instead of .spec.ts via a testFileExtension option too.

We're tracking this here https://github.com/nestjs/schematics/issues/143

**Comment by egodsk** [comment]
If a `fileNameCase` is introduced, should it only affect filenames, as suggested by the option name? What about directory names, if you specify that in the generate command, such as `nest g controller auth-dir/users_dir/users --no-spec`?

Should there also be introduced a `directoryNameCase` option? or should it just be a `nameCase` option that affect both files and directories? 

Something like https://www.npmjs.com/package/change-case could help implement the solution without having to worry about correct case convertions

**Comment by cyrdax** [comment]
this would be a very nice addition.  having to switch to kabob case is a huge pain for our team

**Comment by donnyroufs** [comment]
Is there any news on this?

**Comment by oonsamyi** [comment]
Is there any news on this?(

**Comment by hydra13** [comment]
Is there any news on this? Do you need any help?

**Comment by kamilmysliwiec** [comment]
Contributions are more than welcome! @hydra13

**Comment by erie0210** [comment]
Hi, is this issue still on going? I need this feature (with camelcase) and want to take a look if it's still valid.  @kamilmysliwiec

**Comment by bennycode** [comment]
@kamilmysliwiec can you point me to the code which generates the files? I want to try implementing support for file names in PascalCase. 🙂

**Comment by micalevisk** [comment]
@bennycode
all templates lives here: https://github.com/nestjs/schematics
and are chosen here: https://github.com/nestjs/nest-cli/blob/master/actions/generate.action.ts

**Comment by espoal** [comment]
I started working on a [draft PR](https://github.com/nestjs/nest-cli/pull/2208) for this feature. @kamilmysliwiec or @micalevisk I would love some feedback!

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest-cli/pull/2208

**Comment by 0xhssn** [comment]
hey @bbenoist @kamilmysliwiec , 

I've been looking at this issue about for quite some time. It's something my team would also greatly benefit from. I can take an attempt at it. 

I noticed that there are some PRs regarding it [Schematics #1501](https://github.com/nestjs/schematics/pull/1501), #2208 and [Docs #2886](https://github.com/nestjs/docs.nestjs.com/pull/2886)   

Is there a specific reason for which you guys dropped it? Bcs I would like to dig in if there isnt anything blocking
