### ISSUE TITLE
Nest build resolving TS aliases with .ts extension

### ISSUE THREAD

**Issue by dobrysmak** [nestjs/nest-cli#481]
## I'm submitting a...
<pre><code>
[ ] Regression
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
`nest build` converts *.ts files to *.js files and rewerites TS aliased BUT it's writing .ts files instead of .js. 

## Expected behavior
`dist/app.controller.js` 
```
...
const app_service_ts_1 = require("./app.service.js");
...
```

## Minimal reproduction of the problem with instructions
1. Create nestjs app `nest new test-nest`
2. Add ts alias for src/app.service.ts in tsconfig.json file
```
"paths": {
      "@test/service": ["src/app.service.ts"]
    }
```
3. Update imports for app.service in other files
4. run `npm run build`
5. run `npm run start:prod`

## Environment
```
[System Information]
OS Version     : macOS Catalina
NodeJS Version : v10.17.0
NPM Version    : 6.11.3
[Nest Information]
platform-express version : 6.7.2
common version           : 6.7.2
core version             : 6.7.2
```

Anyone encountered this issue?

**Comment by jmcdo29** [comment]
You're specifically mapping `@test/service` to a typescript file in this case. It should map to `src/app.service` instead so that it can resolve to typescript and javascript

**Comment by kamilmysliwiec** [comment]
Just remove `.ts` extension from your mapping
