### ISSUE TITLE
add -r (node --require) flag in nest start command 

### ISSUE THREAD

**Issue by neerajyadav** [nestjs/nest-cli#488]
## Is your feature request related to a problem? Please describe.
`nest start` command should have option to accept `-r` flag same as like `node -r`. For config management I'm using `.env` file and during development I want to load environment variables from this `.env` file. On production server these environment variables should already be present. I'm using [`dotenv`](https://www.npmjs.com/package/dotenv) for this. I installed `dotenv` as dev dependency and want to use it via `-r` flag. In earlier versions of `nest` I was using `dotenv` like
```
"start:local": "ts-node -r tsconfig-paths/register -r dotenv/config src/main.ts"
```    
In latest version `start:dev` is defined via `nest` package. like 
```
"start:dev": "nest start --watch",
```
This does not allow me to add `-r` flag in command.

## Describe the solution you'd like
`nest start` should have a flag `--r` to require package via command. Something like `npm start --r dotenv/config`. 

## What is the motivation / use case for changing the behavior?
Align `npm start` command with node usage.

**Comment by kamilmysliwiec** [comment]
Please, install the latest version of NestJS CLI. Once it's installed, try this:

```
nest start --watch -e "node -r dotenv/config"
```
Alternatively, you can use `--exec` instead of `-e`

**Comment by vh13294** [comment]
I tried to add .env path, but it is not wokring.

"nest start -e 'node -r dotenv/config dotenv_config_path=env/.env.development'"

**Comment by skborey** [comment]
@vh13294  
I've used `cross-env` package to help setting dotenv_config_path.

It works if run on terminal:

```
nest start --watch --exec 'cross-env dotenv_config_path=.env.development node -r dotenv/config'
```

but when run as script in package.js it throw error of `unknown option '-r'`

```
"start:dev": "nest start --watch --exec 'cross-env dotenv_config_path=.env.development node -r dotenv/config'",
"start:local": "nest start --watch --exec 'cross-env dotenv_config_path=.env.local node -r dotenv/config'"
```

---
I would like to add that script to package.js. If anyone have any update, could you share please.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
