### ISSUE TITLE
linux build Error

### ISSUE THREAD

**Issue by LLLLLamHo** [nestjs/nest-cli#497]
## Current behavior
I am running nest build command in centos of Linux system, but I Cannot find module
![image](https://user-images.githubusercontent.com/19260349/70614271-29ede880-1c45-11ea-9a4a-1579e476e9e8.png)
But I run it on my MAC and it compiles。

"@nestjs/common": "6.7.2",
"@nestjs/core": "6.7.2",
"@nestjs/cli": "6.9.0",

## Expected behavior
Can compile normally under Linux

## Environment

<pre><code>
Nest version: 6.7.2
 
For Tooling issues:
- Node version: v8.14.0
- Platform:  Linux

**Comment by cdash04** [comment]
I have the same problem, but it's building just fine on my computer but not in my GitHub actions workflow. 

<img width="942" alt="Capture d’écran, le 2020-01-17 à 20 18 52" src="https://user-images.githubusercontent.com/25347704/72656043-b8e9d100-3966-11ea-8cca-f1f15f65d0c3.png">

Only some classes from my domain aren't found.

Here is my package.json

`{
  "name": "buildavoter",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "license": "MIT",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "tslint -p tsconfig.json -c tslint.json",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^6.7.2",
    "@nestjs/core": "^6.7.2",
    "@nestjs/mongoose": "^6.1.2",
    "@nestjs/platform-express": "^6.7.2",
    "mongoose": "^5.8.7",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.0",
    "rxjs": "^6.5.3"
  },
  "devDependencies": {
    "@nestjs/cli": "^6.9.0",
    "@nestjs/schematics": "^6.7.0",
    "@nestjs/testing": "^6.7.1",
    "@types/express": "^4.17.2",
    "@types/jest": "^24.0.18",
    "@types/node": "^12.7.5",
    "@types/supertest": "^2.0.8",
    "jest": "^24.9.0",
    "prettier": "^1.18.2",
    "supertest": "^4.0.2",
    "ts-jest": "^24.1.0",
    "ts-loader": "^6.1.1",
    "ts-node": "^8.4.1",
    "tsconfig-paths": "^3.9.0",
    "tslint": "^5.20.1",
    "typescript": "^3.7.4"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".spec.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}
`

and here is my workflow

`name: Node CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm run lint
        npm test
      env:
        CI: true
`

also tried with `npm install` instead of `npm ci` and `npm run build` instead of `npm run build --if-present`

**Comment by korsour** [comment]
Facing the same issue

> I have the same problem, but it's building just fine on my computer but not in my GitHub actions workflow which is a linux machine.

**Comment by maitrungduc1410** [comment]
I have same problem, and finally I found out that NodeJS version 8.x is not working (at the moment: Oct 2020)

Node 10 and 12 work fine

**Comment by mustafasheikh1** [comment]
I having the same issue here but in pipelines
<img width="1031" alt="Screenshot 2021-02-23 at 1 31 45 AM" src="https://user-images.githubusercontent.com/41143843/108766374-e72cdd80-7576-11eb-9431-b6b06bcb2130.png">

**Comment by jmcdo29** [comment]
Thanks for reporting, but none of you have done what Kamil has asked and [provided a minimum reproduction](http://minimum-reproduction.wtf)/ The stack traces and build errors don't help much if we can't see the code producing the errors.

**Comment by mustafasheikh1** [comment]
It's hard to provide a code sample, I'll try, the GitHub actions and my server both use ubuntu 20.04, so it's pretty sure the problem occurs with Linux env, moreover; I have noticed in build sometime the directories aren't mapping with the write casing, macOS is somehow handling this behaviour but  Linux isn't.
While I was surfing StackOverflow I can across this

[Link](https://stackoverflow.com/questions/62180250/nest-build-fails-in-pipeline-cannot-find-modules-which-can-be-found-when-buildi)

as for what I did for the time being
- changed all directories to lowercase
- made a build my local machine. (macOS) (BigSur) (11.2.1) with node (v14.15.4)
- SCP the dist to the server and ran it :p and somehow it's working

**Comment by jmcdo29** [comment]
If it helps to know, Linux file directories are case sensitive, while MacOS directories are not. So whle on MacOS `src/Mailer/mailer.service` may be valid, it may **need** to be `src/mailer/mailer.service` on Linux. Most of the time when dealing with file directories for code, i personally prefer to keep everything lowercase, just makes it easier to look at and read from, in my opinion.

**Comment by mustafasheikh1** [comment]
I don't know to happy or sad right now, but I did the following
- VSCode was ignoring the case  sensitiveness
- so I cross-checked the paths with the errors I was getting on Github actions
- fixed all the paths
- all the errors are gone and my ci/cd and server are working accordingly.
