### ISSUE TITLE
[BUG] - Generate Command Error

### ISSUE THREAD

**Issue by John0x** [nestjs/nest-cli#55]
Hey, I'm inside a freshly generated nest project (generated by the cli) and tried to run ``nest g module test``, which gives me this error:
````
ENOENT: no such file or directory, mkdir 'D:\D:\D:'
````

Windows 10 (newest updates)
64bit

**Comment by ThomRick** [comment]
Hum super weird about the mkdir error !
I'll check it out soon

**Comment by ChaoticLoki** [comment]
Seems to be an issue with the reducer in the function `createRecursiveDirectory(folder)` in the `./src/commands/generate/asset.emitter.ts` file.

**Comment by ThomRick** [comment]
Hey @ChaoticLoki 
I'll reproduce the issue also 

It will be fixed soon with the @angular-devkit/schematics template engine !!!

**Comment by zanjs** [comment]
I'll reproduce the issue also @ChaoticLoki  😭😭😭😭

**Comment by weeco** [comment]
Same issue here, I am available in case you need more information to debug.

**Comment by ThomRick** [comment]
The CLI tool was rebuild from scratch and integrate schematics to generate assets.
Please upgrade to v4.0.0-rc1
