### ISSUE TITLE
[BUG] nest new isnt working on ubuntu - getting generate warning

### ISSUE THREAD

**Issue by hershko765** [nestjs/nest-cli#57]
Step to reproduce:
1. On fresh installation of ubuntu, i installed nestjs/cli globally:
```
sudo npm install -g @nestjs/cli
```

2. Then i tried to create new project:
```
nest new myapp
```

3. Got the following output:
```
[ WARN ] - Can't execute generate and serve commands until the project is not initialized
```

Note:
- i also tried the following commands:
```
nest new myapp ./myapp
nest new myapp ~/projects/myapp
nest new myapp /home/users/me/myapp
```
All resulted in the same output as above
- i also tried to remove and re-install it
- Node version 8.9.4
- NPM version 5.6.0

**Comment by ThomRick** [comment]
Hey @hershko765,

Thanks for the feedbacks ! :-)

In fact it is perfectly working but it just indicates that the generate and serve commands will not work until you did not create a new project.

Let's try and let me know to close the issue ;-)

**Comment by hershko765** [comment]
It doesnt create the project at all, nest new command suppose to create the directory currect?

**Comment by ThomRick** [comment]
What ? You don't have the myapp dir when you execute `nest new myapp` ?

**Comment by hershko765** [comment]
yes, but it was my bad, all famus "sudo" permission crap, with sudo it working fine and generating, you can  close :)

**Comment by ThomRick** [comment]
OK thanks !
