### ISSUE TITLE
npx package not working

### ISSUE THREAD

**Issue by lookapanda** [nestjs/nest-cli#590]
I've just tested and `npx nest new APP` works fine.

_Originally posted by @kamilmysliwiec in https://github.com/nestjs/nest-cli/issues/224#issuecomment-586143953_

I just tried it too and it does not work:

```
% npx nest new my-app
npx: installed 1 in 1.772s
command not found: nest
```

**Comment by kamilmysliwiec** [comment]
I've just updated my post. Use `npx @nestjs/cli new APP` instead. `nest` is just a random package not related to NestJS at all
