### ISSUE TITLE
nest serve [ WARN ] - Can't execute generate and serve commands until the project is not initialized 

### ISSUE THREAD

**Issue by theunreal** [nestjs/nest-cli#60]
I didn't start my project with the nest CLI, but I want to use the CLI in my nest project.

Why do I get the following error?

`nest serve [ WARN ] - Can't execute generate and serve commands until the project is not initialized `

**Comment by ThomRick** [comment]
Hey @theunreal,

Thanks for feedbacks.
 
Do you have a nestconfig.json file in your project directory ?
If not the configuration can't be loaded and the message is displayed.

I could add this description in order to be more friendly :-)

**Comment by theunreal** [comment]
Thanks @ThomRick , I don't have this file in my project directory and I have no idea how it should look like.
I think documentation for this file can be very helpful.

**Comment by ThomRick** [comment]
You're welcome @theunreal,

You can find the description of this file in the repository README.md file.

Let me know if everything is ok to close the issue ;-)

**Comment by theunreal** [comment]
Thanks @ThomRick , but I get:

```
'.' is not recognized as an internal or external command,
operable program or batch file.
```

I see it reported at https://github.com/nestjs/nest-cli/issues/59

**Comment by ThomRick** [comment]
Thanks a lot for the feedbacks @theunreal !
