### ISSUE TITLE
[ERROR] Generate Module

### ISSUE THREAD

**Issue by sofyanhadia** [nestjs/nest-cli#61]
Environment:
- OSX: Sierra 
- NodeJS version: 9.3.0
- NPM version: 5.6.0
- nest-cli version: 2.0.0-rc.3

Command:
`nest generate module admin`

Error message:
```
create [WORKING_DIR]/src/modules/admin/admin.module.ts

Unexpected token . in JSON at position 36
```
Note: `modules/admin/admin.modulet.ts` was created, but other files were not

**Comment by ThomRick** [comment]
Hey @sofyanhadia 

Thanks for the feedbacks

Can you copy / paste your app.module.ts ?

**Comment by ThomRick** [comment]
The CLI tool was rebuild from scratch and integrate schematics to generate assets.
Please upgrade to v4.0.0-rc1
