### ISSUE TITLE
Nest Serve Error

### ISSUE THREAD

**Issue by mayordwells** [nestjs/nest-cli#63]
Following the instruction on this page - https://www.npmjs.com/package/@nestjs/cli

`nest new my-app --repository https://github.com/ThomRick/nest-typescript-starter`
First I think npm install should be run alongside the creation of the app. Since that's what CLIs do. 

Well after I run `npm install`, another thing is that when you run `nest s`, it doesn't work according to the instruction. But running `nest serve` however, it says it can't find main.ts in the src folder. While in the typescript-starter app, it is server.ts, because the name of the starter file in the starter project is server.ts

Also when you run `nest new my-app` and then run npm install and then run `nest serve` it says it can't find server.ts, so had to change the name of the entryFile in nestconfig.json to main.ts

There are some inconsistencies in the naming of the file. And the set up of the nestconfig.json

**Comment by ThomRick** [comment]
The CLI tool was rebuild from scratch and integrate schematics to generate assets.
Please upgrade to v4.0.0-rc1
