### ISSUE TITLE
Cannot execute nest serve command on Windows (4.0.0-rc1)

### ISSUE THREAD

**Issue by dbratsun** [nestjs/nest-cli#70]
After run **nest serve** on Windows (upgrade to 4.0.0-rc1) the simple help information (as after **nest** command) appears.

**Comment by ThomRick** [comment]
The nest serve command was removed in this version.
Use :
``` shell
$ npm run start:dev 
      OR
$ yarn start:dev
```

**Comment by dbratsun** [comment]
OK, this works! Pleas change start page of this project.

**Comment by ThomRick** [comment]
Done ! Thanks for feedbacks :-)

**Comment by ThomRick** [comment]
By the way the documentation about the CLI was not yet merged on docs.nestjs.com
Just run ```nest``` to have usable command.
