### ISSUE TITLE
Create new project

### ISSUE THREAD

**Issue by kamalkech** [nestjs/nest-cli#708]
node: v12.16.3
npm: v6.9.0
nest: v7.1.4
os: macos high sierra
after run `nest new myproject`

i get this error:

```
Failed to execute command: npm install --silent
✖ Installation in progress... ☕
🙀  Packages installation failed, see above
```

above cannot found any error message
any idea to fixe this issue ?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
