### ISSUE TITLE
npm install -g @nestjs/cli notsup on watchpack-chokidar. wanted: node:<8.10.0

### ISSUE THREAD

**Issue by miohtama** [nestjs/nest-cli#752]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[X] Documentation issue or request
[ ] Support request
</code></pre>

There is a scary warning that happens on Node v12 LTS. Note that this is a different bug what was [reported earlier](https://github.com/nestjs/nest-cli/issues/724). This is mostly  a cosmetic issue that confuses new users.

## Current behavior

```
npm install -g @nestjs/cli
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
/Users/moo/.nvm/versions/node/v12.16.1/bin/nest -> /Users/moo/.nvm/versions/node/v12.16.1/lib/node_modules/@nestjs/cli/bin/nest.js

> fsevents@1.2.13 install /Users/moo/.nvm/versions/node/v12.16.1/lib/node_modules/@nestjs/cli/node_modules/watchpack-chokidar2/node_modules/fsevents
> node install.js

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"12.16.1","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0

+ @nestjs/cli@7.2.0
added 492 packages from 353 contributors in 64.889s
```

## Expected behavior

`npm install -g @nestjs/cli` works on Node v12 without any warnings.

## Minimal reproduction of the problem with instructions

This is a local macOS environment, so I do not know if this is easily reproducible.

## Environment

macOS 10.15.4
@nestjs/cli 7.2.0

```
npm --version
6.13.4
```

```
node --version
v12.16.1
```

**Comment by miohtama** [comment]
Closing this issue, as this is does not prevent the actual installation, but the warning messaging was somewhat misleading. Looks like NestJS can still run.

**Comment by miohtama** [comment]
Reopened by the recommendation to see if anyone else would know if there is a way to supress this warning.

**Comment by kamilmysliwiec** [comment]
This issue is caused by `webpack` https://github.com/webpack/webpack/issues/10924
