### ISSUE TITLE
Echoing out the active port on startup

### ISSUE THREAD

**Issue by miohtama** [nestjs/nest-cli#754]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[X] Feature request
[ ] Documentation issue or request
[ ] Support request 
</code></pre>

## Current behavior

When NestJS starts it is not possible to know what IP or port needs to be used to access the  server.

## Expected behavior

Like other dev servers (Angular, Express.js, etc.) it is newcome friendly behaviour to echo pack the current bound port to the user.

E.g.

```
[Nest] 68846   - 06/14/2020, 12:35:43 PM   [NestApplication] Nest application successfully started,running at http://localhost:3000
```

## Minimal reproduction of the problem with instructions

```
npm run start

> backend@0.0.1 start /Users/moo/code/candidates/fullstack-exercise/backend
> nest start

[Nest] 68846   - 06/14/2020, 12:35:43 PM   [NestFactory] Starting Nest application...
[Nest] 68846   - 06/14/2020, 12:35:43 PM   [InstanceLoader] AppModule dependencies initialized +15ms
[Nest] 68846   - 06/14/2020, 12:35:43 PM   [RoutesResolver] AppController {}: +7ms
[Nest] 68846   - 06/14/2020, 12:35:43 PM   [RouterExplorer] Mapped {, GET} route +3ms
[Nest] 68846   - 06/14/2020, 12:35:43 PM   [NestApplication] Nest application successfully started +3ms
```

## What is the motivation / use case for changing the behavior?

This gives better dev experience for people who do only little work with NestJS, so they do not need to figure out the endpoint parameters from configs or documentation.

## Environment

```
 _   _             _      ___  _____  _____  _     _____
| \ | |           | |    |_  |/  ___|/  __ \| |   |_   _|
|  \| |  ___  ___ | |_     | |\ `--. | /  \/| |     | |
| . ` | / _ \/ __|| __|    | | `--. \| |    | |     | |
| |\  ||  __/\__ \| |_ /\__/ //\__/ /| \__/\| |_____| |_
\_| \_/ \___||___/ \__|\____/ \____/  \____/\_____/\___/


[System Information]
OS Version     : macOS Catalina
NodeJS Version : v12.16.1
NPM Version    : 6.14.5 

[Nest CLI]
Nest CLI Version : 7.2.0 

[Nest Platform Information]
platform-express version : 7.0.0
common version           : 7.0.0
core version             : 7.0.0
```

**Comment by jmcdo29** [comment]
Looks like [it got added to the samples](https://github.com/nestjs/nest/pull/3926), and there was talks of adding it to the schematic, but it seems that never came through. Would you like to make a PR for it?

**Comment by kamilmysliwiec** [comment]
This was discussed a few times already and there's no plan to add it to the base template at the moment.
