### ISSUE TITLE
Monitor for changes and restart server in development

### ISSUE THREAD

**Issue by mayordwells** [nestjs/nest-cli#76]
One thing I find to be really frustrating when developing with Nestjs is the fact that I have to restart the server everytime I make little changes to my code base. 
After doing a little research I found out that is what [nodemon](http://nodemon.io/) is good for. 
Development will be so much easier if this feature is available upon creation of a new project. 

Please consider it. 
Thanks for looking into it.

**Comment by dmtw** [comment]
if you generate your app with nest cli this is already in the package.json scripts.
`npm run start:dev`

**Comment by mayordwells** [comment]
Thanks for your reply. usually, I just run `npm start` and never got my app to recompile when I make a change. I feel like that feature should just be available by default without `npm run start:dev`. 
But it's good to know it already exists. Going to give it a try now.

**Comment by ThomRick** [comment]
build and serve commands will be the next features
