### ISSUE TITLE
TypeScript "importsNotUsedAsValues" compiler option doesn't take effect while using path alias

### ISSUE THREAD

**Issue by miZyind** [nestjs/nest-cli#783]
## I'm submitting a...
```
[ ] Regression
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
```

## Current behavior
Here are the typescript settings and the minimum sample code:
```json
// tsconfig.json
{
  "include": ["src", "typings"],
  "exclude": ["dist", "node_modules"],
  "compilerOptions": {
    // Avoid to emit unused imports for side effects (this is the default option even if I didn't set it up)
    "importsNotUsedAsValues": "remove",
    "isolatedModules": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "baseUrl": ".",
    "paths": {
      "#configs/*": ["src/configs/*"],
    },
    // ...
  }
}
```
```typescript
// src/configs/app.ts

export = {
  name: 'Example App',
  // ...
};
```
```typescript
// src/configs/index.ts

import type App from '#configs/app'; // TypeScript 3.8 "Type-Only Imports and Exports" syntax

type AppConfig = typeof App;

export type { AppConfig };
```

Build the project through NestJS-CLI with the command: `nest build`

The output file:
```javascript
// dist/configs/index.js

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// Shouldn't emit the following 2 lines since I imported the "Type" only
const tslib_1 = require("tslib");
const app_1 = tslib_1.__importDefault(require("./app"));
```

The output would be correct if I only modify `src/configs/index.ts` to the following code:
```typescript
// src/configs/index.ts

import type App from './app'; // import directly without using "Path Alias"

type AppConfig = typeof App;

export type { AppConfig };
```

Build the project again through `nest build`

The output file:
```javascript
// dist/configs/index.js

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
```

## Expected behavior
The following code:
```typescript
// src/configs/index.ts

import type App from '#configs/app';

type AppConfig = typeof App;

export type { AppConfig };
```
should emit the following result:
```javascript
// dist/configs/index.js

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
```

## Minimal reproduction of the problem with instructions
The same as the description of `Current behavior`

## What is the motivation / use case for changing the behavior?
`Path Alias` function should emit the same code as the output of original `tsc`

## Environment
```
[System Information]
OS Version     : macOS Catalina
NodeJS Version : v14.2.0
YARN Version    : 1.22.4 

[Nest CLI]
Nest CLI Version : 7.4.1 

[Nest Platform Information]
platform-express version      : 7.3.1
common version                : 7.3.1
config version                : 0.5.0
core version                  : 7.3.1
```

**Comment by kamilmysliwiec** [comment]
Please, report this issue in this repo instead https://github.com/dividab/tsconfig-paths#readme

**Comment by miZyind** [comment]
@kamilmysliwiec Thanks for your reply. I've opened an issue for tsconfig-paths a few weeks ago. But the collaborator of it recently responded that this seems to be a problem of nest since that package only responsible for resolving paths. I'm not sure if there is anything I can help or extra information I need to provide. If so, please leave a comment here, thanks!

**Comment by JanJakes** [comment]
Just run into this and it indeed seems to be a NestJS issue, probably around https://github.com/nestjs/nest-cli/blob/master/lib/compiler/hooks/tsconfig-paths.hook.ts#L22 in particular:

1. If I just put `return node;` before the `const newNode = tsBinary.getMutableClone(node);` line, everything works as expected.
2. If I put `return newNode;` after the `const newNode = tsBinary.getMutableClone(node);` line, then type-only imports are not removed during compilation and they are present in the dist JS files when compiling with ES-modules target which results in an error when trying to run the code (`SyntaxError: The requested module '...' does not provide an export named '...'` when importing types).

When bypassing all of the `tsconfig-paths.hook.ts` and leaving paths resolution up to `tsc`, everything works as expected. That makes me think – why is this hook run for `tsc` at all? Isn't it needed just for Webpack?

In any way, this may worth reopening, what do you thing @kamilmysliwiec? Not sure what the fix should be.

**Comment by JanJakes** [comment]
One more thing I noticed – when we put the `tsconfigPathsPlugin` to the "after" hooks instead of the "before" ones [in this place](https://github.com/nestjs/nest-cli/blob/4756026224c3b0ec4540775066d3376c8a4684f8/lib/compiler/compiler.ts#L61-L62), it seems to work as well.

**Comment by RageYL** [comment]
I also encountered the same problem. For more visibility, I opened a new issue with a potential fix at the bottom: https://github.com/nestjs/nest-cli/issues/1406
