### ISSUE TITLE
Generate new module - invalid regular expression at end of pattern

### ISSUE THREAD

**Issue by ddyrcz** [nestjs/nest-cli#8]
I have blank new nest project generated with 'nest new app' command

When trying to generate new module with 'nest generate module newModule'

The: 'Invalid regular expression: /\/: \ at end of pattern' message appears

Whereas 'nest generate module new-module' works fine

CLI version: 1.7.0
Node version: 8.1.2

**Comment by ThomRick** [comment]
Hey @ddyrcz 

Thanks for the issue.
I think that problem concerns only windows users because I can't reproduce the bug on MacOS.
I'm currently looking for to solve the problem but it's not quite easy.
I wish I could figure it out as soon as possible ;-)

**Comment by ThomRick** [comment]
I think I find the reason:
I don't use normalize path during the asset copy so it probably ran into an non windows friendly path.
Let's try to normalize it. :-)

**Comment by ThomRick** [comment]
Ok I found the bug !
```typescript
new RegExp(path.sep);
```
doesn't work on Windows platform !!!

But that's not the only bug for Windows users ! A lot of work to do !
Thanks Unit Tests (I could see that if I run them on Windows platform) ><

@ddyrcz Thanks again :-)

**Comment by ThomRick** [comment]
Hey ! Please update your CLI to v1.7.5 !
I think there are other issues due to the difference between Unix and Windows platforms but this one is fixed.
Let me know the other issues you can find !
Thanks for your contribution
