### ISSUE TITLE
Unable to install nestjs cli

### ISSUE THREAD

**Issue by nickchauhan** [nestjs/nest-cli#825]
## I'm submitting a...

<pre><code>
[x] Bug report
</code></pre>

## Current behavior

In order to learn nest js, I tried installing Nest js CLI using the following command.

`npm install -g @nestjs/cli`

But I'm getting the following error.
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@nestjs%2fcli - Not found
npm ERR! 404 
npm ERR! 404  '@nestjs/cli@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```

## Expected behavior

I should be able to install nestjs cli on my local

## Environment

```
MacBook Pro 
node - v14.2.0
npm - 6.14.7
```

**Comment by kamilmysliwiec** [comment]
There's a temporary issue in NPM registry: https://status.npmjs.org/

![image](https://user-images.githubusercontent.com/23244943/89520682-86a6a080-d7de-11ea-9230-21ca2530f04c.png)
