### ISSUE TITLE
Webpack compiler does not display e.g file system permission errors

### ISSUE THREAD

**Issue by leptoquark1** [nestjs/nest-cli#868]
I'd the case that the root folder had insufficient permission, resulting in an js error when the error obj was set but not checked.

https://github.com/nestjs/nest-cli/blob/d88e4940d995d2907fc14264307945375b685b2d/lib/compiler/webpack-compiler.ts#L78

err can be set but stats undefined.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest-cli/pull/884
