### ISSUE TITLE
" npm install -g @nestjs/cli " not working on ubuntu 18.04

### ISSUE THREAD

**Issue by sachin-duhan26** [nestjs/nest-cli#875]
## Current behaviour
I followed the official documentation and tried installing Nestjs on Linux ( ubuntu 18.04 )
```
npm install -g @nestjs/cli
```

### Output
```
+ @nestjs/cli@7.5.1
added 513 packages from 352 contributors and audited 949 packages in 43.594s

21 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
now, while making  project and using "nest" command, CLI gives me an error stating "Command nest not found"

## Environment
Node Version - v10.16.3
npm version - 6.14.4
OS - Ubuntu 18.04.5

##  Screenshot
![Screenshot from 2020-09-10 23-31-10](https://user-images.githubusercontent.com/38427564/92777420-cfdda780-f3bd-11ea-849a-d4f6531d2914.png)

**Comment by jmcdo29** [comment]
Did you restart your terminal after installing the package globally?

**Comment by sachin-duhan26** [comment]
hello, @jmcdo29 
Yes, I did restart my terminal after installing the package globally, 
**but still cannot use nest command**!

**Comment by jmcdo29** [comment]
Then your path is probably set up incorrectly and isn't reading where `npm` installed the global package. If you do `echo $PATH` do you see the path to npm's global install directory? Usually, that's here: `/usr/local/lib/node` or `/usr/local/lib/node_modules`. The other option is check `npm ls -g --depth=0` to check the globall installed packages and `npm ls -g | head -1` to check where they are installed
