### ISSUE TITLE
`yarn.lock` and `package-lock.json`

### ISSUE THREAD

**Issue by andreialecu** [nestjs/nest-cli#931]
I think this is a problem. This repo seems to have both a `yarn.lock` and a `package-lock.json`.

This is definitely not recommended, and one of them will desync with the other depending on what the current developer uses.

One of them should be deleted and added to `.gitignore`

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest-cli/pull/932
