### ISSUE TITLE
Generating a "resource" with --dry-run still alters the file system

### ISSUE THREAD

**Issue by smolinari** [nestjs/nest-cli#945]
Hi,

When running

`nest generate resource test --dry-run`

a folder called `test` and two `.spec` files are still generated into the project. 

Expected result: The system shouldn't be generating anything.

Scott

**Comment by kamilmysliwiec** [comment]
I can't reproduce your issue. Are you sure that `test` directory didn't exist in your project already? Please, try again and let me know if you face any error.

**Comment by smolinari** [comment]
Hi @smolinari 

Yes, I'm positive the directory wasn't there. 

Did some further troubleshooting and decided to upgrade my Nest CLI. Now the dry run doesn't add the folder and files. Sorry to waste your time. Should have thought to upgrade first before reporting. 

Scott
