### ISSUE TITLE
Manage custom collection

### ISSUE THREAD

**Issue by ThomRick** [nestjs/nest-cli#99]
AS a user I WANT TO use my own schematics collection WHEN I run nest new
AS a user I WANT TO use my own schematics collection WHEN I run nest generate

**Comment by LukvonStrom** [comment]
Is there any plan of realising this soon? It would provide many users great value if you could implement this IMHO.

**Comment by LukvonStrom** [comment]
I implemented this in #226.
The only thing that is missing is a dynamic implementation of `buildSchematicsListAsTable()` in `generate.command.ts`, for displaying the real available Schematics (maybe by reading them from the Schematic instead of hardcoding them).
