### ISSUE TITLE
Generating a service inside of a directory stops the addition to the first found module 

### ISSUE THREAD

**Issue by RogierdeRuijter** [nestjs/nest-cli#998]
## I'm submitting a...
<pre><code>[x] Bug report</code></pre>

## Current behavior
When generating a service inside of a directory (e.g. a `services` directory). The service isn't added to the first found module.

## Expected behavior
When generating a service it is added to the first found module in the directory tree.

## Minimal reproduction of the problem with instructions
- `nest new test-app`
- `cd test-app/src`
- `nest g module test-module`
- `cd test-module`
- `mkdir services`
- `cd services`
- `nest g service test-service`

## What is the motivation/use case for changing the behavior?
I would like to organize my services inside of a `services` directory. 

## Environment
```
[System Information]
  OS Version     : macOS Big Sur
  NodeJS Version : v12.16.2
  NPM Version    : 6.14.4 

[Nest CLI]
  Nest CLI Version : 7.5.4 

[Nest Platform Information]
  platform-express version : 7.0.0
  graphql version          : 7.9.1
  common version           : 7.0.0
  core version             : 7.0.0
```

**Comment by kamilmysliwiec** [comment]
If you want Nest CLI to automatically add the service to the `providers` array`, you can't run the `nest g` command from the `services` directory as for security & performance reasons, CLI cannot go up your source files tree. So instead of running:

```bash
cd services
nest g service test-service
```

You should run:

```bash
nest g service services/test-service
```

**Comment by MustafaMDKR** [comment]
nest generate controller <controller_name> <path> [--flat]
